import { describe, expect, it } from "vitest";
import { canRecordOnMode, getCaptureMode } from "../lib/camera-session";
import { cameraPermissionErrorMessage, cameraPermissionMessage, cameraPermissionTransitionMessage, cameraReadinessCueLabel, cameraReadinessLabel, getCameraReadiness, isRecordingBlocked, shouldAnnounceCameraRestored, recordingControlLabel, shouldAnimateCameraReadiness, shouldRefreshCameraPermission } from "../lib/camera-capability";

describe("camera session adapter", () => {
  it("uses simulated capture on web", () => {
    expect(getCaptureMode("web")).toBe("simulated");
    expect(canRecordOnMode("simulated")).toBe(true);
  });
    it("uses native capture on iOS and Android", () => { expect(getCaptureMode("ios")).toBe("native"); expect(getCaptureMode("android")).toBe("native"); expect(canRecordOnMode("native")).toBe(true); });
  it("explains camera permission recovery states", () => { expect(cameraPermissionErrorMessage()).toBe("Could not check camera access. Try again or open device settings."); expect(cameraPermissionMessage(true)).toBe("Camera access is ready"); expect(cameraPermissionMessage(false, true)).toBe("Camera access is needed to record a swing. Try again when ready."); expect(cameraPermissionMessage(false, false)).toBe("Camera access is off. Enable it in device settings to record a swing."); });
  it("refreshes permissions only for active native screens", () => { expect(shouldRefreshCameraPermission("ios", true)).toBe(true); expect(shouldRefreshCameraPermission("android", true)).toBe(true); expect(shouldRefreshCameraPermission("ios", false)).toBe(false); expect(shouldRefreshCameraPermission("web", true)).toBe(false); });
  it("only announces a denied-to-granted transition", () => { expect(cameraPermissionTransitionMessage(null, true)).toBe(""); expect(cameraPermissionTransitionMessage(false, false)).toBe(""); expect(cameraPermissionTransitionMessage(false, true)).toBe("Camera access restored"); expect(cameraPermissionTransitionMessage(true, true)).toBe(""); });
  it("labels camera readiness consistently", () => { expect(getCameraReadiness("web", null)).toBe("web"); expect(getCameraReadiness("ios", null, true)).toBe("checking"); expect(getCameraReadiness("ios", { granted: true })).toBe("ready"); expect(getCameraReadiness("ios", { granted: false, canAskAgain: true })).toBe("needs-permission"); expect(getCameraReadiness("ios", { granted: false, canAskAgain: false })).toBe("settings"); expect(cameraReadinessLabel("ready")).toBe("Camera ready"); expect(cameraReadinessLabel("settings")).toBe("Open Settings"); expect(cameraReadinessCueLabel("ready", true)).toBe("Camera ready to record"); expect(cameraReadinessCueLabel("ready", false)).toBe("Camera ready"); expect(cameraReadinessCueLabel("web", true)).toBe("Web simulation"); expect(shouldAnimateCameraReadiness("ios", true)).toBe(true); expect(shouldAnimateCameraReadiness("android", true)).toBe(true); expect(shouldAnimateCameraReadiness("web", true)).toBe(false); expect(shouldAnimateCameraReadiness("ios", false)).toBe(false); expect(isRecordingBlocked("settings")).toBe(true); expect(isRecordingBlocked("ready")).toBe(false); expect(recordingControlLabel("settings")).toBe("Recording unavailable — open camera settings"); expect(recordingControlLabel("ready")).toBe("Record a swing"); expect(shouldAnnounceCameraRestored("ios", false, true)).toBe(true); expect(shouldAnnounceCameraRestored("android", false, true)).toBe(true); expect(shouldAnnounceCameraRestored("web", false, true)).toBe(false); expect(shouldAnnounceCameraRestored("ios", true, true)).toBe(false); });
});

