import React, { useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { drills } from "@/lib/golf-data";
import { ScreenContainer } from "@/components/screen-container";
import { FIGMA } from "../theme";
import { TopBar } from "../ui/TopBar";
import { LimeButton } from "../ui/LimeButton";
import { StaticCard } from "../ui/GlassCard";
import { MetricBar } from "../ui/MetricBar";

export default function FigmaDrillDetailScreen() { const router = useRouter(); const { drillId } = useLocalSearchParams<{ drillId?: string }>(); const drill = drills.find((item) => item.id === drillId) ?? drills[0]; const [step, setStep] = useState(0); const steps = drill.steps; return <ScreenContainer containerClassName="bg-[#0A120A]" safeAreaClassName="bg-[#0A120A]"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><TopBar title="DRILL DETAIL" subtitle={drill.title.toUpperCase()} back /><View style={styles.hero}><Image source={{ uri: "https://images.unsplash.com/photo-1568374567374-d3d9f97ac45f?w=1000&h=640&fit=crop&auto=format" }} style={StyleSheet.absoluteFillObject} /><View style={styles.overlay} /><View style={styles.heroCopy}><Text style={styles.badge}>AI RECOMMENDED</Text><Text style={styles.heroTitle}>{drill.title}</Text><Text style={styles.heroSubtitle}>{drill.description}</Text><Text style={styles.heroMeta}>{drill.time} · {drill.equipment}</Text></View></View><StaticCard style={styles.why}><Text style={styles.kicker}>WHY THIS DRILL</Text><Text style={styles.copy}>This drill keeps the pelvis back while maintaining rotation — the same pattern highlighted by your recent analysis.</Text><MetricBar label="Focus relevance" value={91} tone="good" /></StaticCard><View style={styles.stats}><View style={styles.stat}><Text style={styles.statLabel}>REPS</Text><Text style={styles.statValue}>10</Text></View><View style={styles.stat}><Text style={styles.statLabel}>SETS</Text><Text style={styles.statValue}>3</Text></View><View style={styles.stat}><Text style={styles.statLabel}>DURATION</Text><Text style={styles.statValue}>{drill.time}</Text></View></View><StaticCard style={styles.steps}><Text style={styles.kicker}>COACHING STEPS</Text>{steps.map((text, index) => <Pressable key={text} onPress={() => setStep(index)} style={[styles.step, step === index && styles.stepActive]}><View style={[styles.num, step === index && styles.numActive]}><Text style={[styles.numText, step === index && styles.numTextActive]}>{index + 1}</Text></View><Text style={[styles.stepCopy, step === index && styles.stepCopyActive]}>{text}</Text></Pressable>)}</StaticCard><LimeButton label={step === steps.length - 1 ? "MARK DRILL COMPLETE" : "NEXT COACHING STEP"} onPress={() => step === steps.length - 1 ? router.push("/(tabs)/progress") : setStep((current) => Math.min(current + 1, steps.length - 1))} /><Pressable onPress={() => router.push("/(tabs)/analyze")} style={styles.practiceAgain}><Text style={styles.practiceAgainText}>RECORD A SWING TO CHECK THIS FIX</Text></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 13, paddingBottom: 32, gap: 12 }, hero: { height: 230, overflow: "hidden", borderRadius: 20, backgroundColor: FIGMA.colors.black, position: "relative" }, overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(6,13,6,0.68)" }, heroCopy: { position: "absolute", left: 15, right: 15, bottom: 16 }, badge: { alignSelf: "flex-start", color: FIGMA.colors.black, backgroundColor: FIGMA.colors.lime, borderRadius: 99, paddingHorizontal: 8, paddingVertical: 4, fontSize: 8, fontWeight: "900" }, heroTitle: { color: FIGMA.colors.white, fontSize: 23, fontWeight: "900", marginTop: 8 }, heroSubtitle: { color: FIGMA.colors.textSoft, fontSize: 10, lineHeight: 15, marginTop: 3, maxWidth: 280 }, heroMeta: { color: FIGMA.colors.lime, fontSize: 9, fontWeight: "800", marginTop: 6 }, why: { gap: 8 }, kicker: { color: FIGMA.colors.mutedStrong, fontSize: 8, fontWeight: "800", letterSpacing: 0.9, marginBottom: 4 }, copy: { color: FIGMA.colors.textSoft, fontSize: 11, lineHeight: 17 }, stats: { flexDirection: "row", gap: 8 }, stat: { flex: 1, borderWidth: 1, borderColor: FIGMA.colors.border, backgroundColor: FIGMA.colors.surface, borderRadius: 13, padding: 12, alignItems: "center" }, statLabel: { color: FIGMA.colors.mutedStrong, fontSize: 8, fontWeight: "800" }, statValue: { color: FIGMA.colors.white, fontSize: 16, fontWeight: "900", marginTop: 4 }, steps: { gap: 3 }, step: { flexDirection: "row", gap: 9, alignItems: "flex-start", paddingVertical: 7, paddingHorizontal: 6, borderRadius: 11 }, stepActive: { backgroundColor: "rgba(170,255,0,0.06)" }, num: { width: 21, height: 21, borderRadius: 11, backgroundColor: FIGMA.colors.border, alignItems: "center", justifyContent: "center" }, numActive: { backgroundColor: FIGMA.colors.lime }, numText: { color: FIGMA.colors.muted, fontSize: 9, fontWeight: "900" }, numTextActive: { color: FIGMA.colors.black }, stepCopy: { flex: 1, color: FIGMA.colors.muted, fontSize: 11, lineHeight: 16 }, stepCopyActive: { color: FIGMA.colors.text }, practiceAgain: { minHeight: 44, borderRadius: 99, borderWidth: 1, borderColor: FIGMA.colors.border, backgroundColor: FIGMA.colors.surface, alignItems: "center", justifyContent: "center" }, practiceAgainText: { color: FIGMA.colors.white, fontSize: 9, fontWeight: "800", letterSpacing: 0.35 } });
