import React, { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { drills } from "@/lib/golf-data";
import { useGolfAppState } from "@/lib/golf-app-state";
import { ScreenContainer } from "@/components/screen-container";
import { FIGMA } from "../theme";
import { TopBar } from "../ui/TopBar";
import { StatusChip } from "../ui/Chip";
import { DrillRow } from "../ui/DrillRow";
import { SectionHeader } from "../ui/SectionHeader";

export default function FigmaDrillLibraryScreen() { const router = useRouter(); const { completedDrills } = useGolfAppState(); const [filter, setFilter] = useState("ALL"); const filtered = useMemo(() => filter === "ALL" ? drills : filter === "ROTATION" ? drills.filter((d) => d.title.toLowerCase().includes("step") || d.title.toLowerCase().includes("turn")) : drills.filter((d) => d.title.toLowerCase().includes("tempo")), [filter]); return <ScreenContainer containerClassName="bg-[#0A120A]" safeAreaClassName="bg-[#0A120A]"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><TopBar title="DRILL LIBRARY" subtitle="PRACTICE WITH INTENT" back /><Text style={styles.title}>Your drills</Text><Text style={styles.subtitle}>Small reps. Clear purpose. Repeatable cues.</Text><View style={styles.filters}>{["ALL","ROTATION","TEMPO"].map((item) => <StatusChip key={item} label={item} tone={item === "TEMPO" ? "medium" : "good"} active={filter === item} onPress={() => setFilter(item)} />)}</View><SectionHeader title="AI recommended" kicker="BASED ON YOUR RECENT SWINGS" /><View style={styles.list}>{filtered.map((drill, index) => <DrillRow key={drill.id} title={drill.title} description={drill.description} time={drill.time} difficulty={index === 0 ? "Intermediate" : "Beginner"} target={index === 0 ? "Early Extension" : "Tempo"} recommended={index === 0} completed={completedDrills.includes(drill.id)} onPress={() => router.push({ pathname: "/drill-detail", params: { drillId: drill.id } })} />)}</View><View style={styles.info}><Text style={styles.infoTitle}>Why these drills?</Text><Text style={styles.infoCopy}>The library stays intentionally small so every exercise connects back to a measured part of your swing.</Text></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 13, paddingBottom: 30, gap: 12 }, title: { color: FIGMA.colors.white, fontSize: 26, fontWeight: "900" }, subtitle: { color: FIGMA.colors.muted, fontSize: 11, marginTop: -4 }, filters: { flexDirection: "row", gap: 6, marginTop: 2 }, list: { gap: 8, marginTop: 4 }, info: { padding: 14, borderRadius: 14, borderWidth: 1, borderColor: FIGMA.colors.translucentLimeBorder, backgroundColor: FIGMA.colors.translucentLime }, infoTitle: { color: FIGMA.colors.lime, fontSize: 11, fontWeight: "900" }, infoCopy: { color: FIGMA.colors.textSoft, fontSize: 10, lineHeight: 15, marginTop: 4 } });
