import React from "react";
import { Image, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { FIGMA } from "../theme";
import { TopBar } from "../ui/TopBar";
import { LimeButton } from "../ui/LimeButton";
import { StaticCard } from "../ui/GlassCard";
import { StatusChip } from "../ui/Chip";

const perks = ["Unlimited swing analyses", "Deep biomechanical breakdowns", "AI drill recommendations", "Reference swing comparisons", "Long-term progress insights", "Priority coaching cues"];
export default function FigmaPremiumScreen() { const router = useRouter(); return <ScreenContainer containerClassName="bg-[#0A120A]" safeAreaClassName="bg-[#0A120A]"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><TopBar title="PREMIUM" subtitle="GOLF PERFORMANCE LAB" back /><View style={styles.hero}><Image source={{ uri: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=1000&h=650&fit=crop&auto=format" }} style={StyleSheet.absoluteFillObject} /><View style={styles.overlay} /><View style={styles.heroCopy}><View style={styles.badge}><Text style={styles.badgeText}>👑 PREMIUM</Text></View><Text style={styles.heroTitle}>Golf Performance Lab</Text><Text style={styles.heroSubtitle}>Turn every swing into a clearer practice plan.</Text></View></View><StaticCard style={styles.priceCard}><StatusChip label="7-DAY TRIAL" tone="medium" /><Text style={styles.price}>$9.99<Text style={styles.per}> / month</Text></Text><Text style={styles.cancel}>Cancel anytime · Restore purchases</Text></StaticCard><View style={styles.perks}>{perks.map((perk) => <View key={perk} style={styles.perk}><View style={styles.check}><Text style={styles.checkText}>✓</Text></View><Text style={styles.perkText}>{perk}</Text></View>)}</View><LimeButton label="GET PREMIUM NOW" onPress={() => router.back()} /><Text style={styles.footer}>Your existing local coaching data stays on this device unless you enable sync.</Text></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 13, paddingBottom: 32, gap: 12 }, hero: { height: 210, overflow: "hidden", borderRadius: 20, backgroundColor: FIGMA.colors.black, position: "relative" }, overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(6,13,6,0.70)" }, heroCopy: { position: "absolute", left: 16, right: 16, bottom: 17 }, badge: { alignSelf: "flex-start", backgroundColor: FIGMA.colors.medium, borderRadius: 99, paddingHorizontal: 10, paddingVertical: 5 }, badgeText: { color: FIGMA.colors.black, fontSize: 8, fontWeight: "900" }, heroTitle: { color: FIGMA.colors.white, fontSize: 26, fontWeight: "900", marginTop: 8 }, heroSubtitle: { color: FIGMA.colors.textSoft, fontSize: 11, marginTop: 3 }, priceCard: { alignItems: "center", gap: 4 }, price: { color: FIGMA.colors.white, fontSize: 32, fontWeight: "900", marginTop: 3 }, per: { color: FIGMA.colors.muted, fontSize: 12 }, cancel: { color: FIGMA.colors.muted, fontSize: 9 }, perks: { backgroundColor: FIGMA.colors.surface, borderWidth: 1, borderColor: FIGMA.colors.border, borderRadius: 16, padding: 12, gap: 2 }, perk: { minHeight: 39, flexDirection: "row", alignItems: "center", gap: 8 }, check: { width: 22, height: 22, borderRadius: 11, backgroundColor: "rgba(170,255,0,0.09)", alignItems: "center", justifyContent: "center" }, checkText: { color: FIGMA.colors.lime, fontSize: 12, fontWeight: "900" }, perkText: { color: FIGMA.colors.text, fontSize: 11 }, footer: { color: FIGMA.colors.mutedStrong, fontSize: 8, lineHeight: 12, textAlign: "center", paddingHorizontal: 10 } });
