import React, { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { FIGMA } from "../theme";
import { MISSION_LIBRARY } from "../data";
import { TopBar } from "../ui/TopBar";
import { SectionHeader } from "../ui/SectionHeader";
import { GlassCard } from "../ui/GlassCard";
import { ProgressPill } from "../ui/ProgressPill";
import { LimeButton } from "../ui/LimeButton";

export default function FigmaPracticePlanScreen(){const router=useRouter();const [day,setDay]=useState(1);const mission=useMemo(()=>MISSION_LIBRARY[(day-1)%MISSION_LIBRARY.length],[day]);return <ScreenContainer containerClassName="bg-[#0A120A]" safeAreaClassName="bg-[#0A120A]"><ScrollView contentContainerStyle={styles.content}><TopBar title="PRACTICE PLAN" subtitle="A simple week you can actually repeat" /><View style={styles.days}>{[1,2,3,4,5].map(d=><Pressable key={d} onPress={()=>setDay(d)} style={[styles.day,day===d&&styles.dayActive]}><Text style={[styles.dayText,day===d&&styles.dayTextActive]}>D{d}</Text></Pressable>)}</View><GlassCard style={styles.hero}><Text style={styles.kicker}>DAY {day} · 30 MIN</Text><Text style={styles.title}>{mission.title}</Text><Text style={styles.copy}>{mission.detail}</Text><ProgressPill value={mission.progress} label={`${mission.progress}% complete`} /></GlassCard><SectionHeader title="Plan" kicker="WARM-UP → FOCUS → VERIFY" /><GlassCard style={styles.plan}><View style={styles.step}><Text style={styles.stepNum}>01</Text><View><Text style={styles.stepTitle}>Warm up</Text><Text style={styles.stepCopy}>5 slow swings · feel balance and breath.</Text></View></View><View style={styles.step}><Text style={styles.stepNum}>02</Text><View><Text style={styles.stepTitle}>Focus block</Text><Text style={styles.stepCopy}>{mission.detail}</Text></View></View><View style={styles.step}><Text style={styles.stepNum}>03</Text><View><Text style={styles.stepTitle}>Verify</Text><Text style={styles.stepCopy}>Record two full swings and compare the same cue.</Text></View></View></GlassCard><LimeButton label="START PRACTICE" onPress={()=>router.push("/capture")} /></ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{padding:15,paddingBottom:30,gap:12},days:{flexDirection:"row",gap:6},day:{flex:1,height:38,borderRadius:12,borderWidth:1,borderColor:FIGMA.colors.border,backgroundColor:FIGMA.colors.surface,alignItems:"center",justifyContent:"center"},dayActive:{backgroundColor:FIGMA.colors.lime,borderColor:FIGMA.colors.lime},dayText:{color:FIGMA.colors.muted,fontSize:8,fontWeight:"900"},dayTextActive:{color:FIGMA.colors.black},hero:{gap:10},kicker:{color:FIGMA.colors.lime,fontSize:7,fontWeight:"900",letterSpacing:.8},title:{color:FIGMA.colors.white,fontSize:22,fontWeight:"900"},copy:{color:FIGMA.colors.muted,fontSize:10,lineHeight:15},plan:{gap:2},step:{flexDirection:"row",gap:10,paddingVertical:12,borderBottomWidth:1,borderBottomColor:FIGMA.colors.border},stepNum:{width:28,color:FIGMA.colors.mutedStrong,fontSize:8,fontWeight:"900",paddingTop:2},stepTitle:{color:FIGMA.colors.white,fontSize:11,fontWeight:"900"},stepCopy:{color:FIGMA.colors.muted,fontSize:9,lineHeight:14,marginTop:3,maxWidth:260}});
