import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { FIGMA } from "../theme";
import { TopBar } from "../ui/TopBar";
import { VideoStage } from "../ui/VideoStage";
import { Phase, PHASES } from "../ui/PhaseStrip";
import { StaticCard } from "../ui/GlassCard";
import { MetricBar } from "../ui/MetricBar";
import { StatusChip } from "../ui/Chip";

const focus = [{ key: "hip", label: "Hip Rotation", yours: "37°", reference: "45°", tone: "high" as const, note: "8° lower at impact." }, { key: "plane", label: "Swing Plane", yours: "52°", reference: "54°", tone: "medium" as const, note: "2° outside target." }, { key: "head", label: "Head Position", yours: "+4cm", reference: "On-axis", tone: "good" as const, note: "Minor difference." }];
export default function FigmaCompareScreen() { const [phase, setPhase] = useState<Phase>("IMPACT"); const [index, setIndex] = useState(0); const active = focus[index]; const router = useRouter(); return <ScreenContainer containerClassName="bg-[#0A120A]" safeAreaClassName="bg-[#0A120A]"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><TopBar title="PRO COMPARISON" subtitle="YOU VS REFERENCE" back /><VideoStage phase={phase} onPhaseChange={setPhase} /><StaticCard style={styles.selector}><Text style={styles.kicker}>FOCUS METRIC</Text><View style={styles.metricTabs}>{focus.map((item, i) => <Pressable key={item.key} onPress={() => setIndex(i)} style={[styles.metricTab, i === index && styles.metricTabActive]}><Text style={[styles.metricTabText, i === index && styles.metricTabTextActive]}>{item.label}</Text></Pressable>)}</View><View style={styles.compareGrid}><View style={styles.compareBox}><Text style={styles.compareLabel}>YOUR SWING</Text><Text style={styles.compareValue}>{active.yours}</Text></View><View style={styles.compareBox}><Text style={styles.compareLabel}>REFERENCE</Text><Text style={styles.compareValue}>{active.reference}</Text></View></View><StatusChip label={active.tone === "good" ? "CLOSE" : active.tone === "high" ? "MAIN GAP" : "SMALL GAP"} tone={active.tone} /><Text style={styles.note}>{active.note}</Text><MetricBar label="Similarity" value={active.tone === "high" ? 78 : active.tone === "medium" ? 91 : 96} tone={active.tone === "high" ? "medium" : "good"} /></StaticCard><Pressable onPress={() => router.push("/analysis-detail")} style={styles.deepDive}><Text style={styles.deepDiveText}>DEEP DIVE</Text></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 13, paddingBottom: 30, gap: 12 }, selector: { gap: 11 }, kicker: { color: FIGMA.colors.mutedStrong, fontSize: 8, fontWeight: "800", letterSpacing: 0.9 }, metricTabs: { flexDirection: "row", gap: 6 }, metricTab: { flex: 1, borderRadius: 10, backgroundColor: FIGMA.colors.surfaceQuiet, borderWidth: 1, borderColor: FIGMA.colors.border, paddingVertical: 9, paddingHorizontal: 4, alignItems: "center" }, metricTabActive: { backgroundColor: FIGMA.colors.lime, borderColor: FIGMA.colors.lime }, metricTabText: { color: FIGMA.colors.muted, fontSize: 8, fontWeight: "800", textAlign: "center", lineHeight: 11 }, metricTabTextActive: { color: FIGMA.colors.black }, compareGrid: { flexDirection: "row", gap: 8 }, compareBox: { flex: 1, backgroundColor: FIGMA.colors.surfaceQuiet, borderRadius: 12, padding: 12, alignItems: "center" }, compareLabel: { color: FIGMA.colors.mutedStrong, fontSize: 7, fontWeight: "800", letterSpacing: 0.7 }, compareValue: { color: FIGMA.colors.white, fontSize: 23, fontWeight: "900", marginTop: 4 }, note: { color: FIGMA.colors.textSoft, fontSize: 10, lineHeight: 15, marginTop: -2 }, deepDive: { minHeight: 45, borderRadius: 99, borderWidth: 1, borderColor: FIGMA.colors.borderStrong, backgroundColor: FIGMA.colors.surface, alignItems: "center", justifyContent: "center" }, deepDiveText: { color: FIGMA.colors.white, fontSize: 11, fontWeight: "900", letterSpacing: 0.5 } });
