import { PropsWithChildren, useEffect, useRef } from "react";
import { ActivityIndicator, Animated, Pressable, StyleSheet, Text, View } from "react-native";
import { colors } from "@/lib/golf-data";
import { a11y, haptic } from "@/lib/ux";
import { runSafely } from "@/lib/safe-feedback";
import { reportAppError } from "@/lib/error-reporting";
import { feedbackLiveRegion } from "@/lib/feedback-accessibility";
import { loaderAccessibilityLabel } from "@/lib/loader-accessibility";
import { buttonAccessibilityState } from "@/lib/button-accessibility";
import { isSectionActionInteractive } from "@/lib/section-header-state";
import { emptyStateAccessibilityLabel } from "@/lib/empty-state-accessibility";
import { actionButtonProgressLabel, normalizeActionProgress } from "@/lib/action-button-progress";
import { createToastDismissTimer } from "@/lib/toast-timer";
import { runToastAction } from "@/lib/toast-action";

export function Loader({ visible, message = "Loading" }: { visible: boolean; message?: string }) { if (!visible) return null; return <View accessible accessibilityRole="progressbar" accessibilityState={{ busy: true }} accessibilityLabel={loaderAccessibilityLabel(message)} style={styles.loaderOverlay}><View style={styles.loaderCard}><ActivityIndicator color={colors.fairway} size="small" /><Text style={styles.loaderText}>{message}</Text></View></View>; }
export function Toast({ visible, message, tone = "info", onHide, actionLabel, onAction }: { visible: boolean; message: string; tone?: "success" | "error" | "info"; onHide?: () => void; actionLabel?: string; onAction?: () => void }) { const translateY = useRef(new Animated.Value(-90)).current; const cancelTimerRef = useRef<(() => void) | null>(null); const cancelTimer = () => { cancelTimerRef.current?.(); cancelTimerRef.current = null; }; useEffect(() => { cancelTimer(); if (!visible) return; Animated.timing(translateY, { toValue: 0, duration: 180, useNativeDriver: true }).start(); cancelTimerRef.current = createToastDismissTimer(() => { cancelTimerRef.current = null; Animated.timing(translateY, { toValue: -90, duration: 180, useNativeDriver: true }).start(() => onHide?.()); }); return cancelTimer; }, [onHide, translateY, visible]); const handleAction = () => { cancelTimer(); runToastAction(onAction, onHide); }; return <Animated.View style={[styles.toast, { backgroundColor: tone === "success" ? colors.fairway : tone === "error" ? colors.coral : colors.deep, transform: [{ translateY }] }]}><View accessible accessibilityRole="alert" accessibilityLiveRegion={feedbackLiveRegion(tone)} accessibilityLabel={message} style={styles.toastContent}><Text style={styles.toastText}>{message}</Text></View>{actionLabel && onAction ? <Pressable accessibilityRole="button" accessibilityLabel={`${actionLabel}: ${message}`} accessibilityHint="Activates recovery and dismisses this message" onPress={handleAction} style={({ pressed }) => [styles.toastAction, pressed && { opacity: 0.75 }]}><Text style={styles.toastActionText}>{actionLabel}</Text></Pressable> : null}</Animated.View>; }
export function ActionButton({ title, onPress, variant = "primary", loading = false, disabled = false, progress, children }: PropsWithChildren<{ title: string; onPress: () => void | Promise<void>; variant?: "primary" | "secondary" | "ghost"; loading?: boolean; disabled?: boolean; progress?: number }>) { const progressValue = normalizeActionProgress(progress); const label = loading ? actionButtonProgressLabel(title, progressValue) : title; return <Pressable {...a11y.button(label)} accessibilityState={buttonAccessibilityState(disabled, loading)} disabled={disabled || loading} onPress={() => { void runSafely(async () => { await haptic.light(); await onPress(); }, (error) => reportAppError("action-button", error)); }} style={({ pressed }) => [styles.button, variant === "secondary" && styles.secondaryButton, variant === "ghost" && styles.ghostButton, (pressed || disabled) && styles.buttonMuted]}>{loading ? <ActivityIndicator color={variant === "primary" ? colors.surface : colors.fairway} size="small" /> : children}<View style={styles.buttonCopy}><Text style={[styles.buttonText, variant !== "primary" && styles.secondaryButtonText]}>{loading ? "Working…" : title}</Text>{loading && progressValue !== undefined && <View accessibilityRole="progressbar" accessibilityLabel={`${Math.round(progressValue * 100)}% complete`} accessibilityState={{ busy: true }} style={styles.progressTrack}><View style={[styles.progressFill, { width: `${progressValue * 100}%` }]} /></View>}</View></Pressable>; }
export function SectionHeader({ title, action, onPress }: { title: string; action?: string; onPress?: () => void | Promise<void> }) { const actionLabel = action ? <Text style={styles.sectionAction}>{action}</Text> : null; return <View style={styles.sectionHeader}><Text accessibilityRole="header" style={styles.sectionTitle}>{title}</Text>{action ? isSectionActionInteractive(onPress) ? <Pressable accessibilityRole="button" accessibilityLabel={`${action}, ${title}`} accessibilityHint="Double tap to activate" onPress={() => { if (onPress) void runSafely(onPress, (error) => reportAppError("section-header-action", error)); }} style={({ pressed }) => [styles.sectionActionButton, pressed && { opacity: 0.7 }]}>{actionLabel}</Pressable> : actionLabel : null}</View>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <View accessible accessibilityLabel={emptyStateAccessibilityLabel(title, description)} style={styles.empty}><Text accessibilityRole="header" style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyMark} accessible={false}>◌</Text><Text style={styles.emptyDescription}>{description}</Text></View>; }
const styles = StyleSheet.create({ loaderOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(16,42,36,0.35)", alignItems: "center", justifyContent: "center", zIndex: 20 }, loaderCard: { backgroundColor: colors.surface, borderRadius: 16, padding: 18, flexDirection: "row", alignItems: "center", gap: 10 }, loaderText: { color: colors.ink, fontSize: 12, fontWeight: "700" }, toast: { position: "absolute", top: 8, left: 18, right: 18, zIndex: 30, borderRadius: 13, paddingVertical: 12, paddingHorizontal: 15, elevation: 4 }, toastContent: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, toastText: { flex: 1, color: colors.surface, fontSize: 12, fontWeight: "800" }, toastAction: { minHeight: 32, justifyContent: "center", borderRadius: 8, paddingHorizontal: 9, backgroundColor: "rgba(255,255,255,0.16)" }, toastActionText: { color: colors.surface, fontSize: 11, fontWeight: "900" }, button: { minHeight: 48, borderRadius: 15, paddingHorizontal: 17, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: colors.fairway }, secondaryButton: { backgroundColor: "#E6F1EC" }, ghostButton: { backgroundColor: "transparent" }, buttonText: { color: colors.surface, fontSize: 13, fontWeight: "800" }, buttonCopy: { flex: 1, alignItems: "center", gap: 5 }, progressTrack: { width: "100%", maxWidth: 150, height: 3, borderRadius: 3, backgroundColor: "rgba(255,255,255,0.35)", overflow: "hidden" }, progressFill: { height: "100%", borderRadius: 3, backgroundColor: colors.sun }, secondaryButtonText: { color: colors.fairway }, buttonMuted: { opacity: 0.55 }, sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, sectionActionButton: { minHeight: 44, justifyContent: "center" }, sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: "800" }, sectionAction: { color: colors.fairway, fontSize: 12, fontWeight: "800" }, empty: { alignItems: "center", justifyContent: "center", padding: 32 }, emptyMark: { color: colors.sun, fontSize: 42 }, emptyTitle: { color: colors.ink, fontSize: 16, fontWeight: "800", marginTop: 10 }, emptyDescription: { color: colors.muted, textAlign: "center", fontSize: 12, lineHeight: 18, marginTop: 5 }, });
