import { useLocalSearchParams, useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { colors } from "@/lib/golf-data";
import { useGolfAppState } from "@/lib/golf-app-state";
import { CapturePreview } from "@/components/capture-preview";
import { formatSavedCaptureMeta } from "@/lib/capture-review-meta";
import { canCompareSessions } from "@/lib/compare-availability";

export default function CompareSwingScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id?: string }>();
  const { sessions } = useGolfAppState();
  const selected = sessions.find((session) => session.id === id) ?? sessions[0];
  const baseline = sessions.find((session) => session.id !== selected?.id) ?? selected;
  if (!canCompareSessions(sessions.length) || !selected || !baseline) return <ScreenContainer><View style={styles.empty}><Text style={styles.title}>Not enough swing data</Text><Text style={styles.copy}>Save another swing to compare sessions.</Text><Pressable accessibilityRole="button" accessibilityLabel="Go back from comparison" onPress={() => router.back()} style={({ pressed }) => [styles.emptyButton, pressed && { opacity: 0.75 }]}><Text style={styles.emptyButtonText}>Go back</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer containerClassName="bg-[#F5F7F2]" safeAreaClassName="bg-[#F5F7F2]"><ScrollView contentContainerStyle={styles.container}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={() => router.back()}><IconSymbol name="chevron.left.forwardslash.chevron.right" size={22} color={colors.ink} /></Pressable><Text style={styles.headerTitle}>Compare swings</Text><View style={{ width: 22 }} /></View><Text style={styles.kicker}>SESSION COMPARISON</Text><Text style={styles.title}>{selected.club} is trending {selected.score >= baseline.score ? "up" : "down"}.</Text><Text style={styles.copy}>Use the side-by-side view to spot changes between your latest and previous swing.</Text><View style={styles.videoGrid}><View style={styles.videoCard}><CapturePreview uri={selected.videoUri ?? `simulated://${selected.id}`} /><Text style={styles.videoLabel}>Selected · {selected.date}</Text><Text style={styles.videoMeta}>{formatSavedCaptureMeta(selected)}</Text></View><View style={styles.videoCard}><CapturePreview uri={baseline.videoUri ?? `simulated://${baseline.id}`} /><Text style={styles.videoLabel}>Previous · {baseline.date}</Text><Text style={styles.videoMeta}>{formatSavedCaptureMeta(baseline)}</Text></View></View><View style={styles.scoreGrid}><View style={styles.scoreCard}><Text style={styles.cardLabel}>Selected</Text><Text style={styles.cardDate}>{selected.date}</Text><Text style={styles.score}>{selected.score}<Text style={styles.out}>/100</Text></Text></View><View style={styles.scoreCard}><Text style={styles.cardLabel}>Previous</Text><Text style={styles.cardDate}>{baseline.date}</Text><Text style={styles.score}>{baseline.score}<Text style={styles.out}>/100</Text></Text></View></View><Text style={styles.sectionTitle}>Metric changes</Text>{selected.metrics.map((metric, index) => { const previous = baseline.metrics[index] ?? metric; return <View key={metric.label} style={styles.metricRow}><View style={styles.metricCopy}><Text style={styles.metricLabel}>{metric.label}</Text><Text style={styles.metricDelta}>{metric.delta}</Text></View><Text style={styles.metricValue}>{metric.value}</Text><Text style={styles.previousValue}>{previous.value}</Text></View>; })}<View style={styles.note}><IconSymbol name="bolt.fill" size={18} color={colors.sun} /><Text style={styles.noteText}>Keep the same setup and repeat the metric with the biggest positive change in your next practice block.</Text></View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 20 }, emptyButton: { marginTop: 18, backgroundColor: colors.fairway, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 11 }, emptyButtonText: { color: colors.surface, fontSize: 12, fontWeight: "800" }, container: { padding: 20, paddingBottom: 36 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 22 }, headerTitle: { color: colors.ink, fontSize: 16, fontWeight: "800" }, kicker: { color: colors.muted, fontSize: 10, fontWeight: "800", letterSpacing: 1.1 }, title: { color: colors.ink, fontSize: 27, lineHeight: 31, fontWeight: "900", marginTop: 6 }, copy: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 8 }, videoGrid: { flexDirection: "row", gap: 10, marginTop: 20 }, videoCard: { flex: 1, backgroundColor: colors.surface, borderRadius: 15, borderWidth: 1, borderColor: colors.border, overflow: "hidden" }, videoLabel: { color: colors.muted, fontSize: 9, fontWeight: "800", paddingHorizontal: 9, paddingTop: 9 }, videoMeta: { color: colors.fairway, fontSize: 9, fontWeight: "800", paddingHorizontal: 9, paddingBottom: 9, marginTop: -5 }, scoreGrid: { flexDirection: "row", gap: 10, marginTop: 14 }, scoreCard: { flex: 1, backgroundColor: colors.surface, borderRadius: 17, borderWidth: 1, borderColor: colors.border, padding: 15 }, cardLabel: { color: colors.muted, fontSize: 10, fontWeight: "800" }, cardDate: { color: colors.muted, fontSize: 10, marginTop: 4 }, score: { color: colors.fairway, fontSize: 31, fontWeight: "900", marginTop: 10 }, out: { color: colors.muted, fontSize: 13, fontWeight: "700" }, sectionTitle: { color: colors.ink, fontSize: 18, fontWeight: "800", marginTop: 24, marginBottom: 10 }, metricRow: { flexDirection: "row", alignItems: "center", backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 13, marginBottom: 8 }, metricCopy: { flex: 1 }, metricLabel: { color: colors.ink, fontSize: 12, fontWeight: "800" }, metricDelta: { color: colors.fairway, fontSize: 10, marginTop: 3 }, metricValue: { color: colors.ink, fontSize: 14, fontWeight: "900", width: 68, textAlign: "right" }, previousValue: { color: colors.muted, fontSize: 12, width: 58, textAlign: "right" }, note: { marginTop: 18, padding: 14, borderRadius: 17, backgroundColor: "#FFF8E9", flexDirection: "row", gap: 10, alignItems: "flex-start" }, noteText: { flex: 1, color: colors.muted, fontSize: 11, lineHeight: 16 } });
