import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useState } from "react";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { colors } from "@/lib/golf-data";
import { paywallProducts } from "@/lib/monetization";
import { useMonetization } from "@/lib/monetization-state";
import { Toast } from "@/components/ui/feedback";

export default function PaywallScreen() {
  const router = useRouter();
  const { closePaywall, tier } = useMonetization();
  const [status, setStatus] = useState("");
  const dismiss = () => { closePaywall(); router.back(); };
  return <ScreenContainer containerClassName="bg-[#F5F7F2]" safeAreaClassName="bg-[#F5F7F2]"><ScrollView contentContainerStyle={styles.container}><Pressable accessibilityRole="button" accessibilityLabel="Close upgrade screen" accessibilityHint="Returns to your profile" onPress={dismiss} style={({ pressed }) => [styles.close, pressed && { opacity: 0.7 }]}><Text style={styles.closeText}>×</Text></Pressable><View style={styles.hero}><Text style={styles.eyebrow}>COACH MODE</Text><Text style={styles.title}>Build a smarter swing.</Text><Text style={styles.subtitle}>Unlock deeper metrics, pro comparisons, and unlimited practice analysis when your store connection is ready.</Text></View><View style={styles.featureCard}><Text style={styles.featureTitle}>Premium includes</Text><Text style={styles.feature}>• Advanced swing metrics</Text><Text style={styles.feature}>• Pro-template comparisons</Text><Text style={styles.feature}>• Unlimited analysis sessions</Text><Text style={styles.feature}>• Coach drill recommendations</Text></View>{paywallProducts.map((product) => <View key={product.id} style={styles.product}><View style={styles.productCopy}><Text style={styles.productTitle}>{product.title}</Text><Text style={styles.productDescription}>{product.description}</Text></View><Text style={styles.productPrice}>{product.priceLabel}</Text></View>)}<Text style={styles.note}>Purchases are disabled in this local build until RevenueCat credentials and store products are configured.</Text><View style={styles.management}><Pressable accessibilityRole="button" accessibilityLabel="Restore purchases" accessibilityHint="Checks for purchases after the store connection is configured" onPress={() => setStatus("Restore will be available after the store connection is configured.")} style={({ pressed }) => [pressed && { opacity: 0.7 }]}><Text style={styles.managementText}>Restore purchases</Text></Pressable>{tier !== "free" && <Pressable accessibilityRole="button" accessibilityLabel="Manage subscription" accessibilityHint="Opens subscription management after the store connection is configured" onPress={() => setStatus("Subscription management will open through the connected store.")} style={({ pressed }) => [pressed && { opacity: 0.7 }]}><Text style={styles.managementText}>Manage subscription</Text></Pressable>}</View><Pressable accessibilityRole="button" accessibilityLabel="Continue with free plan" style={({ pressed }) => [styles.secondary, pressed && { opacity: 0.8 }]} onPress={dismiss}><Text style={styles.secondaryText}>Continue with free plan</Text></Pressable></ScrollView><Toast visible={Boolean(status)} message={status} tone="info" onHide={() => setStatus("")} /></ScreenContainer>;
}
const styles = StyleSheet.create({ container: { padding: 20, paddingBottom: 40 }, close: { alignSelf: "flex-end", width: 34, height: 34, borderRadius: 17, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" }, closeText: { color: colors.ink, fontSize: 24, lineHeight: 26 }, hero: { marginTop: 34 }, eyebrow: { color: colors.coral, fontSize: 10, fontWeight: "900", letterSpacing: 1.3 }, title: { color: colors.ink, fontSize: 32, fontWeight: "900", marginTop: 8 }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 10 }, featureCard: { backgroundColor: colors.deep, borderRadius: 20, padding: 18, marginTop: 24 }, featureTitle: { color: colors.sun, fontSize: 14, fontWeight: "900", marginBottom: 10 }, feature: { color: colors.surface, fontSize: 13, marginTop: 8 }, product: { backgroundColor: colors.surface, borderRadius: 17, borderWidth: 1, borderColor: colors.border, padding: 15, marginTop: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, productCopy: { flex: 1, paddingRight: 12 }, productTitle: { color: colors.ink, fontSize: 14, fontWeight: "800" }, productDescription: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 4 }, productPrice: { color: colors.fairway, fontSize: 12, fontWeight: "900" }, management: { flexDirection: "row", justifyContent: "center", gap: 18, marginTop: 14 }, managementText: { color: colors.fairway, fontSize: 11, fontWeight: "800" }, note: { color: colors.muted, fontSize: 10, lineHeight: 15, textAlign: "center", marginTop: 18 }, secondary: { borderWidth: 1, borderColor: colors.fairway, borderRadius: 15, paddingVertical: 14, alignItems: "center", marginTop: 16 }, secondaryText: { color: colors.fairway, fontWeight: "800", fontSize: 13 } });
