import { Pressable, StyleSheet, Text, View } from "react-native";
import { useEffect, useState } from "react";
import { VideoView, useVideoPlayer } from "expo-video";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { colors } from "@/lib/golf-data";
import { getMediaRecoveryState, isPlayableMediaSource, mediaPlaybackRetryLabel, mediaReplacementPickerLabel, mediaRetryAttemptLabel, mediaRetryGuidance, mediaSourceLabel } from "@/lib/media-source";

export function CapturePreview({ uri, onPlayStateChange, onRetryPlayback, onChooseReplacement, isRetryingPlayback = false, isChoosingReplacement = false, retryAttempts = 0 }: { uri: string; onPlayStateChange?: (playing: boolean) => void; onRetryPlayback?: () => void; onChooseReplacement?: () => void; isRetryingPlayback?: boolean; isChoosingReplacement?: boolean; retryAttempts?: number }) {
  const isPlayable = isPlayableMediaSource(uri);
  const hasUnresolvedPlayback = uri.startsWith("ph://");
  const player = useVideoPlayer(isPlayable ? uri : null, (instance) => { instance.loop = true; });
  const [isPlaying, setIsPlaying] = useState(false);
  useEffect(() => { if (!isPlayable) return; const subscription = player.addListener("playingChange", ({ isPlaying: playing }) => setIsPlaying(playing)); return () => subscription.remove(); }, [isPlayable, player]);
  const toggle = () => { if (!isPlayable) return; if (isPlaying) player.pause(); else player.play(); onPlayStateChange?.(!isPlaying); };
  const label = mediaSourceLabel(uri);
  const recoveryState = getMediaRecoveryState(uri, retryAttempts, isRetryingPlayback);
  const retryLimitReached = recoveryState === "replacement";
  return <View style={styles.container}>{isPlayable ? <VideoView accessible accessibilityLabel="Captured swing video preview" style={styles.video} player={player} contentFit="cover" allowsFullscreen /> : <View accessible accessibilityRole="image" accessibilityLabel={hasUnresolvedPlayback ? `Captured swing preview unavailable, ${mediaRetryGuidance(retryAttempts)}` : label} style={styles.art}><View style={styles.sun} /><View style={styles.player} /><Text style={[styles.artLabel, hasUnresolvedPlayback && styles.warningLabel]}>{hasUnresolvedPlayback ? "Playback unavailable" : label}</Text><Text style={styles.artHint}>{hasUnresolvedPlayback ? (isRetryingPlayback ? "Resolving video…" : mediaRetryGuidance(retryAttempts)) : "Local preview"}</Text>{hasUnresolvedPlayback ? <Text accessibilityLiveRegion="polite" style={styles.attemptLabel}>{mediaRetryAttemptLabel(retryAttempts)}</Text> : null}</View>}<Pressable accessibilityRole="button" accessibilityLabel={isPlayable ? (isPlaying ? "Pause captured swing" : "Play captured swing") : label} accessibilityState={{ disabled: !isPlayable }} style={[styles.play, !isPlayable && styles.disabledPlay]} onPress={toggle}><IconSymbol name={isPlayable && isPlaying ? "pause.fill" : "play.fill"} size={18} color={colors.ink} /></Pressable>{hasUnresolvedPlayback && onRetryPlayback && !retryLimitReached ? <Pressable accessibilityRole="button" accessibilityLabel={mediaPlaybackRetryLabel(isRetryingPlayback)} accessibilityState={{ disabled: isRetryingPlayback, busy: isRetryingPlayback }} style={[styles.retryButton, isRetryingPlayback && styles.retryButtonDisabled]} onPress={onRetryPlayback}><IconSymbol name="arrow.clockwise" size={14} color={colors.ink} /><Text style={styles.retryText}>{isRetryingPlayback ? "Resolving…" : "Retry"}</Text></Pressable> : null}{hasUnresolvedPlayback && retryLimitReached && onChooseReplacement ? <Pressable accessibilityRole="button" accessibilityLabel={mediaReplacementPickerLabel(isChoosingReplacement)} accessibilityState={{ disabled: isChoosingReplacement, busy: isChoosingReplacement }} style={[styles.replaceButton, isChoosingReplacement && styles.replaceButtonDisabled]} onPress={onChooseReplacement}><Text style={styles.replaceText}>{isChoosingReplacement ? "Opening…" : "Choose another"}</Text></Pressable> : null}</View>;
}

const styles = StyleSheet.create({ container: { width: "100%", height: 176, borderRadius: 18, overflow: "hidden", backgroundColor: colors.fairway, position: "relative" }, video: { width: "100%", height: "100%" }, art: { flex: 1, backgroundColor: colors.fairway, overflow: "hidden" }, sun: { position: "absolute", width: 92, height: 92, borderRadius: 46, right: 25, top: 22, backgroundColor: colors.sun }, player: { position: "absolute", width: 42, height: 116, left: "45%", bottom: -8, borderRadius: 19, backgroundColor: colors.ink, transform: [{ rotate: "-8deg" }] }, artLabel: { position: "absolute", bottom: 30, left: 12, color: colors.surface, fontSize: 11, fontWeight: "800" }, warningLabel: { color: colors.sun }, artHint: { position: "absolute", bottom: 12, left: 12, color: "rgba(255,255,255,0.76)", fontSize: 10 }, attemptLabel: { position: "absolute", top: 12, left: 12, color: "rgba(255,255,255,0.86)", fontSize: 10, fontWeight: "700" }, play: { position: "absolute", alignSelf: "center", top: 67, width: 42, height: 42, borderRadius: 21, backgroundColor: colors.surface, justifyContent: "center", alignItems: "center" }, disabledPlay: { opacity: 0.64 }, retryButton: { position: "absolute", right: 10, bottom: 10, minHeight: 30, paddingHorizontal: 10, borderRadius: 15, backgroundColor: colors.sun, flexDirection: "row", alignItems: "center", gap: 5 }, retryText: { color: colors.ink, fontSize: 11, fontWeight: "800" }, retryButtonDisabled: { opacity: 0.65 }, replaceButton: { position: "absolute", right: 10, bottom: 10, minHeight: 30, paddingHorizontal: 10, borderRadius: 15, backgroundColor: colors.surface, justifyContent: "center" }, replaceText: { color: colors.ink, fontSize: 11, fontWeight: "800" }, replaceButtonDisabled: { opacity: 0.65 } });
