import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, PropsWithChildren, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { parseStoredJson } from "@/lib/local-state-recovery";
import { reportAppError } from "@/lib/error-reporting";
import { canConsumeAnalysisCredit, canUseFeature as canUsePremiumFeature, clearRewardEvents, defaultMonetizationState, Entitlement, isValidPromoCode, MonetizationEvent, MonetizationEventName, MonetizationState, normalizePromoCode, PremiumFeature, ProductTier } from "@/lib/monetization";

const STORAGE_KEY = "ai-golf-swing-coach:monetization:v1";
type MonetizationContextValue = MonetizationState & { hydrated: boolean; isPaywallOpen: boolean; canUseFeature: (feature: PremiumFeature) => boolean; openPaywall: () => void; closePaywall: () => void; recordAnalysis: () => Promise<void>; setLocalEntitlement: (tier: ProductTier, entitlements: Entitlement[]) => Promise<void>; trackEvent: (name: MonetizationEventName, metadata?: MonetizationEvent["metadata"]) => Promise<void>; applyPromoCode: (code: string) => Promise<boolean>; recordReferral: (code: string, source?: "invite" | "campaign" | "unknown") => Promise<boolean>; clearPromoCode: () => Promise<void>; clearReferral: () => Promise<void>; clearRewardHistory: () => Promise<void>; addAnalysisCredits: (amount: number) => Promise<void>; consumeAnalysisCredit: () => Promise<boolean>; canConsumeCredit: () => boolean };
const MonetizationContext = createContext<MonetizationContextValue | null>(null);

export function MonetizationProvider({ children }: PropsWithChildren) {
  const [state, setState] = useState(defaultMonetizationState);
  const [hydrated, setHydrated] = useState(false);
  const [isPaywallOpen, setPaywallOpen] = useState(false);
  useEffect(() => { let mounted = true; const hydrate = async () => { try { const value = await AsyncStorage.getItem(STORAGE_KEY); if (!mounted || !value) return; setState({ ...defaultMonetizationState, ...parseStoredJson(value, {}, undefined, (error) => reportAppError("monetization-parse", error)) }); } catch (error) { reportAppError("monetization-hydration", error); /* Keep safe defaults when local storage is unavailable. */ } finally { if (mounted) setHydrated(true); } }; void hydrate(); return () => { mounted = false; }; }, []);
  const persist = useCallback(async (next: MonetizationState) => { try { const serialized = JSON.stringify(next); await AsyncStorage.setItem(STORAGE_KEY, serialized); setState(next); } catch (error) { reportAppError("monetization-persistence", error); throw error; } }, []);
  const trackEvent = useCallback((name: MonetizationEventName, metadata?: MonetizationEvent["metadata"]) => { const event: MonetizationEvent = { id: `${name}-${Date.now()}`, name, createdAt: new Date().toISOString(), metadata }; return persist({ ...state, events: [...state.events, event].slice(-100) }); }, [persist, state]);
  const recordAnalysis = useCallback(() => persist({ ...state, analysesUsedThisPeriod: state.analysesUsedThisPeriod + 1, events: [...state.events, { id: `analysis-${Date.now()}`, name: "analysis_credit_used" as const, createdAt: new Date().toISOString() }].slice(-100) }), [persist, state]);
  const setLocalEntitlement = useCallback((tier: ProductTier, entitlements: Entitlement[]) => persist({ ...state, tier, entitlements }), [persist, state]);
  const applyPromoCode = useCallback(async (code: string) => { if (!isValidPromoCode(code)) return false; const normalized = normalizePromoCode(code); await persist({ ...state, promoCode: { code: normalized, appliedAt: new Date().toISOString() }, events: [...state.events, { id: `promo-${Date.now()}`, name: "promo_applied" as const, createdAt: new Date().toISOString(), metadata: { code: normalized } }].slice(-100) }); return true; }, [persist, state]);
  const recordReferral = useCallback(async (code: string, source: "invite" | "campaign" | "unknown" = "unknown") => { if (!isValidPromoCode(code)) return false; const normalized = normalizePromoCode(code); await persist({ ...state, referral: { code: normalized, source, recordedAt: new Date().toISOString() }, events: [...state.events, { id: `referral-${Date.now()}`, name: "referral_recorded" as const, createdAt: new Date().toISOString(), metadata: { code: normalized, source } }].slice(-100) }); return true; }, [persist, state]);
  const clearPromoCode = useCallback(() => persist({ ...state, promoCode: null }), [persist, state]);
  const clearReferral = useCallback(() => persist({ ...state, referral: null }), [persist, state]);
  const clearRewardHistory = useCallback(() => persist({ ...state, events: clearRewardEvents(state.events) }), [persist, state]);
  const addAnalysisCredits = useCallback(async (amount: number) => { const safeAmount = Math.max(0, Math.floor(amount)); if (!safeAmount) return; await persist({ ...state, analysisCredits: state.analysisCredits + safeAmount, events: [...state.events, { id: `credits-${Date.now()}`, name: "analysis_credit_added" as const, createdAt: new Date().toISOString(), metadata: { amount: safeAmount } }].slice(-100) }); }, [persist, state]);
  const consumeAnalysisCredit = useCallback(async () => { if (!canConsumeAnalysisCredit(state)) return false; await persist({ ...state, analysisCredits: state.analysisCredits - 1, events: [...state.events, { id: `credit-use-${Date.now()}`, name: "analysis_credit_used" as const, createdAt: new Date().toISOString() }].slice(-100) }); return true; }, [persist, state]);
  const value = useMemo(() => ({ ...state, hydrated, isPaywallOpen, canUseFeature: (feature: PremiumFeature) => canUsePremiumFeature(state, feature), openPaywall: () => setPaywallOpen(true), closePaywall: () => setPaywallOpen(false), recordAnalysis, setLocalEntitlement, trackEvent, applyPromoCode, recordReferral, clearPromoCode, clearReferral, clearRewardHistory, addAnalysisCredits, consumeAnalysisCredit, canConsumeCredit: () => canConsumeAnalysisCredit(state) }), [state, hydrated, isPaywallOpen, recordAnalysis, setLocalEntitlement, trackEvent, applyPromoCode, recordReferral, clearPromoCode, clearReferral, clearRewardHistory, addAnalysisCredits, consumeAnalysisCredit]);
  return <MonetizationContext.Provider value={value}>{children}</MonetizationContext.Provider>;
}
export function useMonetization() { const context = useContext(MonetizationContext); if (!context) throw new Error("useMonetization must be used inside MonetizationProvider"); return context; }
export const monetizationStorageKey = STORAGE_KEY;
