import type { MonetizationEvent } from "@/lib/monetization";

export type RewardVisualKind = "promo" | "referral" | "credits";
export type RewardHistoryItem = { id: string; label: string; detail?: string; createdAt: string; kind: RewardVisualKind; metadata: Record<string, string | number | boolean> };
const rewardEventLabels: Partial<Record<MonetizationEvent["name"], string>> = { promo_applied: "Promo code applied", referral_recorded: "Referral linked", analysis_credit_added: "Analysis credits added" };
function getRewardVisualKind(name: MonetizationEvent["name"]): RewardVisualKind | undefined { if (name === "promo_applied") return "promo"; if (name === "referral_recorded") return "referral"; if (name === "analysis_credit_added") return "credits"; return undefined; }
function formatRewardDetail(event: MonetizationEvent): string | undefined { const metadata = event.metadata ?? {}; if (event.name === "promo_applied" && typeof metadata.code === "string") return `Code ${metadata.code}`; if (event.name === "referral_recorded" && typeof metadata.source === "string") return `Source: ${metadata.source}`; if (event.name === "analysis_credit_added" && typeof metadata.amount === "number") return `${metadata.amount} credit${metadata.amount === 1 ? "" : "s"} added`; return undefined; }
export function getRewardsHistory(events: MonetizationEvent[], limit = 3): RewardHistoryItem[] { return events.filter((event) => Boolean(rewardEventLabels[event.name]) && Boolean(getRewardVisualKind(event.name))).slice().reverse().slice(0, Math.max(0, limit)).map((event) => ({ id: event.id, label: rewardEventLabels[event.name] ?? "Reward updated", detail: formatRewardDetail(event), createdAt: event.createdAt, kind: getRewardVisualKind(event.name) as RewardVisualKind, metadata: event.metadata ?? {} })); }
export function formatRewardHistoryDate(createdAt: string): string { const date = new Date(createdAt); return Number.isNaN(date.getTime()) ? "Recently" : date.toISOString().slice(0, 10); }
export function formatRewardHistoryTimestamp(createdAt: string): string { const date = new Date(createdAt); return Number.isNaN(date.getTime()) ? "Timestamp unavailable" : date.toISOString().replace("T", " ").replace(".000Z", " UTC"); }
export function formatRewardHistoryMetadata(metadata: RewardHistoryItem["metadata"]): string[] { return Object.entries(metadata).sort(([left], [right]) => left.localeCompare(right)).map(([key, value]) => `${key}: ${String(value)}`); }
export function formatRewardHistoryAccessibility(item: RewardHistoryItem): string { return [item.label, item.detail, formatRewardHistoryDate(item.createdAt)].filter(Boolean).join(", "); }
