import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario03NetworkOfflineScenario: ReleaseScenario = {
  id: '03-network-offline',
  domain: 'network',
  title: 'Release QA · Network · offline',
  risk: 'high',
  steps: [
    {
      id: '03-network-offline-step-01',
      action: 'Exercise offline recovery checkpoint 01',
      input: 'network:fixture:3:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_network_checkpoint_01',
    },
    {
      id: '03-network-offline-step-02',
      action: 'Exercise offline recovery checkpoint 02',
      input: 'network:fixture:3:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_network_checkpoint_02',
    },
    {
      id: '03-network-offline-step-03',
      action: 'Exercise offline recovery checkpoint 03',
      input: 'network:fixture:3:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_network_checkpoint_03',
    },
    {
      id: '03-network-offline-step-04',
      action: 'Exercise offline recovery checkpoint 04',
      input: 'network:fixture:3:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_network_checkpoint_04',
    },
    {
      id: '03-network-offline-step-05',
      action: 'Exercise offline recovery checkpoint 05',
      input: 'network:fixture:3:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_network_checkpoint_05',
    },
    {
      id: '03-network-offline-step-06',
      action: 'Exercise offline recovery checkpoint 06',
      input: 'network:fixture:3:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_network_checkpoint_06',
    },
    {
      id: '03-network-offline-step-07',
      action: 'Exercise offline recovery checkpoint 07',
      input: 'network:fixture:3:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_network_checkpoint_07',
    },
    {
      id: '03-network-offline-step-08',
      action: 'Exercise offline recovery checkpoint 08',
      input: 'network:fixture:3:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_network_checkpoint_08',
    },
    {
      id: '03-network-offline-step-09',
      action: 'Exercise offline recovery checkpoint 09',
      input: 'network:fixture:3:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_network_checkpoint_09',
    },
    {
      id: '03-network-offline-step-10',
      action: 'Exercise offline recovery checkpoint 10',
      input: 'network:fixture:3:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_network_checkpoint_10',
    },
    {
      id: '03-network-offline-step-11',
      action: 'Exercise offline recovery checkpoint 11',
      input: 'network:fixture:3:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_network_checkpoint_11',
    },
    {
      id: '03-network-offline-step-12',
      action: 'Exercise offline recovery checkpoint 12',
      input: 'network:fixture:3:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_network_checkpoint_12',
    },
    {
      id: '03-network-offline-step-13',
      action: 'Exercise offline recovery checkpoint 13',
      input: 'network:fixture:3:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_network_checkpoint_13',
    },
    {
      id: '03-network-offline-step-14',
      action: 'Exercise offline recovery checkpoint 14',
      input: 'network:fixture:3:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_network_checkpoint_14',
    },
    {
      id: '03-network-offline-step-15',
      action: 'Exercise offline recovery checkpoint 15',
      input: 'network:fixture:3:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_network_checkpoint_15',
    },
    {
      id: '03-network-offline-step-16',
      action: 'Exercise offline recovery checkpoint 16',
      input: 'network:fixture:3:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_network_checkpoint_16',
    },
    {
      id: '03-network-offline-step-17',
      action: 'Exercise offline recovery checkpoint 17',
      input: 'network:fixture:3:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_network_checkpoint_17',
    },
    {
      id: '03-network-offline-step-18',
      action: 'Exercise offline recovery checkpoint 18',
      input: 'network:fixture:3:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_network_checkpoint_18',
    },
    {
      id: '03-network-offline-step-19',
      action: 'Exercise offline recovery checkpoint 19',
      input: 'network:fixture:3:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_network_checkpoint_19',
    },
    {
      id: '03-network-offline-step-20',
      action: 'Exercise offline recovery checkpoint 20',
      input: 'network:fixture:3:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_network_checkpoint_20',
    },
    {
      id: '03-network-offline-step-21',
      action: 'Exercise offline recovery checkpoint 21',
      input: 'network:fixture:3:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_network_checkpoint_21',
    },
    {
      id: '03-network-offline-step-22',
      action: 'Exercise offline recovery checkpoint 22',
      input: 'network:fixture:3:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_network_checkpoint_22',
    },
    {
      id: '03-network-offline-step-23',
      action: 'Exercise offline recovery checkpoint 23',
      input: 'network:fixture:3:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_network_checkpoint_23',
    },
    {
      id: '03-network-offline-step-24',
      action: 'Exercise offline recovery checkpoint 24',
      input: 'network:fixture:3:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_network_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario03NetworkOfflineScenarioSummary = {
  id: Scenario03NetworkOfflineScenario.id,
  risk: Scenario03NetworkOfflineScenario.risk,
  stepCount: Scenario03NetworkOfflineScenario.steps.length,
  recoveryStepCount: Scenario03NetworkOfflineScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario03NetworkOfflineScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario03NetworkOfflineScenarioStep(index: number) {
  if (index < 0 || index >= Scenario03NetworkOfflineScenario.steps.length) return undefined;
  return Scenario03NetworkOfflineScenario.steps[index];
}

export function evaluateScenario03NetworkOfflineScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario03NetworkOfflineScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario03NetworkOfflineScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario03NetworkOfflineScenario.steps.length };
}
