import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario06BillingPurchaseUnavailableScenario: ReleaseScenario = {
  id: '06-billing-purchase-unavailable',
  domain: 'billing',
  title: 'Release QA · Billing · purchase unavailable',
  risk: 'critical',
  steps: [
    {
      id: '06-billing-purchase-unavailable-step-01',
      action: 'Exercise purchase unavailable recovery checkpoint 01',
      input: 'billing:fixture:6:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_billing_checkpoint_01',
    },
    {
      id: '06-billing-purchase-unavailable-step-02',
      action: 'Exercise purchase unavailable recovery checkpoint 02',
      input: 'billing:fixture:6:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_billing_checkpoint_02',
    },
    {
      id: '06-billing-purchase-unavailable-step-03',
      action: 'Exercise purchase unavailable recovery checkpoint 03',
      input: 'billing:fixture:6:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_billing_checkpoint_03',
    },
    {
      id: '06-billing-purchase-unavailable-step-04',
      action: 'Exercise purchase unavailable recovery checkpoint 04',
      input: 'billing:fixture:6:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_billing_checkpoint_04',
    },
    {
      id: '06-billing-purchase-unavailable-step-05',
      action: 'Exercise purchase unavailable recovery checkpoint 05',
      input: 'billing:fixture:6:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_billing_checkpoint_05',
    },
    {
      id: '06-billing-purchase-unavailable-step-06',
      action: 'Exercise purchase unavailable recovery checkpoint 06',
      input: 'billing:fixture:6:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_billing_checkpoint_06',
    },
    {
      id: '06-billing-purchase-unavailable-step-07',
      action: 'Exercise purchase unavailable recovery checkpoint 07',
      input: 'billing:fixture:6:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_billing_checkpoint_07',
    },
    {
      id: '06-billing-purchase-unavailable-step-08',
      action: 'Exercise purchase unavailable recovery checkpoint 08',
      input: 'billing:fixture:6:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_billing_checkpoint_08',
    },
    {
      id: '06-billing-purchase-unavailable-step-09',
      action: 'Exercise purchase unavailable recovery checkpoint 09',
      input: 'billing:fixture:6:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_billing_checkpoint_09',
    },
    {
      id: '06-billing-purchase-unavailable-step-10',
      action: 'Exercise purchase unavailable recovery checkpoint 10',
      input: 'billing:fixture:6:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_billing_checkpoint_10',
    },
    {
      id: '06-billing-purchase-unavailable-step-11',
      action: 'Exercise purchase unavailable recovery checkpoint 11',
      input: 'billing:fixture:6:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_billing_checkpoint_11',
    },
    {
      id: '06-billing-purchase-unavailable-step-12',
      action: 'Exercise purchase unavailable recovery checkpoint 12',
      input: 'billing:fixture:6:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_billing_checkpoint_12',
    },
    {
      id: '06-billing-purchase-unavailable-step-13',
      action: 'Exercise purchase unavailable recovery checkpoint 13',
      input: 'billing:fixture:6:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_billing_checkpoint_13',
    },
    {
      id: '06-billing-purchase-unavailable-step-14',
      action: 'Exercise purchase unavailable recovery checkpoint 14',
      input: 'billing:fixture:6:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_billing_checkpoint_14',
    },
    {
      id: '06-billing-purchase-unavailable-step-15',
      action: 'Exercise purchase unavailable recovery checkpoint 15',
      input: 'billing:fixture:6:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_billing_checkpoint_15',
    },
    {
      id: '06-billing-purchase-unavailable-step-16',
      action: 'Exercise purchase unavailable recovery checkpoint 16',
      input: 'billing:fixture:6:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_billing_checkpoint_16',
    },
    {
      id: '06-billing-purchase-unavailable-step-17',
      action: 'Exercise purchase unavailable recovery checkpoint 17',
      input: 'billing:fixture:6:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_billing_checkpoint_17',
    },
    {
      id: '06-billing-purchase-unavailable-step-18',
      action: 'Exercise purchase unavailable recovery checkpoint 18',
      input: 'billing:fixture:6:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_billing_checkpoint_18',
    },
    {
      id: '06-billing-purchase-unavailable-step-19',
      action: 'Exercise purchase unavailable recovery checkpoint 19',
      input: 'billing:fixture:6:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_billing_checkpoint_19',
    },
    {
      id: '06-billing-purchase-unavailable-step-20',
      action: 'Exercise purchase unavailable recovery checkpoint 20',
      input: 'billing:fixture:6:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_billing_checkpoint_20',
    },
    {
      id: '06-billing-purchase-unavailable-step-21',
      action: 'Exercise purchase unavailable recovery checkpoint 21',
      input: 'billing:fixture:6:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_billing_checkpoint_21',
    },
    {
      id: '06-billing-purchase-unavailable-step-22',
      action: 'Exercise purchase unavailable recovery checkpoint 22',
      input: 'billing:fixture:6:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_billing_checkpoint_22',
    },
    {
      id: '06-billing-purchase-unavailable-step-23',
      action: 'Exercise purchase unavailable recovery checkpoint 23',
      input: 'billing:fixture:6:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_billing_checkpoint_23',
    },
    {
      id: '06-billing-purchase-unavailable-step-24',
      action: 'Exercise purchase unavailable recovery checkpoint 24',
      input: 'billing:fixture:6:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_billing_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario06BillingPurchaseUnavailableScenarioSummary = {
  id: Scenario06BillingPurchaseUnavailableScenario.id,
  risk: Scenario06BillingPurchaseUnavailableScenario.risk,
  stepCount: Scenario06BillingPurchaseUnavailableScenario.steps.length,
  recoveryStepCount: Scenario06BillingPurchaseUnavailableScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario06BillingPurchaseUnavailableScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario06BillingPurchaseUnavailableScenarioStep(index: number) {
  if (index < 0 || index >= Scenario06BillingPurchaseUnavailableScenario.steps.length) return undefined;
  return Scenario06BillingPurchaseUnavailableScenario.steps[index];
}

export function evaluateScenario06BillingPurchaseUnavailableScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario06BillingPurchaseUnavailableScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario06BillingPurchaseUnavailableScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario06BillingPurchaseUnavailableScenario.steps.length };
}
