import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario07SharingShareUnavailableScenario: ReleaseScenario = {
  id: '07-sharing-share-unavailable',
  domain: 'sharing',
  title: 'Release QA · Sharing · share unavailable',
  risk: 'medium',
  steps: [
    {
      id: '07-sharing-share-unavailable-step-01',
      action: 'Exercise share unavailable recovery checkpoint 01',
      input: 'sharing:fixture:7:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_sharing_checkpoint_01',
    },
    {
      id: '07-sharing-share-unavailable-step-02',
      action: 'Exercise share unavailable recovery checkpoint 02',
      input: 'sharing:fixture:7:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_sharing_checkpoint_02',
    },
    {
      id: '07-sharing-share-unavailable-step-03',
      action: 'Exercise share unavailable recovery checkpoint 03',
      input: 'sharing:fixture:7:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_sharing_checkpoint_03',
    },
    {
      id: '07-sharing-share-unavailable-step-04',
      action: 'Exercise share unavailable recovery checkpoint 04',
      input: 'sharing:fixture:7:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_sharing_checkpoint_04',
    },
    {
      id: '07-sharing-share-unavailable-step-05',
      action: 'Exercise share unavailable recovery checkpoint 05',
      input: 'sharing:fixture:7:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_sharing_checkpoint_05',
    },
    {
      id: '07-sharing-share-unavailable-step-06',
      action: 'Exercise share unavailable recovery checkpoint 06',
      input: 'sharing:fixture:7:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_sharing_checkpoint_06',
    },
    {
      id: '07-sharing-share-unavailable-step-07',
      action: 'Exercise share unavailable recovery checkpoint 07',
      input: 'sharing:fixture:7:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_sharing_checkpoint_07',
    },
    {
      id: '07-sharing-share-unavailable-step-08',
      action: 'Exercise share unavailable recovery checkpoint 08',
      input: 'sharing:fixture:7:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_sharing_checkpoint_08',
    },
    {
      id: '07-sharing-share-unavailable-step-09',
      action: 'Exercise share unavailable recovery checkpoint 09',
      input: 'sharing:fixture:7:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_sharing_checkpoint_09',
    },
    {
      id: '07-sharing-share-unavailable-step-10',
      action: 'Exercise share unavailable recovery checkpoint 10',
      input: 'sharing:fixture:7:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_sharing_checkpoint_10',
    },
    {
      id: '07-sharing-share-unavailable-step-11',
      action: 'Exercise share unavailable recovery checkpoint 11',
      input: 'sharing:fixture:7:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_sharing_checkpoint_11',
    },
    {
      id: '07-sharing-share-unavailable-step-12',
      action: 'Exercise share unavailable recovery checkpoint 12',
      input: 'sharing:fixture:7:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_sharing_checkpoint_12',
    },
    {
      id: '07-sharing-share-unavailable-step-13',
      action: 'Exercise share unavailable recovery checkpoint 13',
      input: 'sharing:fixture:7:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_sharing_checkpoint_13',
    },
    {
      id: '07-sharing-share-unavailable-step-14',
      action: 'Exercise share unavailable recovery checkpoint 14',
      input: 'sharing:fixture:7:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_sharing_checkpoint_14',
    },
    {
      id: '07-sharing-share-unavailable-step-15',
      action: 'Exercise share unavailable recovery checkpoint 15',
      input: 'sharing:fixture:7:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_sharing_checkpoint_15',
    },
    {
      id: '07-sharing-share-unavailable-step-16',
      action: 'Exercise share unavailable recovery checkpoint 16',
      input: 'sharing:fixture:7:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_sharing_checkpoint_16',
    },
    {
      id: '07-sharing-share-unavailable-step-17',
      action: 'Exercise share unavailable recovery checkpoint 17',
      input: 'sharing:fixture:7:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_sharing_checkpoint_17',
    },
    {
      id: '07-sharing-share-unavailable-step-18',
      action: 'Exercise share unavailable recovery checkpoint 18',
      input: 'sharing:fixture:7:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_sharing_checkpoint_18',
    },
    {
      id: '07-sharing-share-unavailable-step-19',
      action: 'Exercise share unavailable recovery checkpoint 19',
      input: 'sharing:fixture:7:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_sharing_checkpoint_19',
    },
    {
      id: '07-sharing-share-unavailable-step-20',
      action: 'Exercise share unavailable recovery checkpoint 20',
      input: 'sharing:fixture:7:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_sharing_checkpoint_20',
    },
    {
      id: '07-sharing-share-unavailable-step-21',
      action: 'Exercise share unavailable recovery checkpoint 21',
      input: 'sharing:fixture:7:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_sharing_checkpoint_21',
    },
    {
      id: '07-sharing-share-unavailable-step-22',
      action: 'Exercise share unavailable recovery checkpoint 22',
      input: 'sharing:fixture:7:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_sharing_checkpoint_22',
    },
    {
      id: '07-sharing-share-unavailable-step-23',
      action: 'Exercise share unavailable recovery checkpoint 23',
      input: 'sharing:fixture:7:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_sharing_checkpoint_23',
    },
    {
      id: '07-sharing-share-unavailable-step-24',
      action: 'Exercise share unavailable recovery checkpoint 24',
      input: 'sharing:fixture:7:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_sharing_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario07SharingShareUnavailableScenarioSummary = {
  id: Scenario07SharingShareUnavailableScenario.id,
  risk: Scenario07SharingShareUnavailableScenario.risk,
  stepCount: Scenario07SharingShareUnavailableScenario.steps.length,
  recoveryStepCount: Scenario07SharingShareUnavailableScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario07SharingShareUnavailableScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario07SharingShareUnavailableScenarioStep(index: number) {
  if (index < 0 || index >= Scenario07SharingShareUnavailableScenario.steps.length) return undefined;
  return Scenario07SharingShareUnavailableScenario.steps[index];
}

export function evaluateScenario07SharingShareUnavailableScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario07SharingShareUnavailableScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario07SharingShareUnavailableScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario07SharingShareUnavailableScenario.steps.length };
}
