import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario08NotificationsPermissionDeniedScenario: ReleaseScenario = {
  id: '08-notifications-permission-denied',
  domain: 'notifications',
  title: 'Release QA · Notifications · permission denied',
  risk: 'medium',
  steps: [
    {
      id: '08-notifications-permission-denied-step-01',
      action: 'Exercise permission denied recovery checkpoint 01',
      input: 'notifications:fixture:8:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_01',
    },
    {
      id: '08-notifications-permission-denied-step-02',
      action: 'Exercise permission denied recovery checkpoint 02',
      input: 'notifications:fixture:8:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_02',
    },
    {
      id: '08-notifications-permission-denied-step-03',
      action: 'Exercise permission denied recovery checkpoint 03',
      input: 'notifications:fixture:8:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_03',
    },
    {
      id: '08-notifications-permission-denied-step-04',
      action: 'Exercise permission denied recovery checkpoint 04',
      input: 'notifications:fixture:8:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_04',
    },
    {
      id: '08-notifications-permission-denied-step-05',
      action: 'Exercise permission denied recovery checkpoint 05',
      input: 'notifications:fixture:8:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_05',
    },
    {
      id: '08-notifications-permission-denied-step-06',
      action: 'Exercise permission denied recovery checkpoint 06',
      input: 'notifications:fixture:8:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_06',
    },
    {
      id: '08-notifications-permission-denied-step-07',
      action: 'Exercise permission denied recovery checkpoint 07',
      input: 'notifications:fixture:8:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_07',
    },
    {
      id: '08-notifications-permission-denied-step-08',
      action: 'Exercise permission denied recovery checkpoint 08',
      input: 'notifications:fixture:8:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_08',
    },
    {
      id: '08-notifications-permission-denied-step-09',
      action: 'Exercise permission denied recovery checkpoint 09',
      input: 'notifications:fixture:8:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_09',
    },
    {
      id: '08-notifications-permission-denied-step-10',
      action: 'Exercise permission denied recovery checkpoint 10',
      input: 'notifications:fixture:8:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_10',
    },
    {
      id: '08-notifications-permission-denied-step-11',
      action: 'Exercise permission denied recovery checkpoint 11',
      input: 'notifications:fixture:8:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_11',
    },
    {
      id: '08-notifications-permission-denied-step-12',
      action: 'Exercise permission denied recovery checkpoint 12',
      input: 'notifications:fixture:8:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_12',
    },
    {
      id: '08-notifications-permission-denied-step-13',
      action: 'Exercise permission denied recovery checkpoint 13',
      input: 'notifications:fixture:8:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_13',
    },
    {
      id: '08-notifications-permission-denied-step-14',
      action: 'Exercise permission denied recovery checkpoint 14',
      input: 'notifications:fixture:8:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_14',
    },
    {
      id: '08-notifications-permission-denied-step-15',
      action: 'Exercise permission denied recovery checkpoint 15',
      input: 'notifications:fixture:8:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_15',
    },
    {
      id: '08-notifications-permission-denied-step-16',
      action: 'Exercise permission denied recovery checkpoint 16',
      input: 'notifications:fixture:8:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_16',
    },
    {
      id: '08-notifications-permission-denied-step-17',
      action: 'Exercise permission denied recovery checkpoint 17',
      input: 'notifications:fixture:8:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_17',
    },
    {
      id: '08-notifications-permission-denied-step-18',
      action: 'Exercise permission denied recovery checkpoint 18',
      input: 'notifications:fixture:8:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_18',
    },
    {
      id: '08-notifications-permission-denied-step-19',
      action: 'Exercise permission denied recovery checkpoint 19',
      input: 'notifications:fixture:8:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_19',
    },
    {
      id: '08-notifications-permission-denied-step-20',
      action: 'Exercise permission denied recovery checkpoint 20',
      input: 'notifications:fixture:8:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_20',
    },
    {
      id: '08-notifications-permission-denied-step-21',
      action: 'Exercise permission denied recovery checkpoint 21',
      input: 'notifications:fixture:8:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_21',
    },
    {
      id: '08-notifications-permission-denied-step-22',
      action: 'Exercise permission denied recovery checkpoint 22',
      input: 'notifications:fixture:8:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_22',
    },
    {
      id: '08-notifications-permission-denied-step-23',
      action: 'Exercise permission denied recovery checkpoint 23',
      input: 'notifications:fixture:8:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_23',
    },
    {
      id: '08-notifications-permission-denied-step-24',
      action: 'Exercise permission denied recovery checkpoint 24',
      input: 'notifications:fixture:8:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario08NotificationsPermissionDeniedScenarioSummary = {
  id: Scenario08NotificationsPermissionDeniedScenario.id,
  risk: Scenario08NotificationsPermissionDeniedScenario.risk,
  stepCount: Scenario08NotificationsPermissionDeniedScenario.steps.length,
  recoveryStepCount: Scenario08NotificationsPermissionDeniedScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario08NotificationsPermissionDeniedScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario08NotificationsPermissionDeniedScenarioStep(index: number) {
  if (index < 0 || index >= Scenario08NotificationsPermissionDeniedScenario.steps.length) return undefined;
  return Scenario08NotificationsPermissionDeniedScenario.steps[index];
}

export function evaluateScenario08NotificationsPermissionDeniedScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario08NotificationsPermissionDeniedScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario08NotificationsPermissionDeniedScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario08NotificationsPermissionDeniedScenario.steps.length };
}
