import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario09StorageCorruptJsonScenario: ReleaseScenario = {
  id: '09-storage-corrupt-json',
  domain: 'storage',
  title: 'Release QA · Storage · corrupt json',
  risk: 'medium',
  steps: [
    {
      id: '09-storage-corrupt-json-step-01',
      action: 'Exercise corrupt json recovery checkpoint 01',
      input: 'storage:fixture:9:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_storage_checkpoint_01',
    },
    {
      id: '09-storage-corrupt-json-step-02',
      action: 'Exercise corrupt json recovery checkpoint 02',
      input: 'storage:fixture:9:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_storage_checkpoint_02',
    },
    {
      id: '09-storage-corrupt-json-step-03',
      action: 'Exercise corrupt json recovery checkpoint 03',
      input: 'storage:fixture:9:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_storage_checkpoint_03',
    },
    {
      id: '09-storage-corrupt-json-step-04',
      action: 'Exercise corrupt json recovery checkpoint 04',
      input: 'storage:fixture:9:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_storage_checkpoint_04',
    },
    {
      id: '09-storage-corrupt-json-step-05',
      action: 'Exercise corrupt json recovery checkpoint 05',
      input: 'storage:fixture:9:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_storage_checkpoint_05',
    },
    {
      id: '09-storage-corrupt-json-step-06',
      action: 'Exercise corrupt json recovery checkpoint 06',
      input: 'storage:fixture:9:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_storage_checkpoint_06',
    },
    {
      id: '09-storage-corrupt-json-step-07',
      action: 'Exercise corrupt json recovery checkpoint 07',
      input: 'storage:fixture:9:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_storage_checkpoint_07',
    },
    {
      id: '09-storage-corrupt-json-step-08',
      action: 'Exercise corrupt json recovery checkpoint 08',
      input: 'storage:fixture:9:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_storage_checkpoint_08',
    },
    {
      id: '09-storage-corrupt-json-step-09',
      action: 'Exercise corrupt json recovery checkpoint 09',
      input: 'storage:fixture:9:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_storage_checkpoint_09',
    },
    {
      id: '09-storage-corrupt-json-step-10',
      action: 'Exercise corrupt json recovery checkpoint 10',
      input: 'storage:fixture:9:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_storage_checkpoint_10',
    },
    {
      id: '09-storage-corrupt-json-step-11',
      action: 'Exercise corrupt json recovery checkpoint 11',
      input: 'storage:fixture:9:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_storage_checkpoint_11',
    },
    {
      id: '09-storage-corrupt-json-step-12',
      action: 'Exercise corrupt json recovery checkpoint 12',
      input: 'storage:fixture:9:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_storage_checkpoint_12',
    },
    {
      id: '09-storage-corrupt-json-step-13',
      action: 'Exercise corrupt json recovery checkpoint 13',
      input: 'storage:fixture:9:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_storage_checkpoint_13',
    },
    {
      id: '09-storage-corrupt-json-step-14',
      action: 'Exercise corrupt json recovery checkpoint 14',
      input: 'storage:fixture:9:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_storage_checkpoint_14',
    },
    {
      id: '09-storage-corrupt-json-step-15',
      action: 'Exercise corrupt json recovery checkpoint 15',
      input: 'storage:fixture:9:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_storage_checkpoint_15',
    },
    {
      id: '09-storage-corrupt-json-step-16',
      action: 'Exercise corrupt json recovery checkpoint 16',
      input: 'storage:fixture:9:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_storage_checkpoint_16',
    },
    {
      id: '09-storage-corrupt-json-step-17',
      action: 'Exercise corrupt json recovery checkpoint 17',
      input: 'storage:fixture:9:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_storage_checkpoint_17',
    },
    {
      id: '09-storage-corrupt-json-step-18',
      action: 'Exercise corrupt json recovery checkpoint 18',
      input: 'storage:fixture:9:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_storage_checkpoint_18',
    },
    {
      id: '09-storage-corrupt-json-step-19',
      action: 'Exercise corrupt json recovery checkpoint 19',
      input: 'storage:fixture:9:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_storage_checkpoint_19',
    },
    {
      id: '09-storage-corrupt-json-step-20',
      action: 'Exercise corrupt json recovery checkpoint 20',
      input: 'storage:fixture:9:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_storage_checkpoint_20',
    },
    {
      id: '09-storage-corrupt-json-step-21',
      action: 'Exercise corrupt json recovery checkpoint 21',
      input: 'storage:fixture:9:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_storage_checkpoint_21',
    },
    {
      id: '09-storage-corrupt-json-step-22',
      action: 'Exercise corrupt json recovery checkpoint 22',
      input: 'storage:fixture:9:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_storage_checkpoint_22',
    },
    {
      id: '09-storage-corrupt-json-step-23',
      action: 'Exercise corrupt json recovery checkpoint 23',
      input: 'storage:fixture:9:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_storage_checkpoint_23',
    },
    {
      id: '09-storage-corrupt-json-step-24',
      action: 'Exercise corrupt json recovery checkpoint 24',
      input: 'storage:fixture:9:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_storage_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario09StorageCorruptJsonScenarioSummary = {
  id: Scenario09StorageCorruptJsonScenario.id,
  risk: Scenario09StorageCorruptJsonScenario.risk,
  stepCount: Scenario09StorageCorruptJsonScenario.steps.length,
  recoveryStepCount: Scenario09StorageCorruptJsonScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario09StorageCorruptJsonScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario09StorageCorruptJsonScenarioStep(index: number) {
  if (index < 0 || index >= Scenario09StorageCorruptJsonScenario.steps.length) return undefined;
  return Scenario09StorageCorruptJsonScenario.steps[index];
}

export function evaluateScenario09StorageCorruptJsonScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario09StorageCorruptJsonScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario09StorageCorruptJsonScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario09StorageCorruptJsonScenario.steps.length };
}
