import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario10NavigationUnknownRouteScenario: ReleaseScenario = {
  id: '10-navigation-unknown-route',
  domain: 'navigation',
  title: 'Release QA · Navigation · unknown route',
  risk: 'medium',
  steps: [
    {
      id: '10-navigation-unknown-route-step-01',
      action: 'Exercise unknown route recovery checkpoint 01',
      input: 'navigation:fixture:10:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_01',
    },
    {
      id: '10-navigation-unknown-route-step-02',
      action: 'Exercise unknown route recovery checkpoint 02',
      input: 'navigation:fixture:10:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_02',
    },
    {
      id: '10-navigation-unknown-route-step-03',
      action: 'Exercise unknown route recovery checkpoint 03',
      input: 'navigation:fixture:10:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_03',
    },
    {
      id: '10-navigation-unknown-route-step-04',
      action: 'Exercise unknown route recovery checkpoint 04',
      input: 'navigation:fixture:10:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_04',
    },
    {
      id: '10-navigation-unknown-route-step-05',
      action: 'Exercise unknown route recovery checkpoint 05',
      input: 'navigation:fixture:10:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_05',
    },
    {
      id: '10-navigation-unknown-route-step-06',
      action: 'Exercise unknown route recovery checkpoint 06',
      input: 'navigation:fixture:10:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_06',
    },
    {
      id: '10-navigation-unknown-route-step-07',
      action: 'Exercise unknown route recovery checkpoint 07',
      input: 'navigation:fixture:10:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_07',
    },
    {
      id: '10-navigation-unknown-route-step-08',
      action: 'Exercise unknown route recovery checkpoint 08',
      input: 'navigation:fixture:10:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_08',
    },
    {
      id: '10-navigation-unknown-route-step-09',
      action: 'Exercise unknown route recovery checkpoint 09',
      input: 'navigation:fixture:10:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_09',
    },
    {
      id: '10-navigation-unknown-route-step-10',
      action: 'Exercise unknown route recovery checkpoint 10',
      input: 'navigation:fixture:10:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_10',
    },
    {
      id: '10-navigation-unknown-route-step-11',
      action: 'Exercise unknown route recovery checkpoint 11',
      input: 'navigation:fixture:10:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_11',
    },
    {
      id: '10-navigation-unknown-route-step-12',
      action: 'Exercise unknown route recovery checkpoint 12',
      input: 'navigation:fixture:10:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_12',
    },
    {
      id: '10-navigation-unknown-route-step-13',
      action: 'Exercise unknown route recovery checkpoint 13',
      input: 'navigation:fixture:10:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_13',
    },
    {
      id: '10-navigation-unknown-route-step-14',
      action: 'Exercise unknown route recovery checkpoint 14',
      input: 'navigation:fixture:10:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_14',
    },
    {
      id: '10-navigation-unknown-route-step-15',
      action: 'Exercise unknown route recovery checkpoint 15',
      input: 'navigation:fixture:10:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_15',
    },
    {
      id: '10-navigation-unknown-route-step-16',
      action: 'Exercise unknown route recovery checkpoint 16',
      input: 'navigation:fixture:10:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_16',
    },
    {
      id: '10-navigation-unknown-route-step-17',
      action: 'Exercise unknown route recovery checkpoint 17',
      input: 'navigation:fixture:10:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_17',
    },
    {
      id: '10-navigation-unknown-route-step-18',
      action: 'Exercise unknown route recovery checkpoint 18',
      input: 'navigation:fixture:10:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_18',
    },
    {
      id: '10-navigation-unknown-route-step-19',
      action: 'Exercise unknown route recovery checkpoint 19',
      input: 'navigation:fixture:10:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_19',
    },
    {
      id: '10-navigation-unknown-route-step-20',
      action: 'Exercise unknown route recovery checkpoint 20',
      input: 'navigation:fixture:10:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_20',
    },
    {
      id: '10-navigation-unknown-route-step-21',
      action: 'Exercise unknown route recovery checkpoint 21',
      input: 'navigation:fixture:10:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_21',
    },
    {
      id: '10-navigation-unknown-route-step-22',
      action: 'Exercise unknown route recovery checkpoint 22',
      input: 'navigation:fixture:10:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_22',
    },
    {
      id: '10-navigation-unknown-route-step-23',
      action: 'Exercise unknown route recovery checkpoint 23',
      input: 'navigation:fixture:10:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_23',
    },
    {
      id: '10-navigation-unknown-route-step-24',
      action: 'Exercise unknown route recovery checkpoint 24',
      input: 'navigation:fixture:10:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario10NavigationUnknownRouteScenarioSummary = {
  id: Scenario10NavigationUnknownRouteScenario.id,
  risk: Scenario10NavigationUnknownRouteScenario.risk,
  stepCount: Scenario10NavigationUnknownRouteScenario.steps.length,
  recoveryStepCount: Scenario10NavigationUnknownRouteScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario10NavigationUnknownRouteScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario10NavigationUnknownRouteScenarioStep(index: number) {
  if (index < 0 || index >= Scenario10NavigationUnknownRouteScenario.steps.length) return undefined;
  return Scenario10NavigationUnknownRouteScenario.steps[index];
}

export function evaluateScenario10NavigationUnknownRouteScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario10NavigationUnknownRouteScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario10NavigationUnknownRouteScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario10NavigationUnknownRouteScenario.steps.length };
}
