import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario11LifecycleBackgroundDuringUploadScenario: ReleaseScenario = {
  id: '11-lifecycle-background-during-upload',
  domain: 'lifecycle',
  title: 'Release QA · Lifecycle · background during upload',
  risk: 'medium',
  steps: [
    {
      id: '11-lifecycle-background-during-upload-step-01',
      action: 'Exercise background during upload recovery checkpoint 01',
      input: 'lifecycle:fixture:11:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_lifecycle_checkpoint_01',
    },
    {
      id: '11-lifecycle-background-during-upload-step-02',
      action: 'Exercise background during upload recovery checkpoint 02',
      input: 'lifecycle:fixture:11:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_lifecycle_checkpoint_02',
    },
    {
      id: '11-lifecycle-background-during-upload-step-03',
      action: 'Exercise background during upload recovery checkpoint 03',
      input: 'lifecycle:fixture:11:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_lifecycle_checkpoint_03',
    },
    {
      id: '11-lifecycle-background-during-upload-step-04',
      action: 'Exercise background during upload recovery checkpoint 04',
      input: 'lifecycle:fixture:11:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_lifecycle_checkpoint_04',
    },
    {
      id: '11-lifecycle-background-during-upload-step-05',
      action: 'Exercise background during upload recovery checkpoint 05',
      input: 'lifecycle:fixture:11:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_lifecycle_checkpoint_05',
    },
    {
      id: '11-lifecycle-background-during-upload-step-06',
      action: 'Exercise background during upload recovery checkpoint 06',
      input: 'lifecycle:fixture:11:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_lifecycle_checkpoint_06',
    },
    {
      id: '11-lifecycle-background-during-upload-step-07',
      action: 'Exercise background during upload recovery checkpoint 07',
      input: 'lifecycle:fixture:11:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_lifecycle_checkpoint_07',
    },
    {
      id: '11-lifecycle-background-during-upload-step-08',
      action: 'Exercise background during upload recovery checkpoint 08',
      input: 'lifecycle:fixture:11:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_lifecycle_checkpoint_08',
    },
    {
      id: '11-lifecycle-background-during-upload-step-09',
      action: 'Exercise background during upload recovery checkpoint 09',
      input: 'lifecycle:fixture:11:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_lifecycle_checkpoint_09',
    },
    {
      id: '11-lifecycle-background-during-upload-step-10',
      action: 'Exercise background during upload recovery checkpoint 10',
      input: 'lifecycle:fixture:11:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_lifecycle_checkpoint_10',
    },
    {
      id: '11-lifecycle-background-during-upload-step-11',
      action: 'Exercise background during upload recovery checkpoint 11',
      input: 'lifecycle:fixture:11:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_lifecycle_checkpoint_11',
    },
    {
      id: '11-lifecycle-background-during-upload-step-12',
      action: 'Exercise background during upload recovery checkpoint 12',
      input: 'lifecycle:fixture:11:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_lifecycle_checkpoint_12',
    },
    {
      id: '11-lifecycle-background-during-upload-step-13',
      action: 'Exercise background during upload recovery checkpoint 13',
      input: 'lifecycle:fixture:11:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_lifecycle_checkpoint_13',
    },
    {
      id: '11-lifecycle-background-during-upload-step-14',
      action: 'Exercise background during upload recovery checkpoint 14',
      input: 'lifecycle:fixture:11:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_lifecycle_checkpoint_14',
    },
    {
      id: '11-lifecycle-background-during-upload-step-15',
      action: 'Exercise background during upload recovery checkpoint 15',
      input: 'lifecycle:fixture:11:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_lifecycle_checkpoint_15',
    },
    {
      id: '11-lifecycle-background-during-upload-step-16',
      action: 'Exercise background during upload recovery checkpoint 16',
      input: 'lifecycle:fixture:11:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_lifecycle_checkpoint_16',
    },
    {
      id: '11-lifecycle-background-during-upload-step-17',
      action: 'Exercise background during upload recovery checkpoint 17',
      input: 'lifecycle:fixture:11:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_lifecycle_checkpoint_17',
    },
    {
      id: '11-lifecycle-background-during-upload-step-18',
      action: 'Exercise background during upload recovery checkpoint 18',
      input: 'lifecycle:fixture:11:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_lifecycle_checkpoint_18',
    },
    {
      id: '11-lifecycle-background-during-upload-step-19',
      action: 'Exercise background during upload recovery checkpoint 19',
      input: 'lifecycle:fixture:11:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_lifecycle_checkpoint_19',
    },
    {
      id: '11-lifecycle-background-during-upload-step-20',
      action: 'Exercise background during upload recovery checkpoint 20',
      input: 'lifecycle:fixture:11:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_lifecycle_checkpoint_20',
    },
    {
      id: '11-lifecycle-background-during-upload-step-21',
      action: 'Exercise background during upload recovery checkpoint 21',
      input: 'lifecycle:fixture:11:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_lifecycle_checkpoint_21',
    },
    {
      id: '11-lifecycle-background-during-upload-step-22',
      action: 'Exercise background during upload recovery checkpoint 22',
      input: 'lifecycle:fixture:11:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_lifecycle_checkpoint_22',
    },
    {
      id: '11-lifecycle-background-during-upload-step-23',
      action: 'Exercise background during upload recovery checkpoint 23',
      input: 'lifecycle:fixture:11:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_lifecycle_checkpoint_23',
    },
    {
      id: '11-lifecycle-background-during-upload-step-24',
      action: 'Exercise background during upload recovery checkpoint 24',
      input: 'lifecycle:fixture:11:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_lifecycle_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario11LifecycleBackgroundDuringUploadScenarioSummary = {
  id: Scenario11LifecycleBackgroundDuringUploadScenario.id,
  risk: Scenario11LifecycleBackgroundDuringUploadScenario.risk,
  stepCount: Scenario11LifecycleBackgroundDuringUploadScenario.steps.length,
  recoveryStepCount: Scenario11LifecycleBackgroundDuringUploadScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario11LifecycleBackgroundDuringUploadScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario11LifecycleBackgroundDuringUploadScenarioStep(index: number) {
  if (index < 0 || index >= Scenario11LifecycleBackgroundDuringUploadScenario.steps.length) return undefined;
  return Scenario11LifecycleBackgroundDuringUploadScenario.steps[index];
}

export function evaluateScenario11LifecycleBackgroundDuringUploadScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario11LifecycleBackgroundDuringUploadScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario11LifecycleBackgroundDuringUploadScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario11LifecycleBackgroundDuringUploadScenario.steps.length };
}
