import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario13ReleaseMissingBuildNumberScenario: ReleaseScenario = {
  id: '13-release-missing-build-number',
  domain: 'release',
  title: 'Release QA · Release · missing build number',
  risk: 'medium',
  steps: [
    {
      id: '13-release-missing-build-number-step-01',
      action: 'Exercise missing build number recovery checkpoint 01',
      input: 'release:fixture:13:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_01',
    },
    {
      id: '13-release-missing-build-number-step-02',
      action: 'Exercise missing build number recovery checkpoint 02',
      input: 'release:fixture:13:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_02',
    },
    {
      id: '13-release-missing-build-number-step-03',
      action: 'Exercise missing build number recovery checkpoint 03',
      input: 'release:fixture:13:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_03',
    },
    {
      id: '13-release-missing-build-number-step-04',
      action: 'Exercise missing build number recovery checkpoint 04',
      input: 'release:fixture:13:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_04',
    },
    {
      id: '13-release-missing-build-number-step-05',
      action: 'Exercise missing build number recovery checkpoint 05',
      input: 'release:fixture:13:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_05',
    },
    {
      id: '13-release-missing-build-number-step-06',
      action: 'Exercise missing build number recovery checkpoint 06',
      input: 'release:fixture:13:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_06',
    },
    {
      id: '13-release-missing-build-number-step-07',
      action: 'Exercise missing build number recovery checkpoint 07',
      input: 'release:fixture:13:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_07',
    },
    {
      id: '13-release-missing-build-number-step-08',
      action: 'Exercise missing build number recovery checkpoint 08',
      input: 'release:fixture:13:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_08',
    },
    {
      id: '13-release-missing-build-number-step-09',
      action: 'Exercise missing build number recovery checkpoint 09',
      input: 'release:fixture:13:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_09',
    },
    {
      id: '13-release-missing-build-number-step-10',
      action: 'Exercise missing build number recovery checkpoint 10',
      input: 'release:fixture:13:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_10',
    },
    {
      id: '13-release-missing-build-number-step-11',
      action: 'Exercise missing build number recovery checkpoint 11',
      input: 'release:fixture:13:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_11',
    },
    {
      id: '13-release-missing-build-number-step-12',
      action: 'Exercise missing build number recovery checkpoint 12',
      input: 'release:fixture:13:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_12',
    },
    {
      id: '13-release-missing-build-number-step-13',
      action: 'Exercise missing build number recovery checkpoint 13',
      input: 'release:fixture:13:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_13',
    },
    {
      id: '13-release-missing-build-number-step-14',
      action: 'Exercise missing build number recovery checkpoint 14',
      input: 'release:fixture:13:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_14',
    },
    {
      id: '13-release-missing-build-number-step-15',
      action: 'Exercise missing build number recovery checkpoint 15',
      input: 'release:fixture:13:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_15',
    },
    {
      id: '13-release-missing-build-number-step-16',
      action: 'Exercise missing build number recovery checkpoint 16',
      input: 'release:fixture:13:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_16',
    },
    {
      id: '13-release-missing-build-number-step-17',
      action: 'Exercise missing build number recovery checkpoint 17',
      input: 'release:fixture:13:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_17',
    },
    {
      id: '13-release-missing-build-number-step-18',
      action: 'Exercise missing build number recovery checkpoint 18',
      input: 'release:fixture:13:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_18',
    },
    {
      id: '13-release-missing-build-number-step-19',
      action: 'Exercise missing build number recovery checkpoint 19',
      input: 'release:fixture:13:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_19',
    },
    {
      id: '13-release-missing-build-number-step-20',
      action: 'Exercise missing build number recovery checkpoint 20',
      input: 'release:fixture:13:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_20',
    },
    {
      id: '13-release-missing-build-number-step-21',
      action: 'Exercise missing build number recovery checkpoint 21',
      input: 'release:fixture:13:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_21',
    },
    {
      id: '13-release-missing-build-number-step-22',
      action: 'Exercise missing build number recovery checkpoint 22',
      input: 'release:fixture:13:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_22',
    },
    {
      id: '13-release-missing-build-number-step-23',
      action: 'Exercise missing build number recovery checkpoint 23',
      input: 'release:fixture:13:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_23',
    },
    {
      id: '13-release-missing-build-number-step-24',
      action: 'Exercise missing build number recovery checkpoint 24',
      input: 'release:fixture:13:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario13ReleaseMissingBuildNumberScenarioSummary = {
  id: Scenario13ReleaseMissingBuildNumberScenario.id,
  risk: Scenario13ReleaseMissingBuildNumberScenario.risk,
  stepCount: Scenario13ReleaseMissingBuildNumberScenario.steps.length,
  recoveryStepCount: Scenario13ReleaseMissingBuildNumberScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario13ReleaseMissingBuildNumberScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario13ReleaseMissingBuildNumberScenarioStep(index: number) {
  if (index < 0 || index >= Scenario13ReleaseMissingBuildNumberScenario.steps.length) return undefined;
  return Scenario13ReleaseMissingBuildNumberScenario.steps[index];
}

export function evaluateScenario13ReleaseMissingBuildNumberScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario13ReleaseMissingBuildNumberScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario13ReleaseMissingBuildNumberScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario13ReleaseMissingBuildNumberScenario.steps.length };
}
