import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario14AccessibilityLargeTextScenario: ReleaseScenario = {
  id: '14-accessibility-large-text',
  domain: 'accessibility',
  title: 'Release QA · Accessibility · large text',
  risk: 'medium',
  steps: [
    {
      id: '14-accessibility-large-text-step-01',
      action: 'Exercise large text recovery checkpoint 01',
      input: 'accessibility:fixture:14:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_01',
    },
    {
      id: '14-accessibility-large-text-step-02',
      action: 'Exercise large text recovery checkpoint 02',
      input: 'accessibility:fixture:14:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_02',
    },
    {
      id: '14-accessibility-large-text-step-03',
      action: 'Exercise large text recovery checkpoint 03',
      input: 'accessibility:fixture:14:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_03',
    },
    {
      id: '14-accessibility-large-text-step-04',
      action: 'Exercise large text recovery checkpoint 04',
      input: 'accessibility:fixture:14:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_04',
    },
    {
      id: '14-accessibility-large-text-step-05',
      action: 'Exercise large text recovery checkpoint 05',
      input: 'accessibility:fixture:14:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_05',
    },
    {
      id: '14-accessibility-large-text-step-06',
      action: 'Exercise large text recovery checkpoint 06',
      input: 'accessibility:fixture:14:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_06',
    },
    {
      id: '14-accessibility-large-text-step-07',
      action: 'Exercise large text recovery checkpoint 07',
      input: 'accessibility:fixture:14:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_07',
    },
    {
      id: '14-accessibility-large-text-step-08',
      action: 'Exercise large text recovery checkpoint 08',
      input: 'accessibility:fixture:14:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_08',
    },
    {
      id: '14-accessibility-large-text-step-09',
      action: 'Exercise large text recovery checkpoint 09',
      input: 'accessibility:fixture:14:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_09',
    },
    {
      id: '14-accessibility-large-text-step-10',
      action: 'Exercise large text recovery checkpoint 10',
      input: 'accessibility:fixture:14:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_10',
    },
    {
      id: '14-accessibility-large-text-step-11',
      action: 'Exercise large text recovery checkpoint 11',
      input: 'accessibility:fixture:14:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_11',
    },
    {
      id: '14-accessibility-large-text-step-12',
      action: 'Exercise large text recovery checkpoint 12',
      input: 'accessibility:fixture:14:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_12',
    },
    {
      id: '14-accessibility-large-text-step-13',
      action: 'Exercise large text recovery checkpoint 13',
      input: 'accessibility:fixture:14:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_13',
    },
    {
      id: '14-accessibility-large-text-step-14',
      action: 'Exercise large text recovery checkpoint 14',
      input: 'accessibility:fixture:14:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_14',
    },
    {
      id: '14-accessibility-large-text-step-15',
      action: 'Exercise large text recovery checkpoint 15',
      input: 'accessibility:fixture:14:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_15',
    },
    {
      id: '14-accessibility-large-text-step-16',
      action: 'Exercise large text recovery checkpoint 16',
      input: 'accessibility:fixture:14:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_16',
    },
    {
      id: '14-accessibility-large-text-step-17',
      action: 'Exercise large text recovery checkpoint 17',
      input: 'accessibility:fixture:14:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_17',
    },
    {
      id: '14-accessibility-large-text-step-18',
      action: 'Exercise large text recovery checkpoint 18',
      input: 'accessibility:fixture:14:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_18',
    },
    {
      id: '14-accessibility-large-text-step-19',
      action: 'Exercise large text recovery checkpoint 19',
      input: 'accessibility:fixture:14:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_19',
    },
    {
      id: '14-accessibility-large-text-step-20',
      action: 'Exercise large text recovery checkpoint 20',
      input: 'accessibility:fixture:14:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_20',
    },
    {
      id: '14-accessibility-large-text-step-21',
      action: 'Exercise large text recovery checkpoint 21',
      input: 'accessibility:fixture:14:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_21',
    },
    {
      id: '14-accessibility-large-text-step-22',
      action: 'Exercise large text recovery checkpoint 22',
      input: 'accessibility:fixture:14:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_22',
    },
    {
      id: '14-accessibility-large-text-step-23',
      action: 'Exercise large text recovery checkpoint 23',
      input: 'accessibility:fixture:14:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_23',
    },
    {
      id: '14-accessibility-large-text-step-24',
      action: 'Exercise large text recovery checkpoint 24',
      input: 'accessibility:fixture:14:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario14AccessibilityLargeTextScenarioSummary = {
  id: Scenario14AccessibilityLargeTextScenario.id,
  risk: Scenario14AccessibilityLargeTextScenario.risk,
  stepCount: Scenario14AccessibilityLargeTextScenario.steps.length,
  recoveryStepCount: Scenario14AccessibilityLargeTextScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario14AccessibilityLargeTextScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario14AccessibilityLargeTextScenarioStep(index: number) {
  if (index < 0 || index >= Scenario14AccessibilityLargeTextScenario.steps.length) return undefined;
  return Scenario14AccessibilityLargeTextScenario.steps[index];
}

export function evaluateScenario14AccessibilityLargeTextScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario14AccessibilityLargeTextScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario14AccessibilityLargeTextScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario14AccessibilityLargeTextScenario.steps.length };
}
