import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario15PerformanceSlowListScenario: ReleaseScenario = {
  id: '15-performance-slow-list',
  domain: 'performance',
  title: 'Release QA · Performance · slow list',
  risk: 'medium',
  steps: [
    {
      id: '15-performance-slow-list-step-01',
      action: 'Exercise slow list recovery checkpoint 01',
      input: 'performance:fixture:15:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_performance_checkpoint_01',
    },
    {
      id: '15-performance-slow-list-step-02',
      action: 'Exercise slow list recovery checkpoint 02',
      input: 'performance:fixture:15:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_performance_checkpoint_02',
    },
    {
      id: '15-performance-slow-list-step-03',
      action: 'Exercise slow list recovery checkpoint 03',
      input: 'performance:fixture:15:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_performance_checkpoint_03',
    },
    {
      id: '15-performance-slow-list-step-04',
      action: 'Exercise slow list recovery checkpoint 04',
      input: 'performance:fixture:15:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_performance_checkpoint_04',
    },
    {
      id: '15-performance-slow-list-step-05',
      action: 'Exercise slow list recovery checkpoint 05',
      input: 'performance:fixture:15:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_performance_checkpoint_05',
    },
    {
      id: '15-performance-slow-list-step-06',
      action: 'Exercise slow list recovery checkpoint 06',
      input: 'performance:fixture:15:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_performance_checkpoint_06',
    },
    {
      id: '15-performance-slow-list-step-07',
      action: 'Exercise slow list recovery checkpoint 07',
      input: 'performance:fixture:15:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_performance_checkpoint_07',
    },
    {
      id: '15-performance-slow-list-step-08',
      action: 'Exercise slow list recovery checkpoint 08',
      input: 'performance:fixture:15:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_performance_checkpoint_08',
    },
    {
      id: '15-performance-slow-list-step-09',
      action: 'Exercise slow list recovery checkpoint 09',
      input: 'performance:fixture:15:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_performance_checkpoint_09',
    },
    {
      id: '15-performance-slow-list-step-10',
      action: 'Exercise slow list recovery checkpoint 10',
      input: 'performance:fixture:15:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_performance_checkpoint_10',
    },
    {
      id: '15-performance-slow-list-step-11',
      action: 'Exercise slow list recovery checkpoint 11',
      input: 'performance:fixture:15:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_performance_checkpoint_11',
    },
    {
      id: '15-performance-slow-list-step-12',
      action: 'Exercise slow list recovery checkpoint 12',
      input: 'performance:fixture:15:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_performance_checkpoint_12',
    },
    {
      id: '15-performance-slow-list-step-13',
      action: 'Exercise slow list recovery checkpoint 13',
      input: 'performance:fixture:15:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_performance_checkpoint_13',
    },
    {
      id: '15-performance-slow-list-step-14',
      action: 'Exercise slow list recovery checkpoint 14',
      input: 'performance:fixture:15:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_performance_checkpoint_14',
    },
    {
      id: '15-performance-slow-list-step-15',
      action: 'Exercise slow list recovery checkpoint 15',
      input: 'performance:fixture:15:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_performance_checkpoint_15',
    },
    {
      id: '15-performance-slow-list-step-16',
      action: 'Exercise slow list recovery checkpoint 16',
      input: 'performance:fixture:15:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_performance_checkpoint_16',
    },
    {
      id: '15-performance-slow-list-step-17',
      action: 'Exercise slow list recovery checkpoint 17',
      input: 'performance:fixture:15:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_performance_checkpoint_17',
    },
    {
      id: '15-performance-slow-list-step-18',
      action: 'Exercise slow list recovery checkpoint 18',
      input: 'performance:fixture:15:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_performance_checkpoint_18',
    },
    {
      id: '15-performance-slow-list-step-19',
      action: 'Exercise slow list recovery checkpoint 19',
      input: 'performance:fixture:15:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_performance_checkpoint_19',
    },
    {
      id: '15-performance-slow-list-step-20',
      action: 'Exercise slow list recovery checkpoint 20',
      input: 'performance:fixture:15:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_performance_checkpoint_20',
    },
    {
      id: '15-performance-slow-list-step-21',
      action: 'Exercise slow list recovery checkpoint 21',
      input: 'performance:fixture:15:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_performance_checkpoint_21',
    },
    {
      id: '15-performance-slow-list-step-22',
      action: 'Exercise slow list recovery checkpoint 22',
      input: 'performance:fixture:15:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_performance_checkpoint_22',
    },
    {
      id: '15-performance-slow-list-step-23',
      action: 'Exercise slow list recovery checkpoint 23',
      input: 'performance:fixture:15:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_performance_checkpoint_23',
    },
    {
      id: '15-performance-slow-list-step-24',
      action: 'Exercise slow list recovery checkpoint 24',
      input: 'performance:fixture:15:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_performance_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario15PerformanceSlowListScenarioSummary = {
  id: Scenario15PerformanceSlowListScenario.id,
  risk: Scenario15PerformanceSlowListScenario.risk,
  stepCount: Scenario15PerformanceSlowListScenario.steps.length,
  recoveryStepCount: Scenario15PerformanceSlowListScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario15PerformanceSlowListScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario15PerformanceSlowListScenarioStep(index: number) {
  if (index < 0 || index >= Scenario15PerformanceSlowListScenario.steps.length) return undefined;
  return Scenario15PerformanceSlowListScenario.steps[index];
}

export function evaluateScenario15PerformanceSlowListScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario15PerformanceSlowListScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario15PerformanceSlowListScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario15PerformanceSlowListScenario.steps.length };
}
