import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario17AnalysisDuplicateSubmitScenario: ReleaseScenario = {
  id: '17-analysis-duplicate-submit',
  domain: 'analysis',
  title: 'Release QA · Analysis · duplicate submit',
  risk: 'high',
  steps: [
    {
      id: '17-analysis-duplicate-submit-step-01',
      action: 'Exercise duplicate submit recovery checkpoint 01',
      input: 'analysis:fixture:17:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_analysis_checkpoint_01',
    },
    {
      id: '17-analysis-duplicate-submit-step-02',
      action: 'Exercise duplicate submit recovery checkpoint 02',
      input: 'analysis:fixture:17:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_analysis_checkpoint_02',
    },
    {
      id: '17-analysis-duplicate-submit-step-03',
      action: 'Exercise duplicate submit recovery checkpoint 03',
      input: 'analysis:fixture:17:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_analysis_checkpoint_03',
    },
    {
      id: '17-analysis-duplicate-submit-step-04',
      action: 'Exercise duplicate submit recovery checkpoint 04',
      input: 'analysis:fixture:17:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_analysis_checkpoint_04',
    },
    {
      id: '17-analysis-duplicate-submit-step-05',
      action: 'Exercise duplicate submit recovery checkpoint 05',
      input: 'analysis:fixture:17:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_analysis_checkpoint_05',
    },
    {
      id: '17-analysis-duplicate-submit-step-06',
      action: 'Exercise duplicate submit recovery checkpoint 06',
      input: 'analysis:fixture:17:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_analysis_checkpoint_06',
    },
    {
      id: '17-analysis-duplicate-submit-step-07',
      action: 'Exercise duplicate submit recovery checkpoint 07',
      input: 'analysis:fixture:17:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_analysis_checkpoint_07',
    },
    {
      id: '17-analysis-duplicate-submit-step-08',
      action: 'Exercise duplicate submit recovery checkpoint 08',
      input: 'analysis:fixture:17:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_analysis_checkpoint_08',
    },
    {
      id: '17-analysis-duplicate-submit-step-09',
      action: 'Exercise duplicate submit recovery checkpoint 09',
      input: 'analysis:fixture:17:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_analysis_checkpoint_09',
    },
    {
      id: '17-analysis-duplicate-submit-step-10',
      action: 'Exercise duplicate submit recovery checkpoint 10',
      input: 'analysis:fixture:17:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_analysis_checkpoint_10',
    },
    {
      id: '17-analysis-duplicate-submit-step-11',
      action: 'Exercise duplicate submit recovery checkpoint 11',
      input: 'analysis:fixture:17:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_analysis_checkpoint_11',
    },
    {
      id: '17-analysis-duplicate-submit-step-12',
      action: 'Exercise duplicate submit recovery checkpoint 12',
      input: 'analysis:fixture:17:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_analysis_checkpoint_12',
    },
    {
      id: '17-analysis-duplicate-submit-step-13',
      action: 'Exercise duplicate submit recovery checkpoint 13',
      input: 'analysis:fixture:17:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_analysis_checkpoint_13',
    },
    {
      id: '17-analysis-duplicate-submit-step-14',
      action: 'Exercise duplicate submit recovery checkpoint 14',
      input: 'analysis:fixture:17:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_analysis_checkpoint_14',
    },
    {
      id: '17-analysis-duplicate-submit-step-15',
      action: 'Exercise duplicate submit recovery checkpoint 15',
      input: 'analysis:fixture:17:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_analysis_checkpoint_15',
    },
    {
      id: '17-analysis-duplicate-submit-step-16',
      action: 'Exercise duplicate submit recovery checkpoint 16',
      input: 'analysis:fixture:17:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_analysis_checkpoint_16',
    },
    {
      id: '17-analysis-duplicate-submit-step-17',
      action: 'Exercise duplicate submit recovery checkpoint 17',
      input: 'analysis:fixture:17:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_analysis_checkpoint_17',
    },
    {
      id: '17-analysis-duplicate-submit-step-18',
      action: 'Exercise duplicate submit recovery checkpoint 18',
      input: 'analysis:fixture:17:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_analysis_checkpoint_18',
    },
    {
      id: '17-analysis-duplicate-submit-step-19',
      action: 'Exercise duplicate submit recovery checkpoint 19',
      input: 'analysis:fixture:17:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_analysis_checkpoint_19',
    },
    {
      id: '17-analysis-duplicate-submit-step-20',
      action: 'Exercise duplicate submit recovery checkpoint 20',
      input: 'analysis:fixture:17:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_analysis_checkpoint_20',
    },
    {
      id: '17-analysis-duplicate-submit-step-21',
      action: 'Exercise duplicate submit recovery checkpoint 21',
      input: 'analysis:fixture:17:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_analysis_checkpoint_21',
    },
    {
      id: '17-analysis-duplicate-submit-step-22',
      action: 'Exercise duplicate submit recovery checkpoint 22',
      input: 'analysis:fixture:17:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_analysis_checkpoint_22',
    },
    {
      id: '17-analysis-duplicate-submit-step-23',
      action: 'Exercise duplicate submit recovery checkpoint 23',
      input: 'analysis:fixture:17:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_analysis_checkpoint_23',
    },
    {
      id: '17-analysis-duplicate-submit-step-24',
      action: 'Exercise duplicate submit recovery checkpoint 24',
      input: 'analysis:fixture:17:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_analysis_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario17AnalysisDuplicateSubmitScenarioSummary = {
  id: Scenario17AnalysisDuplicateSubmitScenario.id,
  risk: Scenario17AnalysisDuplicateSubmitScenario.risk,
  stepCount: Scenario17AnalysisDuplicateSubmitScenario.steps.length,
  recoveryStepCount: Scenario17AnalysisDuplicateSubmitScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario17AnalysisDuplicateSubmitScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario17AnalysisDuplicateSubmitScenarioStep(index: number) {
  if (index < 0 || index >= Scenario17AnalysisDuplicateSubmitScenario.steps.length) return undefined;
  return Scenario17AnalysisDuplicateSubmitScenario.steps[index];
}

export function evaluateScenario17AnalysisDuplicateSubmitScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario17AnalysisDuplicateSubmitScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario17AnalysisDuplicateSubmitScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario17AnalysisDuplicateSubmitScenario.steps.length };
}
