import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario18NetworkSlowResponseScenario: ReleaseScenario = {
  id: '18-network-slow-response',
  domain: 'network',
  title: 'Release QA · Network · slow response',
  risk: 'high',
  steps: [
    {
      id: '18-network-slow-response-step-01',
      action: 'Exercise slow response recovery checkpoint 01',
      input: 'network:fixture:18:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_network_checkpoint_01',
    },
    {
      id: '18-network-slow-response-step-02',
      action: 'Exercise slow response recovery checkpoint 02',
      input: 'network:fixture:18:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_network_checkpoint_02',
    },
    {
      id: '18-network-slow-response-step-03',
      action: 'Exercise slow response recovery checkpoint 03',
      input: 'network:fixture:18:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_network_checkpoint_03',
    },
    {
      id: '18-network-slow-response-step-04',
      action: 'Exercise slow response recovery checkpoint 04',
      input: 'network:fixture:18:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_network_checkpoint_04',
    },
    {
      id: '18-network-slow-response-step-05',
      action: 'Exercise slow response recovery checkpoint 05',
      input: 'network:fixture:18:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_network_checkpoint_05',
    },
    {
      id: '18-network-slow-response-step-06',
      action: 'Exercise slow response recovery checkpoint 06',
      input: 'network:fixture:18:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_network_checkpoint_06',
    },
    {
      id: '18-network-slow-response-step-07',
      action: 'Exercise slow response recovery checkpoint 07',
      input: 'network:fixture:18:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_network_checkpoint_07',
    },
    {
      id: '18-network-slow-response-step-08',
      action: 'Exercise slow response recovery checkpoint 08',
      input: 'network:fixture:18:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_network_checkpoint_08',
    },
    {
      id: '18-network-slow-response-step-09',
      action: 'Exercise slow response recovery checkpoint 09',
      input: 'network:fixture:18:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_network_checkpoint_09',
    },
    {
      id: '18-network-slow-response-step-10',
      action: 'Exercise slow response recovery checkpoint 10',
      input: 'network:fixture:18:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_network_checkpoint_10',
    },
    {
      id: '18-network-slow-response-step-11',
      action: 'Exercise slow response recovery checkpoint 11',
      input: 'network:fixture:18:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_network_checkpoint_11',
    },
    {
      id: '18-network-slow-response-step-12',
      action: 'Exercise slow response recovery checkpoint 12',
      input: 'network:fixture:18:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_network_checkpoint_12',
    },
    {
      id: '18-network-slow-response-step-13',
      action: 'Exercise slow response recovery checkpoint 13',
      input: 'network:fixture:18:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_network_checkpoint_13',
    },
    {
      id: '18-network-slow-response-step-14',
      action: 'Exercise slow response recovery checkpoint 14',
      input: 'network:fixture:18:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_network_checkpoint_14',
    },
    {
      id: '18-network-slow-response-step-15',
      action: 'Exercise slow response recovery checkpoint 15',
      input: 'network:fixture:18:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_network_checkpoint_15',
    },
    {
      id: '18-network-slow-response-step-16',
      action: 'Exercise slow response recovery checkpoint 16',
      input: 'network:fixture:18:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_network_checkpoint_16',
    },
    {
      id: '18-network-slow-response-step-17',
      action: 'Exercise slow response recovery checkpoint 17',
      input: 'network:fixture:18:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_network_checkpoint_17',
    },
    {
      id: '18-network-slow-response-step-18',
      action: 'Exercise slow response recovery checkpoint 18',
      input: 'network:fixture:18:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_network_checkpoint_18',
    },
    {
      id: '18-network-slow-response-step-19',
      action: 'Exercise slow response recovery checkpoint 19',
      input: 'network:fixture:18:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_network_checkpoint_19',
    },
    {
      id: '18-network-slow-response-step-20',
      action: 'Exercise slow response recovery checkpoint 20',
      input: 'network:fixture:18:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_network_checkpoint_20',
    },
    {
      id: '18-network-slow-response-step-21',
      action: 'Exercise slow response recovery checkpoint 21',
      input: 'network:fixture:18:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_network_checkpoint_21',
    },
    {
      id: '18-network-slow-response-step-22',
      action: 'Exercise slow response recovery checkpoint 22',
      input: 'network:fixture:18:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_network_checkpoint_22',
    },
    {
      id: '18-network-slow-response-step-23',
      action: 'Exercise slow response recovery checkpoint 23',
      input: 'network:fixture:18:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_network_checkpoint_23',
    },
    {
      id: '18-network-slow-response-step-24',
      action: 'Exercise slow response recovery checkpoint 24',
      input: 'network:fixture:18:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_network_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario18NetworkSlowResponseScenarioSummary = {
  id: Scenario18NetworkSlowResponseScenario.id,
  risk: Scenario18NetworkSlowResponseScenario.risk,
  stepCount: Scenario18NetworkSlowResponseScenario.steps.length,
  recoveryStepCount: Scenario18NetworkSlowResponseScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario18NetworkSlowResponseScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario18NetworkSlowResponseScenarioStep(index: number) {
  if (index < 0 || index >= Scenario18NetworkSlowResponseScenario.steps.length) return undefined;
  return Scenario18NetworkSlowResponseScenario.steps[index];
}

export function evaluateScenario18NetworkSlowResponseScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario18NetworkSlowResponseScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario18NetworkSlowResponseScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario18NetworkSlowResponseScenario.steps.length };
}
