import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario19MediaOversizedVideoScenario: ReleaseScenario = {
  id: '19-media-oversized-video',
  domain: 'media',
  title: 'Release QA · Media · oversized video',
  risk: 'high',
  steps: [
    {
      id: '19-media-oversized-video-step-01',
      action: 'Exercise oversized video recovery checkpoint 01',
      input: 'media:fixture:19:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_01',
    },
    {
      id: '19-media-oversized-video-step-02',
      action: 'Exercise oversized video recovery checkpoint 02',
      input: 'media:fixture:19:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_02',
    },
    {
      id: '19-media-oversized-video-step-03',
      action: 'Exercise oversized video recovery checkpoint 03',
      input: 'media:fixture:19:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_03',
    },
    {
      id: '19-media-oversized-video-step-04',
      action: 'Exercise oversized video recovery checkpoint 04',
      input: 'media:fixture:19:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_04',
    },
    {
      id: '19-media-oversized-video-step-05',
      action: 'Exercise oversized video recovery checkpoint 05',
      input: 'media:fixture:19:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_05',
    },
    {
      id: '19-media-oversized-video-step-06',
      action: 'Exercise oversized video recovery checkpoint 06',
      input: 'media:fixture:19:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_06',
    },
    {
      id: '19-media-oversized-video-step-07',
      action: 'Exercise oversized video recovery checkpoint 07',
      input: 'media:fixture:19:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_07',
    },
    {
      id: '19-media-oversized-video-step-08',
      action: 'Exercise oversized video recovery checkpoint 08',
      input: 'media:fixture:19:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_08',
    },
    {
      id: '19-media-oversized-video-step-09',
      action: 'Exercise oversized video recovery checkpoint 09',
      input: 'media:fixture:19:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_09',
    },
    {
      id: '19-media-oversized-video-step-10',
      action: 'Exercise oversized video recovery checkpoint 10',
      input: 'media:fixture:19:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_10',
    },
    {
      id: '19-media-oversized-video-step-11',
      action: 'Exercise oversized video recovery checkpoint 11',
      input: 'media:fixture:19:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_11',
    },
    {
      id: '19-media-oversized-video-step-12',
      action: 'Exercise oversized video recovery checkpoint 12',
      input: 'media:fixture:19:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_12',
    },
    {
      id: '19-media-oversized-video-step-13',
      action: 'Exercise oversized video recovery checkpoint 13',
      input: 'media:fixture:19:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_13',
    },
    {
      id: '19-media-oversized-video-step-14',
      action: 'Exercise oversized video recovery checkpoint 14',
      input: 'media:fixture:19:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_14',
    },
    {
      id: '19-media-oversized-video-step-15',
      action: 'Exercise oversized video recovery checkpoint 15',
      input: 'media:fixture:19:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_15',
    },
    {
      id: '19-media-oversized-video-step-16',
      action: 'Exercise oversized video recovery checkpoint 16',
      input: 'media:fixture:19:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_16',
    },
    {
      id: '19-media-oversized-video-step-17',
      action: 'Exercise oversized video recovery checkpoint 17',
      input: 'media:fixture:19:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_17',
    },
    {
      id: '19-media-oversized-video-step-18',
      action: 'Exercise oversized video recovery checkpoint 18',
      input: 'media:fixture:19:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_18',
    },
    {
      id: '19-media-oversized-video-step-19',
      action: 'Exercise oversized video recovery checkpoint 19',
      input: 'media:fixture:19:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_19',
    },
    {
      id: '19-media-oversized-video-step-20',
      action: 'Exercise oversized video recovery checkpoint 20',
      input: 'media:fixture:19:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_20',
    },
    {
      id: '19-media-oversized-video-step-21',
      action: 'Exercise oversized video recovery checkpoint 21',
      input: 'media:fixture:19:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_21',
    },
    {
      id: '19-media-oversized-video-step-22',
      action: 'Exercise oversized video recovery checkpoint 22',
      input: 'media:fixture:19:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_22',
    },
    {
      id: '19-media-oversized-video-step-23',
      action: 'Exercise oversized video recovery checkpoint 23',
      input: 'media:fixture:19:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_23',
    },
    {
      id: '19-media-oversized-video-step-24',
      action: 'Exercise oversized video recovery checkpoint 24',
      input: 'media:fixture:19:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario19MediaOversizedVideoScenarioSummary = {
  id: Scenario19MediaOversizedVideoScenario.id,
  risk: Scenario19MediaOversizedVideoScenario.risk,
  stepCount: Scenario19MediaOversizedVideoScenario.steps.length,
  recoveryStepCount: Scenario19MediaOversizedVideoScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario19MediaOversizedVideoScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario19MediaOversizedVideoScenarioStep(index: number) {
  if (index < 0 || index >= Scenario19MediaOversizedVideoScenario.steps.length) return undefined;
  return Scenario19MediaOversizedVideoScenario.steps[index];
}

export function evaluateScenario19MediaOversizedVideoScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario19MediaOversizedVideoScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario19MediaOversizedVideoScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario19MediaOversizedVideoScenario.steps.length };
}
