import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario20AuthMissingSessionScenario: ReleaseScenario = {
  id: '20-auth-missing-session',
  domain: 'auth',
  title: 'Release QA · Auth · missing session',
  risk: 'critical',
  steps: [
    {
      id: '20-auth-missing-session-step-01',
      action: 'Exercise missing session recovery checkpoint 01',
      input: 'auth:fixture:20:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_auth_checkpoint_01',
    },
    {
      id: '20-auth-missing-session-step-02',
      action: 'Exercise missing session recovery checkpoint 02',
      input: 'auth:fixture:20:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_auth_checkpoint_02',
    },
    {
      id: '20-auth-missing-session-step-03',
      action: 'Exercise missing session recovery checkpoint 03',
      input: 'auth:fixture:20:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_auth_checkpoint_03',
    },
    {
      id: '20-auth-missing-session-step-04',
      action: 'Exercise missing session recovery checkpoint 04',
      input: 'auth:fixture:20:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_auth_checkpoint_04',
    },
    {
      id: '20-auth-missing-session-step-05',
      action: 'Exercise missing session recovery checkpoint 05',
      input: 'auth:fixture:20:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_auth_checkpoint_05',
    },
    {
      id: '20-auth-missing-session-step-06',
      action: 'Exercise missing session recovery checkpoint 06',
      input: 'auth:fixture:20:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_auth_checkpoint_06',
    },
    {
      id: '20-auth-missing-session-step-07',
      action: 'Exercise missing session recovery checkpoint 07',
      input: 'auth:fixture:20:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_auth_checkpoint_07',
    },
    {
      id: '20-auth-missing-session-step-08',
      action: 'Exercise missing session recovery checkpoint 08',
      input: 'auth:fixture:20:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_auth_checkpoint_08',
    },
    {
      id: '20-auth-missing-session-step-09',
      action: 'Exercise missing session recovery checkpoint 09',
      input: 'auth:fixture:20:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_auth_checkpoint_09',
    },
    {
      id: '20-auth-missing-session-step-10',
      action: 'Exercise missing session recovery checkpoint 10',
      input: 'auth:fixture:20:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_auth_checkpoint_10',
    },
    {
      id: '20-auth-missing-session-step-11',
      action: 'Exercise missing session recovery checkpoint 11',
      input: 'auth:fixture:20:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_auth_checkpoint_11',
    },
    {
      id: '20-auth-missing-session-step-12',
      action: 'Exercise missing session recovery checkpoint 12',
      input: 'auth:fixture:20:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_auth_checkpoint_12',
    },
    {
      id: '20-auth-missing-session-step-13',
      action: 'Exercise missing session recovery checkpoint 13',
      input: 'auth:fixture:20:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_auth_checkpoint_13',
    },
    {
      id: '20-auth-missing-session-step-14',
      action: 'Exercise missing session recovery checkpoint 14',
      input: 'auth:fixture:20:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_auth_checkpoint_14',
    },
    {
      id: '20-auth-missing-session-step-15',
      action: 'Exercise missing session recovery checkpoint 15',
      input: 'auth:fixture:20:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_auth_checkpoint_15',
    },
    {
      id: '20-auth-missing-session-step-16',
      action: 'Exercise missing session recovery checkpoint 16',
      input: 'auth:fixture:20:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_auth_checkpoint_16',
    },
    {
      id: '20-auth-missing-session-step-17',
      action: 'Exercise missing session recovery checkpoint 17',
      input: 'auth:fixture:20:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_auth_checkpoint_17',
    },
    {
      id: '20-auth-missing-session-step-18',
      action: 'Exercise missing session recovery checkpoint 18',
      input: 'auth:fixture:20:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_auth_checkpoint_18',
    },
    {
      id: '20-auth-missing-session-step-19',
      action: 'Exercise missing session recovery checkpoint 19',
      input: 'auth:fixture:20:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_auth_checkpoint_19',
    },
    {
      id: '20-auth-missing-session-step-20',
      action: 'Exercise missing session recovery checkpoint 20',
      input: 'auth:fixture:20:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_auth_checkpoint_20',
    },
    {
      id: '20-auth-missing-session-step-21',
      action: 'Exercise missing session recovery checkpoint 21',
      input: 'auth:fixture:20:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_auth_checkpoint_21',
    },
    {
      id: '20-auth-missing-session-step-22',
      action: 'Exercise missing session recovery checkpoint 22',
      input: 'auth:fixture:20:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_auth_checkpoint_22',
    },
    {
      id: '20-auth-missing-session-step-23',
      action: 'Exercise missing session recovery checkpoint 23',
      input: 'auth:fixture:20:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_auth_checkpoint_23',
    },
    {
      id: '20-auth-missing-session-step-24',
      action: 'Exercise missing session recovery checkpoint 24',
      input: 'auth:fixture:20:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_auth_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario20AuthMissingSessionScenarioSummary = {
  id: Scenario20AuthMissingSessionScenario.id,
  risk: Scenario20AuthMissingSessionScenario.risk,
  stepCount: Scenario20AuthMissingSessionScenario.steps.length,
  recoveryStepCount: Scenario20AuthMissingSessionScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario20AuthMissingSessionScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario20AuthMissingSessionScenarioStep(index: number) {
  if (index < 0 || index >= Scenario20AuthMissingSessionScenario.steps.length) return undefined;
  return Scenario20AuthMissingSessionScenario.steps[index];
}

export function evaluateScenario20AuthMissingSessionScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario20AuthMissingSessionScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario20AuthMissingSessionScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario20AuthMissingSessionScenario.steps.length };
}
