import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario21BillingPurchaseCancelledScenario: ReleaseScenario = {
  id: '21-billing-purchase-cancelled',
  domain: 'billing',
  title: 'Release QA · Billing · purchase cancelled',
  risk: 'critical',
  steps: [
    {
      id: '21-billing-purchase-cancelled-step-01',
      action: 'Exercise purchase cancelled recovery checkpoint 01',
      input: 'billing:fixture:21:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_billing_checkpoint_01',
    },
    {
      id: '21-billing-purchase-cancelled-step-02',
      action: 'Exercise purchase cancelled recovery checkpoint 02',
      input: 'billing:fixture:21:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_billing_checkpoint_02',
    },
    {
      id: '21-billing-purchase-cancelled-step-03',
      action: 'Exercise purchase cancelled recovery checkpoint 03',
      input: 'billing:fixture:21:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_billing_checkpoint_03',
    },
    {
      id: '21-billing-purchase-cancelled-step-04',
      action: 'Exercise purchase cancelled recovery checkpoint 04',
      input: 'billing:fixture:21:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_billing_checkpoint_04',
    },
    {
      id: '21-billing-purchase-cancelled-step-05',
      action: 'Exercise purchase cancelled recovery checkpoint 05',
      input: 'billing:fixture:21:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_billing_checkpoint_05',
    },
    {
      id: '21-billing-purchase-cancelled-step-06',
      action: 'Exercise purchase cancelled recovery checkpoint 06',
      input: 'billing:fixture:21:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_billing_checkpoint_06',
    },
    {
      id: '21-billing-purchase-cancelled-step-07',
      action: 'Exercise purchase cancelled recovery checkpoint 07',
      input: 'billing:fixture:21:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_billing_checkpoint_07',
    },
    {
      id: '21-billing-purchase-cancelled-step-08',
      action: 'Exercise purchase cancelled recovery checkpoint 08',
      input: 'billing:fixture:21:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_billing_checkpoint_08',
    },
    {
      id: '21-billing-purchase-cancelled-step-09',
      action: 'Exercise purchase cancelled recovery checkpoint 09',
      input: 'billing:fixture:21:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_billing_checkpoint_09',
    },
    {
      id: '21-billing-purchase-cancelled-step-10',
      action: 'Exercise purchase cancelled recovery checkpoint 10',
      input: 'billing:fixture:21:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_billing_checkpoint_10',
    },
    {
      id: '21-billing-purchase-cancelled-step-11',
      action: 'Exercise purchase cancelled recovery checkpoint 11',
      input: 'billing:fixture:21:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_billing_checkpoint_11',
    },
    {
      id: '21-billing-purchase-cancelled-step-12',
      action: 'Exercise purchase cancelled recovery checkpoint 12',
      input: 'billing:fixture:21:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_billing_checkpoint_12',
    },
    {
      id: '21-billing-purchase-cancelled-step-13',
      action: 'Exercise purchase cancelled recovery checkpoint 13',
      input: 'billing:fixture:21:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_billing_checkpoint_13',
    },
    {
      id: '21-billing-purchase-cancelled-step-14',
      action: 'Exercise purchase cancelled recovery checkpoint 14',
      input: 'billing:fixture:21:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_billing_checkpoint_14',
    },
    {
      id: '21-billing-purchase-cancelled-step-15',
      action: 'Exercise purchase cancelled recovery checkpoint 15',
      input: 'billing:fixture:21:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_billing_checkpoint_15',
    },
    {
      id: '21-billing-purchase-cancelled-step-16',
      action: 'Exercise purchase cancelled recovery checkpoint 16',
      input: 'billing:fixture:21:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_billing_checkpoint_16',
    },
    {
      id: '21-billing-purchase-cancelled-step-17',
      action: 'Exercise purchase cancelled recovery checkpoint 17',
      input: 'billing:fixture:21:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_billing_checkpoint_17',
    },
    {
      id: '21-billing-purchase-cancelled-step-18',
      action: 'Exercise purchase cancelled recovery checkpoint 18',
      input: 'billing:fixture:21:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_billing_checkpoint_18',
    },
    {
      id: '21-billing-purchase-cancelled-step-19',
      action: 'Exercise purchase cancelled recovery checkpoint 19',
      input: 'billing:fixture:21:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_billing_checkpoint_19',
    },
    {
      id: '21-billing-purchase-cancelled-step-20',
      action: 'Exercise purchase cancelled recovery checkpoint 20',
      input: 'billing:fixture:21:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_billing_checkpoint_20',
    },
    {
      id: '21-billing-purchase-cancelled-step-21',
      action: 'Exercise purchase cancelled recovery checkpoint 21',
      input: 'billing:fixture:21:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_billing_checkpoint_21',
    },
    {
      id: '21-billing-purchase-cancelled-step-22',
      action: 'Exercise purchase cancelled recovery checkpoint 22',
      input: 'billing:fixture:21:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_billing_checkpoint_22',
    },
    {
      id: '21-billing-purchase-cancelled-step-23',
      action: 'Exercise purchase cancelled recovery checkpoint 23',
      input: 'billing:fixture:21:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_billing_checkpoint_23',
    },
    {
      id: '21-billing-purchase-cancelled-step-24',
      action: 'Exercise purchase cancelled recovery checkpoint 24',
      input: 'billing:fixture:21:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_billing_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario21BillingPurchaseCancelledScenarioSummary = {
  id: Scenario21BillingPurchaseCancelledScenario.id,
  risk: Scenario21BillingPurchaseCancelledScenario.risk,
  stepCount: Scenario21BillingPurchaseCancelledScenario.steps.length,
  recoveryStepCount: Scenario21BillingPurchaseCancelledScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario21BillingPurchaseCancelledScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario21BillingPurchaseCancelledScenarioStep(index: number) {
  if (index < 0 || index >= Scenario21BillingPurchaseCancelledScenario.steps.length) return undefined;
  return Scenario21BillingPurchaseCancelledScenario.steps[index];
}

export function evaluateScenario21BillingPurchaseCancelledScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario21BillingPurchaseCancelledScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario21BillingPurchaseCancelledScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario21BillingPurchaseCancelledScenario.steps.length };
}
