import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario23NotificationsTokenRefreshScenario: ReleaseScenario = {
  id: '23-notifications-token-refresh',
  domain: 'notifications',
  title: 'Release QA · Notifications · token refresh',
  risk: 'medium',
  steps: [
    {
      id: '23-notifications-token-refresh-step-01',
      action: 'Exercise token refresh recovery checkpoint 01',
      input: 'notifications:fixture:23:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_01',
    },
    {
      id: '23-notifications-token-refresh-step-02',
      action: 'Exercise token refresh recovery checkpoint 02',
      input: 'notifications:fixture:23:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_02',
    },
    {
      id: '23-notifications-token-refresh-step-03',
      action: 'Exercise token refresh recovery checkpoint 03',
      input: 'notifications:fixture:23:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_03',
    },
    {
      id: '23-notifications-token-refresh-step-04',
      action: 'Exercise token refresh recovery checkpoint 04',
      input: 'notifications:fixture:23:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_04',
    },
    {
      id: '23-notifications-token-refresh-step-05',
      action: 'Exercise token refresh recovery checkpoint 05',
      input: 'notifications:fixture:23:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_05',
    },
    {
      id: '23-notifications-token-refresh-step-06',
      action: 'Exercise token refresh recovery checkpoint 06',
      input: 'notifications:fixture:23:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_06',
    },
    {
      id: '23-notifications-token-refresh-step-07',
      action: 'Exercise token refresh recovery checkpoint 07',
      input: 'notifications:fixture:23:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_07',
    },
    {
      id: '23-notifications-token-refresh-step-08',
      action: 'Exercise token refresh recovery checkpoint 08',
      input: 'notifications:fixture:23:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_08',
    },
    {
      id: '23-notifications-token-refresh-step-09',
      action: 'Exercise token refresh recovery checkpoint 09',
      input: 'notifications:fixture:23:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_09',
    },
    {
      id: '23-notifications-token-refresh-step-10',
      action: 'Exercise token refresh recovery checkpoint 10',
      input: 'notifications:fixture:23:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_10',
    },
    {
      id: '23-notifications-token-refresh-step-11',
      action: 'Exercise token refresh recovery checkpoint 11',
      input: 'notifications:fixture:23:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_11',
    },
    {
      id: '23-notifications-token-refresh-step-12',
      action: 'Exercise token refresh recovery checkpoint 12',
      input: 'notifications:fixture:23:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_12',
    },
    {
      id: '23-notifications-token-refresh-step-13',
      action: 'Exercise token refresh recovery checkpoint 13',
      input: 'notifications:fixture:23:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_13',
    },
    {
      id: '23-notifications-token-refresh-step-14',
      action: 'Exercise token refresh recovery checkpoint 14',
      input: 'notifications:fixture:23:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_14',
    },
    {
      id: '23-notifications-token-refresh-step-15',
      action: 'Exercise token refresh recovery checkpoint 15',
      input: 'notifications:fixture:23:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_15',
    },
    {
      id: '23-notifications-token-refresh-step-16',
      action: 'Exercise token refresh recovery checkpoint 16',
      input: 'notifications:fixture:23:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_16',
    },
    {
      id: '23-notifications-token-refresh-step-17',
      action: 'Exercise token refresh recovery checkpoint 17',
      input: 'notifications:fixture:23:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_17',
    },
    {
      id: '23-notifications-token-refresh-step-18',
      action: 'Exercise token refresh recovery checkpoint 18',
      input: 'notifications:fixture:23:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_18',
    },
    {
      id: '23-notifications-token-refresh-step-19',
      action: 'Exercise token refresh recovery checkpoint 19',
      input: 'notifications:fixture:23:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_19',
    },
    {
      id: '23-notifications-token-refresh-step-20',
      action: 'Exercise token refresh recovery checkpoint 20',
      input: 'notifications:fixture:23:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_20',
    },
    {
      id: '23-notifications-token-refresh-step-21',
      action: 'Exercise token refresh recovery checkpoint 21',
      input: 'notifications:fixture:23:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_21',
    },
    {
      id: '23-notifications-token-refresh-step-22',
      action: 'Exercise token refresh recovery checkpoint 22',
      input: 'notifications:fixture:23:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_22',
    },
    {
      id: '23-notifications-token-refresh-step-23',
      action: 'Exercise token refresh recovery checkpoint 23',
      input: 'notifications:fixture:23:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_23',
    },
    {
      id: '23-notifications-token-refresh-step-24',
      action: 'Exercise token refresh recovery checkpoint 24',
      input: 'notifications:fixture:23:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario23NotificationsTokenRefreshScenarioSummary = {
  id: Scenario23NotificationsTokenRefreshScenario.id,
  risk: Scenario23NotificationsTokenRefreshScenario.risk,
  stepCount: Scenario23NotificationsTokenRefreshScenario.steps.length,
  recoveryStepCount: Scenario23NotificationsTokenRefreshScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario23NotificationsTokenRefreshScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario23NotificationsTokenRefreshScenarioStep(index: number) {
  if (index < 0 || index >= Scenario23NotificationsTokenRefreshScenario.steps.length) return undefined;
  return Scenario23NotificationsTokenRefreshScenario.steps[index];
}

export function evaluateScenario23NotificationsTokenRefreshScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario23NotificationsTokenRefreshScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario23NotificationsTokenRefreshScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario23NotificationsTokenRefreshScenario.steps.length };
}
