import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario25NavigationRapidTapsScenario: ReleaseScenario = {
  id: '25-navigation-rapid-taps',
  domain: 'navigation',
  title: 'Release QA · Navigation · rapid taps',
  risk: 'medium',
  steps: [
    {
      id: '25-navigation-rapid-taps-step-01',
      action: 'Exercise rapid taps recovery checkpoint 01',
      input: 'navigation:fixture:25:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_01',
    },
    {
      id: '25-navigation-rapid-taps-step-02',
      action: 'Exercise rapid taps recovery checkpoint 02',
      input: 'navigation:fixture:25:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_02',
    },
    {
      id: '25-navigation-rapid-taps-step-03',
      action: 'Exercise rapid taps recovery checkpoint 03',
      input: 'navigation:fixture:25:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_03',
    },
    {
      id: '25-navigation-rapid-taps-step-04',
      action: 'Exercise rapid taps recovery checkpoint 04',
      input: 'navigation:fixture:25:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_04',
    },
    {
      id: '25-navigation-rapid-taps-step-05',
      action: 'Exercise rapid taps recovery checkpoint 05',
      input: 'navigation:fixture:25:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_05',
    },
    {
      id: '25-navigation-rapid-taps-step-06',
      action: 'Exercise rapid taps recovery checkpoint 06',
      input: 'navigation:fixture:25:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_06',
    },
    {
      id: '25-navigation-rapid-taps-step-07',
      action: 'Exercise rapid taps recovery checkpoint 07',
      input: 'navigation:fixture:25:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_07',
    },
    {
      id: '25-navigation-rapid-taps-step-08',
      action: 'Exercise rapid taps recovery checkpoint 08',
      input: 'navigation:fixture:25:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_08',
    },
    {
      id: '25-navigation-rapid-taps-step-09',
      action: 'Exercise rapid taps recovery checkpoint 09',
      input: 'navigation:fixture:25:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_09',
    },
    {
      id: '25-navigation-rapid-taps-step-10',
      action: 'Exercise rapid taps recovery checkpoint 10',
      input: 'navigation:fixture:25:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_10',
    },
    {
      id: '25-navigation-rapid-taps-step-11',
      action: 'Exercise rapid taps recovery checkpoint 11',
      input: 'navigation:fixture:25:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_11',
    },
    {
      id: '25-navigation-rapid-taps-step-12',
      action: 'Exercise rapid taps recovery checkpoint 12',
      input: 'navigation:fixture:25:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_12',
    },
    {
      id: '25-navigation-rapid-taps-step-13',
      action: 'Exercise rapid taps recovery checkpoint 13',
      input: 'navigation:fixture:25:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_13',
    },
    {
      id: '25-navigation-rapid-taps-step-14',
      action: 'Exercise rapid taps recovery checkpoint 14',
      input: 'navigation:fixture:25:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_14',
    },
    {
      id: '25-navigation-rapid-taps-step-15',
      action: 'Exercise rapid taps recovery checkpoint 15',
      input: 'navigation:fixture:25:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_15',
    },
    {
      id: '25-navigation-rapid-taps-step-16',
      action: 'Exercise rapid taps recovery checkpoint 16',
      input: 'navigation:fixture:25:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_16',
    },
    {
      id: '25-navigation-rapid-taps-step-17',
      action: 'Exercise rapid taps recovery checkpoint 17',
      input: 'navigation:fixture:25:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_17',
    },
    {
      id: '25-navigation-rapid-taps-step-18',
      action: 'Exercise rapid taps recovery checkpoint 18',
      input: 'navigation:fixture:25:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_18',
    },
    {
      id: '25-navigation-rapid-taps-step-19',
      action: 'Exercise rapid taps recovery checkpoint 19',
      input: 'navigation:fixture:25:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_19',
    },
    {
      id: '25-navigation-rapid-taps-step-20',
      action: 'Exercise rapid taps recovery checkpoint 20',
      input: 'navigation:fixture:25:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_20',
    },
    {
      id: '25-navigation-rapid-taps-step-21',
      action: 'Exercise rapid taps recovery checkpoint 21',
      input: 'navigation:fixture:25:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_21',
    },
    {
      id: '25-navigation-rapid-taps-step-22',
      action: 'Exercise rapid taps recovery checkpoint 22',
      input: 'navigation:fixture:25:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_22',
    },
    {
      id: '25-navigation-rapid-taps-step-23',
      action: 'Exercise rapid taps recovery checkpoint 23',
      input: 'navigation:fixture:25:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_23',
    },
    {
      id: '25-navigation-rapid-taps-step-24',
      action: 'Exercise rapid taps recovery checkpoint 24',
      input: 'navigation:fixture:25:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario25NavigationRapidTapsScenarioSummary = {
  id: Scenario25NavigationRapidTapsScenario.id,
  risk: Scenario25NavigationRapidTapsScenario.risk,
  stepCount: Scenario25NavigationRapidTapsScenario.steps.length,
  recoveryStepCount: Scenario25NavigationRapidTapsScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario25NavigationRapidTapsScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario25NavigationRapidTapsScenarioStep(index: number) {
  if (index < 0 || index >= Scenario25NavigationRapidTapsScenario.steps.length) return undefined;
  return Scenario25NavigationRapidTapsScenario.steps[index];
}

export function evaluateScenario25NavigationRapidTapsScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario25NavigationRapidTapsScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario25NavigationRapidTapsScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario25NavigationRapidTapsScenario.steps.length };
}
