import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario28ReleaseMissingBundleIdScenario: ReleaseScenario = {
  id: '28-release-missing-bundle-id',
  domain: 'release',
  title: 'Release QA · Release · missing bundle id',
  risk: 'medium',
  steps: [
    {
      id: '28-release-missing-bundle-id-step-01',
      action: 'Exercise missing bundle id recovery checkpoint 01',
      input: 'release:fixture:28:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_01',
    },
    {
      id: '28-release-missing-bundle-id-step-02',
      action: 'Exercise missing bundle id recovery checkpoint 02',
      input: 'release:fixture:28:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_02',
    },
    {
      id: '28-release-missing-bundle-id-step-03',
      action: 'Exercise missing bundle id recovery checkpoint 03',
      input: 'release:fixture:28:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_03',
    },
    {
      id: '28-release-missing-bundle-id-step-04',
      action: 'Exercise missing bundle id recovery checkpoint 04',
      input: 'release:fixture:28:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_04',
    },
    {
      id: '28-release-missing-bundle-id-step-05',
      action: 'Exercise missing bundle id recovery checkpoint 05',
      input: 'release:fixture:28:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_05',
    },
    {
      id: '28-release-missing-bundle-id-step-06',
      action: 'Exercise missing bundle id recovery checkpoint 06',
      input: 'release:fixture:28:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_06',
    },
    {
      id: '28-release-missing-bundle-id-step-07',
      action: 'Exercise missing bundle id recovery checkpoint 07',
      input: 'release:fixture:28:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_07',
    },
    {
      id: '28-release-missing-bundle-id-step-08',
      action: 'Exercise missing bundle id recovery checkpoint 08',
      input: 'release:fixture:28:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_08',
    },
    {
      id: '28-release-missing-bundle-id-step-09',
      action: 'Exercise missing bundle id recovery checkpoint 09',
      input: 'release:fixture:28:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_09',
    },
    {
      id: '28-release-missing-bundle-id-step-10',
      action: 'Exercise missing bundle id recovery checkpoint 10',
      input: 'release:fixture:28:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_10',
    },
    {
      id: '28-release-missing-bundle-id-step-11',
      action: 'Exercise missing bundle id recovery checkpoint 11',
      input: 'release:fixture:28:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_11',
    },
    {
      id: '28-release-missing-bundle-id-step-12',
      action: 'Exercise missing bundle id recovery checkpoint 12',
      input: 'release:fixture:28:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_12',
    },
    {
      id: '28-release-missing-bundle-id-step-13',
      action: 'Exercise missing bundle id recovery checkpoint 13',
      input: 'release:fixture:28:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_13',
    },
    {
      id: '28-release-missing-bundle-id-step-14',
      action: 'Exercise missing bundle id recovery checkpoint 14',
      input: 'release:fixture:28:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_14',
    },
    {
      id: '28-release-missing-bundle-id-step-15',
      action: 'Exercise missing bundle id recovery checkpoint 15',
      input: 'release:fixture:28:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_15',
    },
    {
      id: '28-release-missing-bundle-id-step-16',
      action: 'Exercise missing bundle id recovery checkpoint 16',
      input: 'release:fixture:28:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_16',
    },
    {
      id: '28-release-missing-bundle-id-step-17',
      action: 'Exercise missing bundle id recovery checkpoint 17',
      input: 'release:fixture:28:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_17',
    },
    {
      id: '28-release-missing-bundle-id-step-18',
      action: 'Exercise missing bundle id recovery checkpoint 18',
      input: 'release:fixture:28:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_18',
    },
    {
      id: '28-release-missing-bundle-id-step-19',
      action: 'Exercise missing bundle id recovery checkpoint 19',
      input: 'release:fixture:28:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_19',
    },
    {
      id: '28-release-missing-bundle-id-step-20',
      action: 'Exercise missing bundle id recovery checkpoint 20',
      input: 'release:fixture:28:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_20',
    },
    {
      id: '28-release-missing-bundle-id-step-21',
      action: 'Exercise missing bundle id recovery checkpoint 21',
      input: 'release:fixture:28:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_21',
    },
    {
      id: '28-release-missing-bundle-id-step-22',
      action: 'Exercise missing bundle id recovery checkpoint 22',
      input: 'release:fixture:28:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_22',
    },
    {
      id: '28-release-missing-bundle-id-step-23',
      action: 'Exercise missing bundle id recovery checkpoint 23',
      input: 'release:fixture:28:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_23',
    },
    {
      id: '28-release-missing-bundle-id-step-24',
      action: 'Exercise missing bundle id recovery checkpoint 24',
      input: 'release:fixture:28:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario28ReleaseMissingBundleIdScenarioSummary = {
  id: Scenario28ReleaseMissingBundleIdScenario.id,
  risk: Scenario28ReleaseMissingBundleIdScenario.risk,
  stepCount: Scenario28ReleaseMissingBundleIdScenario.steps.length,
  recoveryStepCount: Scenario28ReleaseMissingBundleIdScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario28ReleaseMissingBundleIdScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario28ReleaseMissingBundleIdScenarioStep(index: number) {
  if (index < 0 || index >= Scenario28ReleaseMissingBundleIdScenario.steps.length) return undefined;
  return Scenario28ReleaseMissingBundleIdScenario.steps[index];
}

export function evaluateScenario28ReleaseMissingBundleIdScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario28ReleaseMissingBundleIdScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario28ReleaseMissingBundleIdScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario28ReleaseMissingBundleIdScenario.steps.length };
}
