import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario29AccessibilityReduceMotionScenario: ReleaseScenario = {
  id: '29-accessibility-reduce-motion',
  domain: 'accessibility',
  title: 'Release QA · Accessibility · reduce motion',
  risk: 'medium',
  steps: [
    {
      id: '29-accessibility-reduce-motion-step-01',
      action: 'Exercise reduce motion recovery checkpoint 01',
      input: 'accessibility:fixture:29:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_01',
    },
    {
      id: '29-accessibility-reduce-motion-step-02',
      action: 'Exercise reduce motion recovery checkpoint 02',
      input: 'accessibility:fixture:29:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_02',
    },
    {
      id: '29-accessibility-reduce-motion-step-03',
      action: 'Exercise reduce motion recovery checkpoint 03',
      input: 'accessibility:fixture:29:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_03',
    },
    {
      id: '29-accessibility-reduce-motion-step-04',
      action: 'Exercise reduce motion recovery checkpoint 04',
      input: 'accessibility:fixture:29:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_04',
    },
    {
      id: '29-accessibility-reduce-motion-step-05',
      action: 'Exercise reduce motion recovery checkpoint 05',
      input: 'accessibility:fixture:29:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_05',
    },
    {
      id: '29-accessibility-reduce-motion-step-06',
      action: 'Exercise reduce motion recovery checkpoint 06',
      input: 'accessibility:fixture:29:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_06',
    },
    {
      id: '29-accessibility-reduce-motion-step-07',
      action: 'Exercise reduce motion recovery checkpoint 07',
      input: 'accessibility:fixture:29:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_07',
    },
    {
      id: '29-accessibility-reduce-motion-step-08',
      action: 'Exercise reduce motion recovery checkpoint 08',
      input: 'accessibility:fixture:29:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_08',
    },
    {
      id: '29-accessibility-reduce-motion-step-09',
      action: 'Exercise reduce motion recovery checkpoint 09',
      input: 'accessibility:fixture:29:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_09',
    },
    {
      id: '29-accessibility-reduce-motion-step-10',
      action: 'Exercise reduce motion recovery checkpoint 10',
      input: 'accessibility:fixture:29:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_10',
    },
    {
      id: '29-accessibility-reduce-motion-step-11',
      action: 'Exercise reduce motion recovery checkpoint 11',
      input: 'accessibility:fixture:29:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_11',
    },
    {
      id: '29-accessibility-reduce-motion-step-12',
      action: 'Exercise reduce motion recovery checkpoint 12',
      input: 'accessibility:fixture:29:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_12',
    },
    {
      id: '29-accessibility-reduce-motion-step-13',
      action: 'Exercise reduce motion recovery checkpoint 13',
      input: 'accessibility:fixture:29:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_13',
    },
    {
      id: '29-accessibility-reduce-motion-step-14',
      action: 'Exercise reduce motion recovery checkpoint 14',
      input: 'accessibility:fixture:29:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_14',
    },
    {
      id: '29-accessibility-reduce-motion-step-15',
      action: 'Exercise reduce motion recovery checkpoint 15',
      input: 'accessibility:fixture:29:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_15',
    },
    {
      id: '29-accessibility-reduce-motion-step-16',
      action: 'Exercise reduce motion recovery checkpoint 16',
      input: 'accessibility:fixture:29:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_16',
    },
    {
      id: '29-accessibility-reduce-motion-step-17',
      action: 'Exercise reduce motion recovery checkpoint 17',
      input: 'accessibility:fixture:29:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_17',
    },
    {
      id: '29-accessibility-reduce-motion-step-18',
      action: 'Exercise reduce motion recovery checkpoint 18',
      input: 'accessibility:fixture:29:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_18',
    },
    {
      id: '29-accessibility-reduce-motion-step-19',
      action: 'Exercise reduce motion recovery checkpoint 19',
      input: 'accessibility:fixture:29:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_19',
    },
    {
      id: '29-accessibility-reduce-motion-step-20',
      action: 'Exercise reduce motion recovery checkpoint 20',
      input: 'accessibility:fixture:29:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_20',
    },
    {
      id: '29-accessibility-reduce-motion-step-21',
      action: 'Exercise reduce motion recovery checkpoint 21',
      input: 'accessibility:fixture:29:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_21',
    },
    {
      id: '29-accessibility-reduce-motion-step-22',
      action: 'Exercise reduce motion recovery checkpoint 22',
      input: 'accessibility:fixture:29:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_22',
    },
    {
      id: '29-accessibility-reduce-motion-step-23',
      action: 'Exercise reduce motion recovery checkpoint 23',
      input: 'accessibility:fixture:29:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_23',
    },
    {
      id: '29-accessibility-reduce-motion-step-24',
      action: 'Exercise reduce motion recovery checkpoint 24',
      input: 'accessibility:fixture:29:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario29AccessibilityReduceMotionScenarioSummary = {
  id: Scenario29AccessibilityReduceMotionScenario.id,
  risk: Scenario29AccessibilityReduceMotionScenario.risk,
  stepCount: Scenario29AccessibilityReduceMotionScenario.steps.length,
  recoveryStepCount: Scenario29AccessibilityReduceMotionScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario29AccessibilityReduceMotionScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario29AccessibilityReduceMotionScenarioStep(index: number) {
  if (index < 0 || index >= Scenario29AccessibilityReduceMotionScenario.steps.length) return undefined;
  return Scenario29AccessibilityReduceMotionScenario.steps[index];
}

export function evaluateScenario29AccessibilityReduceMotionScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario29AccessibilityReduceMotionScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario29AccessibilityReduceMotionScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario29AccessibilityReduceMotionScenario.steps.length };
}
