import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario30PerformanceLargePayloadScenario: ReleaseScenario = {
  id: '30-performance-large-payload',
  domain: 'performance',
  title: 'Release QA · Performance · large payload',
  risk: 'medium',
  steps: [
    {
      id: '30-performance-large-payload-step-01',
      action: 'Exercise large payload recovery checkpoint 01',
      input: 'performance:fixture:30:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_performance_checkpoint_01',
    },
    {
      id: '30-performance-large-payload-step-02',
      action: 'Exercise large payload recovery checkpoint 02',
      input: 'performance:fixture:30:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_performance_checkpoint_02',
    },
    {
      id: '30-performance-large-payload-step-03',
      action: 'Exercise large payload recovery checkpoint 03',
      input: 'performance:fixture:30:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_performance_checkpoint_03',
    },
    {
      id: '30-performance-large-payload-step-04',
      action: 'Exercise large payload recovery checkpoint 04',
      input: 'performance:fixture:30:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_performance_checkpoint_04',
    },
    {
      id: '30-performance-large-payload-step-05',
      action: 'Exercise large payload recovery checkpoint 05',
      input: 'performance:fixture:30:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_performance_checkpoint_05',
    },
    {
      id: '30-performance-large-payload-step-06',
      action: 'Exercise large payload recovery checkpoint 06',
      input: 'performance:fixture:30:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_performance_checkpoint_06',
    },
    {
      id: '30-performance-large-payload-step-07',
      action: 'Exercise large payload recovery checkpoint 07',
      input: 'performance:fixture:30:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_performance_checkpoint_07',
    },
    {
      id: '30-performance-large-payload-step-08',
      action: 'Exercise large payload recovery checkpoint 08',
      input: 'performance:fixture:30:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_performance_checkpoint_08',
    },
    {
      id: '30-performance-large-payload-step-09',
      action: 'Exercise large payload recovery checkpoint 09',
      input: 'performance:fixture:30:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_performance_checkpoint_09',
    },
    {
      id: '30-performance-large-payload-step-10',
      action: 'Exercise large payload recovery checkpoint 10',
      input: 'performance:fixture:30:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_performance_checkpoint_10',
    },
    {
      id: '30-performance-large-payload-step-11',
      action: 'Exercise large payload recovery checkpoint 11',
      input: 'performance:fixture:30:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_performance_checkpoint_11',
    },
    {
      id: '30-performance-large-payload-step-12',
      action: 'Exercise large payload recovery checkpoint 12',
      input: 'performance:fixture:30:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_performance_checkpoint_12',
    },
    {
      id: '30-performance-large-payload-step-13',
      action: 'Exercise large payload recovery checkpoint 13',
      input: 'performance:fixture:30:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_performance_checkpoint_13',
    },
    {
      id: '30-performance-large-payload-step-14',
      action: 'Exercise large payload recovery checkpoint 14',
      input: 'performance:fixture:30:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_performance_checkpoint_14',
    },
    {
      id: '30-performance-large-payload-step-15',
      action: 'Exercise large payload recovery checkpoint 15',
      input: 'performance:fixture:30:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_performance_checkpoint_15',
    },
    {
      id: '30-performance-large-payload-step-16',
      action: 'Exercise large payload recovery checkpoint 16',
      input: 'performance:fixture:30:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_performance_checkpoint_16',
    },
    {
      id: '30-performance-large-payload-step-17',
      action: 'Exercise large payload recovery checkpoint 17',
      input: 'performance:fixture:30:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_performance_checkpoint_17',
    },
    {
      id: '30-performance-large-payload-step-18',
      action: 'Exercise large payload recovery checkpoint 18',
      input: 'performance:fixture:30:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_performance_checkpoint_18',
    },
    {
      id: '30-performance-large-payload-step-19',
      action: 'Exercise large payload recovery checkpoint 19',
      input: 'performance:fixture:30:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_performance_checkpoint_19',
    },
    {
      id: '30-performance-large-payload-step-20',
      action: 'Exercise large payload recovery checkpoint 20',
      input: 'performance:fixture:30:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_performance_checkpoint_20',
    },
    {
      id: '30-performance-large-payload-step-21',
      action: 'Exercise large payload recovery checkpoint 21',
      input: 'performance:fixture:30:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_performance_checkpoint_21',
    },
    {
      id: '30-performance-large-payload-step-22',
      action: 'Exercise large payload recovery checkpoint 22',
      input: 'performance:fixture:30:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_performance_checkpoint_22',
    },
    {
      id: '30-performance-large-payload-step-23',
      action: 'Exercise large payload recovery checkpoint 23',
      input: 'performance:fixture:30:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_performance_checkpoint_23',
    },
    {
      id: '30-performance-large-payload-step-24',
      action: 'Exercise large payload recovery checkpoint 24',
      input: 'performance:fixture:30:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_performance_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario30PerformanceLargePayloadScenarioSummary = {
  id: Scenario30PerformanceLargePayloadScenario.id,
  risk: Scenario30PerformanceLargePayloadScenario.risk,
  stepCount: Scenario30PerformanceLargePayloadScenario.steps.length,
  recoveryStepCount: Scenario30PerformanceLargePayloadScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario30PerformanceLargePayloadScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario30PerformanceLargePayloadScenarioStep(index: number) {
  if (index < 0 || index >= Scenario30PerformanceLargePayloadScenario.steps.length) return undefined;
  return Scenario30PerformanceLargePayloadScenario.steps[index];
}

export function evaluateScenario30PerformanceLargePayloadScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario30PerformanceLargePayloadScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario30PerformanceLargePayloadScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario30PerformanceLargePayloadScenario.steps.length };
}
