import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario31CameraRecordingInterruptedScenario: ReleaseScenario = {
  id: '31-camera-recording-interrupted',
  domain: 'camera',
  title: 'Release QA · Camera · recording interrupted',
  risk: 'high',
  steps: [
    {
      id: '31-camera-recording-interrupted-step-01',
      action: 'Exercise recording interrupted recovery checkpoint 01',
      input: 'camera:fixture:31:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_camera_checkpoint_01',
    },
    {
      id: '31-camera-recording-interrupted-step-02',
      action: 'Exercise recording interrupted recovery checkpoint 02',
      input: 'camera:fixture:31:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_camera_checkpoint_02',
    },
    {
      id: '31-camera-recording-interrupted-step-03',
      action: 'Exercise recording interrupted recovery checkpoint 03',
      input: 'camera:fixture:31:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_camera_checkpoint_03',
    },
    {
      id: '31-camera-recording-interrupted-step-04',
      action: 'Exercise recording interrupted recovery checkpoint 04',
      input: 'camera:fixture:31:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_camera_checkpoint_04',
    },
    {
      id: '31-camera-recording-interrupted-step-05',
      action: 'Exercise recording interrupted recovery checkpoint 05',
      input: 'camera:fixture:31:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_camera_checkpoint_05',
    },
    {
      id: '31-camera-recording-interrupted-step-06',
      action: 'Exercise recording interrupted recovery checkpoint 06',
      input: 'camera:fixture:31:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_camera_checkpoint_06',
    },
    {
      id: '31-camera-recording-interrupted-step-07',
      action: 'Exercise recording interrupted recovery checkpoint 07',
      input: 'camera:fixture:31:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_camera_checkpoint_07',
    },
    {
      id: '31-camera-recording-interrupted-step-08',
      action: 'Exercise recording interrupted recovery checkpoint 08',
      input: 'camera:fixture:31:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_camera_checkpoint_08',
    },
    {
      id: '31-camera-recording-interrupted-step-09',
      action: 'Exercise recording interrupted recovery checkpoint 09',
      input: 'camera:fixture:31:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_camera_checkpoint_09',
    },
    {
      id: '31-camera-recording-interrupted-step-10',
      action: 'Exercise recording interrupted recovery checkpoint 10',
      input: 'camera:fixture:31:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_camera_checkpoint_10',
    },
    {
      id: '31-camera-recording-interrupted-step-11',
      action: 'Exercise recording interrupted recovery checkpoint 11',
      input: 'camera:fixture:31:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_camera_checkpoint_11',
    },
    {
      id: '31-camera-recording-interrupted-step-12',
      action: 'Exercise recording interrupted recovery checkpoint 12',
      input: 'camera:fixture:31:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_camera_checkpoint_12',
    },
    {
      id: '31-camera-recording-interrupted-step-13',
      action: 'Exercise recording interrupted recovery checkpoint 13',
      input: 'camera:fixture:31:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_camera_checkpoint_13',
    },
    {
      id: '31-camera-recording-interrupted-step-14',
      action: 'Exercise recording interrupted recovery checkpoint 14',
      input: 'camera:fixture:31:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_camera_checkpoint_14',
    },
    {
      id: '31-camera-recording-interrupted-step-15',
      action: 'Exercise recording interrupted recovery checkpoint 15',
      input: 'camera:fixture:31:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_camera_checkpoint_15',
    },
    {
      id: '31-camera-recording-interrupted-step-16',
      action: 'Exercise recording interrupted recovery checkpoint 16',
      input: 'camera:fixture:31:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_camera_checkpoint_16',
    },
    {
      id: '31-camera-recording-interrupted-step-17',
      action: 'Exercise recording interrupted recovery checkpoint 17',
      input: 'camera:fixture:31:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_camera_checkpoint_17',
    },
    {
      id: '31-camera-recording-interrupted-step-18',
      action: 'Exercise recording interrupted recovery checkpoint 18',
      input: 'camera:fixture:31:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_camera_checkpoint_18',
    },
    {
      id: '31-camera-recording-interrupted-step-19',
      action: 'Exercise recording interrupted recovery checkpoint 19',
      input: 'camera:fixture:31:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_camera_checkpoint_19',
    },
    {
      id: '31-camera-recording-interrupted-step-20',
      action: 'Exercise recording interrupted recovery checkpoint 20',
      input: 'camera:fixture:31:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_camera_checkpoint_20',
    },
    {
      id: '31-camera-recording-interrupted-step-21',
      action: 'Exercise recording interrupted recovery checkpoint 21',
      input: 'camera:fixture:31:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_camera_checkpoint_21',
    },
    {
      id: '31-camera-recording-interrupted-step-22',
      action: 'Exercise recording interrupted recovery checkpoint 22',
      input: 'camera:fixture:31:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_camera_checkpoint_22',
    },
    {
      id: '31-camera-recording-interrupted-step-23',
      action: 'Exercise recording interrupted recovery checkpoint 23',
      input: 'camera:fixture:31:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_camera_checkpoint_23',
    },
    {
      id: '31-camera-recording-interrupted-step-24',
      action: 'Exercise recording interrupted recovery checkpoint 24',
      input: 'camera:fixture:31:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_camera_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario31CameraRecordingInterruptedScenarioSummary = {
  id: Scenario31CameraRecordingInterruptedScenario.id,
  risk: Scenario31CameraRecordingInterruptedScenario.risk,
  stepCount: Scenario31CameraRecordingInterruptedScenario.steps.length,
  recoveryStepCount: Scenario31CameraRecordingInterruptedScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario31CameraRecordingInterruptedScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario31CameraRecordingInterruptedScenarioStep(index: number) {
  if (index < 0 || index >= Scenario31CameraRecordingInterruptedScenario.steps.length) return undefined;
  return Scenario31CameraRecordingInterruptedScenario.steps[index];
}

export function evaluateScenario31CameraRecordingInterruptedScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario31CameraRecordingInterruptedScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario31CameraRecordingInterruptedScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario31CameraRecordingInterruptedScenario.steps.length };
}
