import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario32AnalysisCancelScenario: ReleaseScenario = {
  id: '32-analysis-cancel',
  domain: 'analysis',
  title: 'Release QA · Analysis · cancel',
  risk: 'high',
  steps: [
    {
      id: '32-analysis-cancel-step-01',
      action: 'Exercise cancel recovery checkpoint 01',
      input: 'analysis:fixture:32:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_analysis_checkpoint_01',
    },
    {
      id: '32-analysis-cancel-step-02',
      action: 'Exercise cancel recovery checkpoint 02',
      input: 'analysis:fixture:32:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_analysis_checkpoint_02',
    },
    {
      id: '32-analysis-cancel-step-03',
      action: 'Exercise cancel recovery checkpoint 03',
      input: 'analysis:fixture:32:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_analysis_checkpoint_03',
    },
    {
      id: '32-analysis-cancel-step-04',
      action: 'Exercise cancel recovery checkpoint 04',
      input: 'analysis:fixture:32:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_analysis_checkpoint_04',
    },
    {
      id: '32-analysis-cancel-step-05',
      action: 'Exercise cancel recovery checkpoint 05',
      input: 'analysis:fixture:32:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_analysis_checkpoint_05',
    },
    {
      id: '32-analysis-cancel-step-06',
      action: 'Exercise cancel recovery checkpoint 06',
      input: 'analysis:fixture:32:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_analysis_checkpoint_06',
    },
    {
      id: '32-analysis-cancel-step-07',
      action: 'Exercise cancel recovery checkpoint 07',
      input: 'analysis:fixture:32:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_analysis_checkpoint_07',
    },
    {
      id: '32-analysis-cancel-step-08',
      action: 'Exercise cancel recovery checkpoint 08',
      input: 'analysis:fixture:32:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_analysis_checkpoint_08',
    },
    {
      id: '32-analysis-cancel-step-09',
      action: 'Exercise cancel recovery checkpoint 09',
      input: 'analysis:fixture:32:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_analysis_checkpoint_09',
    },
    {
      id: '32-analysis-cancel-step-10',
      action: 'Exercise cancel recovery checkpoint 10',
      input: 'analysis:fixture:32:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_analysis_checkpoint_10',
    },
    {
      id: '32-analysis-cancel-step-11',
      action: 'Exercise cancel recovery checkpoint 11',
      input: 'analysis:fixture:32:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_analysis_checkpoint_11',
    },
    {
      id: '32-analysis-cancel-step-12',
      action: 'Exercise cancel recovery checkpoint 12',
      input: 'analysis:fixture:32:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_analysis_checkpoint_12',
    },
    {
      id: '32-analysis-cancel-step-13',
      action: 'Exercise cancel recovery checkpoint 13',
      input: 'analysis:fixture:32:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_analysis_checkpoint_13',
    },
    {
      id: '32-analysis-cancel-step-14',
      action: 'Exercise cancel recovery checkpoint 14',
      input: 'analysis:fixture:32:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_analysis_checkpoint_14',
    },
    {
      id: '32-analysis-cancel-step-15',
      action: 'Exercise cancel recovery checkpoint 15',
      input: 'analysis:fixture:32:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_analysis_checkpoint_15',
    },
    {
      id: '32-analysis-cancel-step-16',
      action: 'Exercise cancel recovery checkpoint 16',
      input: 'analysis:fixture:32:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_analysis_checkpoint_16',
    },
    {
      id: '32-analysis-cancel-step-17',
      action: 'Exercise cancel recovery checkpoint 17',
      input: 'analysis:fixture:32:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_analysis_checkpoint_17',
    },
    {
      id: '32-analysis-cancel-step-18',
      action: 'Exercise cancel recovery checkpoint 18',
      input: 'analysis:fixture:32:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_analysis_checkpoint_18',
    },
    {
      id: '32-analysis-cancel-step-19',
      action: 'Exercise cancel recovery checkpoint 19',
      input: 'analysis:fixture:32:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_analysis_checkpoint_19',
    },
    {
      id: '32-analysis-cancel-step-20',
      action: 'Exercise cancel recovery checkpoint 20',
      input: 'analysis:fixture:32:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_analysis_checkpoint_20',
    },
    {
      id: '32-analysis-cancel-step-21',
      action: 'Exercise cancel recovery checkpoint 21',
      input: 'analysis:fixture:32:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_analysis_checkpoint_21',
    },
    {
      id: '32-analysis-cancel-step-22',
      action: 'Exercise cancel recovery checkpoint 22',
      input: 'analysis:fixture:32:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_analysis_checkpoint_22',
    },
    {
      id: '32-analysis-cancel-step-23',
      action: 'Exercise cancel recovery checkpoint 23',
      input: 'analysis:fixture:32:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_analysis_checkpoint_23',
    },
    {
      id: '32-analysis-cancel-step-24',
      action: 'Exercise cancel recovery checkpoint 24',
      input: 'analysis:fixture:32:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_analysis_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario32AnalysisCancelScenarioSummary = {
  id: Scenario32AnalysisCancelScenario.id,
  risk: Scenario32AnalysisCancelScenario.risk,
  stepCount: Scenario32AnalysisCancelScenario.steps.length,
  recoveryStepCount: Scenario32AnalysisCancelScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario32AnalysisCancelScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario32AnalysisCancelScenarioStep(index: number) {
  if (index < 0 || index >= Scenario32AnalysisCancelScenario.steps.length) return undefined;
  return Scenario32AnalysisCancelScenario.steps[index];
}

export function evaluateScenario32AnalysisCancelScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario32AnalysisCancelScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario32AnalysisCancelScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario32AnalysisCancelScenario.steps.length };
}
