import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario34MediaUnsupportedFormatScenario: ReleaseScenario = {
  id: '34-media-unsupported-format',
  domain: 'media',
  title: 'Release QA · Media · unsupported format',
  risk: 'high',
  steps: [
    {
      id: '34-media-unsupported-format-step-01',
      action: 'Exercise unsupported format recovery checkpoint 01',
      input: 'media:fixture:34:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_01',
    },
    {
      id: '34-media-unsupported-format-step-02',
      action: 'Exercise unsupported format recovery checkpoint 02',
      input: 'media:fixture:34:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_02',
    },
    {
      id: '34-media-unsupported-format-step-03',
      action: 'Exercise unsupported format recovery checkpoint 03',
      input: 'media:fixture:34:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_03',
    },
    {
      id: '34-media-unsupported-format-step-04',
      action: 'Exercise unsupported format recovery checkpoint 04',
      input: 'media:fixture:34:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_04',
    },
    {
      id: '34-media-unsupported-format-step-05',
      action: 'Exercise unsupported format recovery checkpoint 05',
      input: 'media:fixture:34:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_05',
    },
    {
      id: '34-media-unsupported-format-step-06',
      action: 'Exercise unsupported format recovery checkpoint 06',
      input: 'media:fixture:34:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_06',
    },
    {
      id: '34-media-unsupported-format-step-07',
      action: 'Exercise unsupported format recovery checkpoint 07',
      input: 'media:fixture:34:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_07',
    },
    {
      id: '34-media-unsupported-format-step-08',
      action: 'Exercise unsupported format recovery checkpoint 08',
      input: 'media:fixture:34:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_08',
    },
    {
      id: '34-media-unsupported-format-step-09',
      action: 'Exercise unsupported format recovery checkpoint 09',
      input: 'media:fixture:34:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_09',
    },
    {
      id: '34-media-unsupported-format-step-10',
      action: 'Exercise unsupported format recovery checkpoint 10',
      input: 'media:fixture:34:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_10',
    },
    {
      id: '34-media-unsupported-format-step-11',
      action: 'Exercise unsupported format recovery checkpoint 11',
      input: 'media:fixture:34:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_11',
    },
    {
      id: '34-media-unsupported-format-step-12',
      action: 'Exercise unsupported format recovery checkpoint 12',
      input: 'media:fixture:34:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_12',
    },
    {
      id: '34-media-unsupported-format-step-13',
      action: 'Exercise unsupported format recovery checkpoint 13',
      input: 'media:fixture:34:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_13',
    },
    {
      id: '34-media-unsupported-format-step-14',
      action: 'Exercise unsupported format recovery checkpoint 14',
      input: 'media:fixture:34:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_14',
    },
    {
      id: '34-media-unsupported-format-step-15',
      action: 'Exercise unsupported format recovery checkpoint 15',
      input: 'media:fixture:34:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_15',
    },
    {
      id: '34-media-unsupported-format-step-16',
      action: 'Exercise unsupported format recovery checkpoint 16',
      input: 'media:fixture:34:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_16',
    },
    {
      id: '34-media-unsupported-format-step-17',
      action: 'Exercise unsupported format recovery checkpoint 17',
      input: 'media:fixture:34:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_17',
    },
    {
      id: '34-media-unsupported-format-step-18',
      action: 'Exercise unsupported format recovery checkpoint 18',
      input: 'media:fixture:34:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_18',
    },
    {
      id: '34-media-unsupported-format-step-19',
      action: 'Exercise unsupported format recovery checkpoint 19',
      input: 'media:fixture:34:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_19',
    },
    {
      id: '34-media-unsupported-format-step-20',
      action: 'Exercise unsupported format recovery checkpoint 20',
      input: 'media:fixture:34:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_20',
    },
    {
      id: '34-media-unsupported-format-step-21',
      action: 'Exercise unsupported format recovery checkpoint 21',
      input: 'media:fixture:34:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_21',
    },
    {
      id: '34-media-unsupported-format-step-22',
      action: 'Exercise unsupported format recovery checkpoint 22',
      input: 'media:fixture:34:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_22',
    },
    {
      id: '34-media-unsupported-format-step-23',
      action: 'Exercise unsupported format recovery checkpoint 23',
      input: 'media:fixture:34:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_23',
    },
    {
      id: '34-media-unsupported-format-step-24',
      action: 'Exercise unsupported format recovery checkpoint 24',
      input: 'media:fixture:34:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario34MediaUnsupportedFormatScenarioSummary = {
  id: Scenario34MediaUnsupportedFormatScenario.id,
  risk: Scenario34MediaUnsupportedFormatScenario.risk,
  stepCount: Scenario34MediaUnsupportedFormatScenario.steps.length,
  recoveryStepCount: Scenario34MediaUnsupportedFormatScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario34MediaUnsupportedFormatScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario34MediaUnsupportedFormatScenarioStep(index: number) {
  if (index < 0 || index >= Scenario34MediaUnsupportedFormatScenario.steps.length) return undefined;
  return Scenario34MediaUnsupportedFormatScenario.steps[index];
}

export function evaluateScenario34MediaUnsupportedFormatScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario34MediaUnsupportedFormatScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario34MediaUnsupportedFormatScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario34MediaUnsupportedFormatScenario.steps.length };
}
