import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario38NotificationsScheduledNotificationScenario: ReleaseScenario = {
  id: '38-notifications-scheduled-notification',
  domain: 'notifications',
  title: 'Release QA · Notifications · scheduled notification',
  risk: 'medium',
  steps: [
    {
      id: '38-notifications-scheduled-notification-step-01',
      action: 'Exercise scheduled notification recovery checkpoint 01',
      input: 'notifications:fixture:38:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_01',
    },
    {
      id: '38-notifications-scheduled-notification-step-02',
      action: 'Exercise scheduled notification recovery checkpoint 02',
      input: 'notifications:fixture:38:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_02',
    },
    {
      id: '38-notifications-scheduled-notification-step-03',
      action: 'Exercise scheduled notification recovery checkpoint 03',
      input: 'notifications:fixture:38:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_03',
    },
    {
      id: '38-notifications-scheduled-notification-step-04',
      action: 'Exercise scheduled notification recovery checkpoint 04',
      input: 'notifications:fixture:38:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_04',
    },
    {
      id: '38-notifications-scheduled-notification-step-05',
      action: 'Exercise scheduled notification recovery checkpoint 05',
      input: 'notifications:fixture:38:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_05',
    },
    {
      id: '38-notifications-scheduled-notification-step-06',
      action: 'Exercise scheduled notification recovery checkpoint 06',
      input: 'notifications:fixture:38:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_06',
    },
    {
      id: '38-notifications-scheduled-notification-step-07',
      action: 'Exercise scheduled notification recovery checkpoint 07',
      input: 'notifications:fixture:38:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_07',
    },
    {
      id: '38-notifications-scheduled-notification-step-08',
      action: 'Exercise scheduled notification recovery checkpoint 08',
      input: 'notifications:fixture:38:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_08',
    },
    {
      id: '38-notifications-scheduled-notification-step-09',
      action: 'Exercise scheduled notification recovery checkpoint 09',
      input: 'notifications:fixture:38:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_09',
    },
    {
      id: '38-notifications-scheduled-notification-step-10',
      action: 'Exercise scheduled notification recovery checkpoint 10',
      input: 'notifications:fixture:38:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_10',
    },
    {
      id: '38-notifications-scheduled-notification-step-11',
      action: 'Exercise scheduled notification recovery checkpoint 11',
      input: 'notifications:fixture:38:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_11',
    },
    {
      id: '38-notifications-scheduled-notification-step-12',
      action: 'Exercise scheduled notification recovery checkpoint 12',
      input: 'notifications:fixture:38:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_12',
    },
    {
      id: '38-notifications-scheduled-notification-step-13',
      action: 'Exercise scheduled notification recovery checkpoint 13',
      input: 'notifications:fixture:38:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_13',
    },
    {
      id: '38-notifications-scheduled-notification-step-14',
      action: 'Exercise scheduled notification recovery checkpoint 14',
      input: 'notifications:fixture:38:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_14',
    },
    {
      id: '38-notifications-scheduled-notification-step-15',
      action: 'Exercise scheduled notification recovery checkpoint 15',
      input: 'notifications:fixture:38:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_15',
    },
    {
      id: '38-notifications-scheduled-notification-step-16',
      action: 'Exercise scheduled notification recovery checkpoint 16',
      input: 'notifications:fixture:38:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_16',
    },
    {
      id: '38-notifications-scheduled-notification-step-17',
      action: 'Exercise scheduled notification recovery checkpoint 17',
      input: 'notifications:fixture:38:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_17',
    },
    {
      id: '38-notifications-scheduled-notification-step-18',
      action: 'Exercise scheduled notification recovery checkpoint 18',
      input: 'notifications:fixture:38:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_18',
    },
    {
      id: '38-notifications-scheduled-notification-step-19',
      action: 'Exercise scheduled notification recovery checkpoint 19',
      input: 'notifications:fixture:38:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_19',
    },
    {
      id: '38-notifications-scheduled-notification-step-20',
      action: 'Exercise scheduled notification recovery checkpoint 20',
      input: 'notifications:fixture:38:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_20',
    },
    {
      id: '38-notifications-scheduled-notification-step-21',
      action: 'Exercise scheduled notification recovery checkpoint 21',
      input: 'notifications:fixture:38:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_21',
    },
    {
      id: '38-notifications-scheduled-notification-step-22',
      action: 'Exercise scheduled notification recovery checkpoint 22',
      input: 'notifications:fixture:38:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_22',
    },
    {
      id: '38-notifications-scheduled-notification-step-23',
      action: 'Exercise scheduled notification recovery checkpoint 23',
      input: 'notifications:fixture:38:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_23',
    },
    {
      id: '38-notifications-scheduled-notification-step-24',
      action: 'Exercise scheduled notification recovery checkpoint 24',
      input: 'notifications:fixture:38:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario38NotificationsScheduledNotificationScenarioSummary = {
  id: Scenario38NotificationsScheduledNotificationScenario.id,
  risk: Scenario38NotificationsScheduledNotificationScenario.risk,
  stepCount: Scenario38NotificationsScheduledNotificationScenario.steps.length,
  recoveryStepCount: Scenario38NotificationsScheduledNotificationScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario38NotificationsScheduledNotificationScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario38NotificationsScheduledNotificationScenarioStep(index: number) {
  if (index < 0 || index >= Scenario38NotificationsScheduledNotificationScenario.steps.length) return undefined;
  return Scenario38NotificationsScheduledNotificationScenario.steps[index];
}

export function evaluateScenario38NotificationsScheduledNotificationScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario38NotificationsScheduledNotificationScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario38NotificationsScheduledNotificationScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario38NotificationsScheduledNotificationScenario.steps.length };
}
