import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario40NavigationBackWhileLoadingScenario: ReleaseScenario = {
  id: '40-navigation-back-while-loading',
  domain: 'navigation',
  title: 'Release QA · Navigation · back while loading',
  risk: 'medium',
  steps: [
    {
      id: '40-navigation-back-while-loading-step-01',
      action: 'Exercise back while loading recovery checkpoint 01',
      input: 'navigation:fixture:40:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_01',
    },
    {
      id: '40-navigation-back-while-loading-step-02',
      action: 'Exercise back while loading recovery checkpoint 02',
      input: 'navigation:fixture:40:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_02',
    },
    {
      id: '40-navigation-back-while-loading-step-03',
      action: 'Exercise back while loading recovery checkpoint 03',
      input: 'navigation:fixture:40:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_03',
    },
    {
      id: '40-navigation-back-while-loading-step-04',
      action: 'Exercise back while loading recovery checkpoint 04',
      input: 'navigation:fixture:40:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_04',
    },
    {
      id: '40-navigation-back-while-loading-step-05',
      action: 'Exercise back while loading recovery checkpoint 05',
      input: 'navigation:fixture:40:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_05',
    },
    {
      id: '40-navigation-back-while-loading-step-06',
      action: 'Exercise back while loading recovery checkpoint 06',
      input: 'navigation:fixture:40:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_06',
    },
    {
      id: '40-navigation-back-while-loading-step-07',
      action: 'Exercise back while loading recovery checkpoint 07',
      input: 'navigation:fixture:40:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_07',
    },
    {
      id: '40-navigation-back-while-loading-step-08',
      action: 'Exercise back while loading recovery checkpoint 08',
      input: 'navigation:fixture:40:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_08',
    },
    {
      id: '40-navigation-back-while-loading-step-09',
      action: 'Exercise back while loading recovery checkpoint 09',
      input: 'navigation:fixture:40:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_09',
    },
    {
      id: '40-navigation-back-while-loading-step-10',
      action: 'Exercise back while loading recovery checkpoint 10',
      input: 'navigation:fixture:40:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_10',
    },
    {
      id: '40-navigation-back-while-loading-step-11',
      action: 'Exercise back while loading recovery checkpoint 11',
      input: 'navigation:fixture:40:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_11',
    },
    {
      id: '40-navigation-back-while-loading-step-12',
      action: 'Exercise back while loading recovery checkpoint 12',
      input: 'navigation:fixture:40:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_12',
    },
    {
      id: '40-navigation-back-while-loading-step-13',
      action: 'Exercise back while loading recovery checkpoint 13',
      input: 'navigation:fixture:40:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_13',
    },
    {
      id: '40-navigation-back-while-loading-step-14',
      action: 'Exercise back while loading recovery checkpoint 14',
      input: 'navigation:fixture:40:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_14',
    },
    {
      id: '40-navigation-back-while-loading-step-15',
      action: 'Exercise back while loading recovery checkpoint 15',
      input: 'navigation:fixture:40:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_15',
    },
    {
      id: '40-navigation-back-while-loading-step-16',
      action: 'Exercise back while loading recovery checkpoint 16',
      input: 'navigation:fixture:40:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_16',
    },
    {
      id: '40-navigation-back-while-loading-step-17',
      action: 'Exercise back while loading recovery checkpoint 17',
      input: 'navigation:fixture:40:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_17',
    },
    {
      id: '40-navigation-back-while-loading-step-18',
      action: 'Exercise back while loading recovery checkpoint 18',
      input: 'navigation:fixture:40:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_18',
    },
    {
      id: '40-navigation-back-while-loading-step-19',
      action: 'Exercise back while loading recovery checkpoint 19',
      input: 'navigation:fixture:40:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_19',
    },
    {
      id: '40-navigation-back-while-loading-step-20',
      action: 'Exercise back while loading recovery checkpoint 20',
      input: 'navigation:fixture:40:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_20',
    },
    {
      id: '40-navigation-back-while-loading-step-21',
      action: 'Exercise back while loading recovery checkpoint 21',
      input: 'navigation:fixture:40:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_21',
    },
    {
      id: '40-navigation-back-while-loading-step-22',
      action: 'Exercise back while loading recovery checkpoint 22',
      input: 'navigation:fixture:40:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_22',
    },
    {
      id: '40-navigation-back-while-loading-step-23',
      action: 'Exercise back while loading recovery checkpoint 23',
      input: 'navigation:fixture:40:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_23',
    },
    {
      id: '40-navigation-back-while-loading-step-24',
      action: 'Exercise back while loading recovery checkpoint 24',
      input: 'navigation:fixture:40:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario40NavigationBackWhileLoadingScenarioSummary = {
  id: Scenario40NavigationBackWhileLoadingScenario.id,
  risk: Scenario40NavigationBackWhileLoadingScenario.risk,
  stepCount: Scenario40NavigationBackWhileLoadingScenario.steps.length,
  recoveryStepCount: Scenario40NavigationBackWhileLoadingScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario40NavigationBackWhileLoadingScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario40NavigationBackWhileLoadingScenarioStep(index: number) {
  if (index < 0 || index >= Scenario40NavigationBackWhileLoadingScenario.steps.length) return undefined;
  return Scenario40NavigationBackWhileLoadingScenario.steps[index];
}

export function evaluateScenario40NavigationBackWhileLoadingScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario40NavigationBackWhileLoadingScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario40NavigationBackWhileLoadingScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario40NavigationBackWhileLoadingScenario.steps.length };
}
