import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario61CameraThermalWarningScenario: ReleaseScenario = {
  id: '61-camera-thermal-warning',
  domain: 'camera',
  title: 'Release QA · Camera · thermal warning',
  risk: 'high',
  steps: [
    {
      id: '61-camera-thermal-warning-step-01',
      action: 'Exercise thermal warning recovery checkpoint 01',
      input: 'camera:fixture:61:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_camera_checkpoint_01',
    },
    {
      id: '61-camera-thermal-warning-step-02',
      action: 'Exercise thermal warning recovery checkpoint 02',
      input: 'camera:fixture:61:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_camera_checkpoint_02',
    },
    {
      id: '61-camera-thermal-warning-step-03',
      action: 'Exercise thermal warning recovery checkpoint 03',
      input: 'camera:fixture:61:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_camera_checkpoint_03',
    },
    {
      id: '61-camera-thermal-warning-step-04',
      action: 'Exercise thermal warning recovery checkpoint 04',
      input: 'camera:fixture:61:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_camera_checkpoint_04',
    },
    {
      id: '61-camera-thermal-warning-step-05',
      action: 'Exercise thermal warning recovery checkpoint 05',
      input: 'camera:fixture:61:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_camera_checkpoint_05',
    },
    {
      id: '61-camera-thermal-warning-step-06',
      action: 'Exercise thermal warning recovery checkpoint 06',
      input: 'camera:fixture:61:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_camera_checkpoint_06',
    },
    {
      id: '61-camera-thermal-warning-step-07',
      action: 'Exercise thermal warning recovery checkpoint 07',
      input: 'camera:fixture:61:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_camera_checkpoint_07',
    },
    {
      id: '61-camera-thermal-warning-step-08',
      action: 'Exercise thermal warning recovery checkpoint 08',
      input: 'camera:fixture:61:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_camera_checkpoint_08',
    },
    {
      id: '61-camera-thermal-warning-step-09',
      action: 'Exercise thermal warning recovery checkpoint 09',
      input: 'camera:fixture:61:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_camera_checkpoint_09',
    },
    {
      id: '61-camera-thermal-warning-step-10',
      action: 'Exercise thermal warning recovery checkpoint 10',
      input: 'camera:fixture:61:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_camera_checkpoint_10',
    },
    {
      id: '61-camera-thermal-warning-step-11',
      action: 'Exercise thermal warning recovery checkpoint 11',
      input: 'camera:fixture:61:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_camera_checkpoint_11',
    },
    {
      id: '61-camera-thermal-warning-step-12',
      action: 'Exercise thermal warning recovery checkpoint 12',
      input: 'camera:fixture:61:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_camera_checkpoint_12',
    },
    {
      id: '61-camera-thermal-warning-step-13',
      action: 'Exercise thermal warning recovery checkpoint 13',
      input: 'camera:fixture:61:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_camera_checkpoint_13',
    },
    {
      id: '61-camera-thermal-warning-step-14',
      action: 'Exercise thermal warning recovery checkpoint 14',
      input: 'camera:fixture:61:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_camera_checkpoint_14',
    },
    {
      id: '61-camera-thermal-warning-step-15',
      action: 'Exercise thermal warning recovery checkpoint 15',
      input: 'camera:fixture:61:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_camera_checkpoint_15',
    },
    {
      id: '61-camera-thermal-warning-step-16',
      action: 'Exercise thermal warning recovery checkpoint 16',
      input: 'camera:fixture:61:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_camera_checkpoint_16',
    },
    {
      id: '61-camera-thermal-warning-step-17',
      action: 'Exercise thermal warning recovery checkpoint 17',
      input: 'camera:fixture:61:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_camera_checkpoint_17',
    },
    {
      id: '61-camera-thermal-warning-step-18',
      action: 'Exercise thermal warning recovery checkpoint 18',
      input: 'camera:fixture:61:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_camera_checkpoint_18',
    },
    {
      id: '61-camera-thermal-warning-step-19',
      action: 'Exercise thermal warning recovery checkpoint 19',
      input: 'camera:fixture:61:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_camera_checkpoint_19',
    },
    {
      id: '61-camera-thermal-warning-step-20',
      action: 'Exercise thermal warning recovery checkpoint 20',
      input: 'camera:fixture:61:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_camera_checkpoint_20',
    },
    {
      id: '61-camera-thermal-warning-step-21',
      action: 'Exercise thermal warning recovery checkpoint 21',
      input: 'camera:fixture:61:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_camera_checkpoint_21',
    },
    {
      id: '61-camera-thermal-warning-step-22',
      action: 'Exercise thermal warning recovery checkpoint 22',
      input: 'camera:fixture:61:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_camera_checkpoint_22',
    },
    {
      id: '61-camera-thermal-warning-step-23',
      action: 'Exercise thermal warning recovery checkpoint 23',
      input: 'camera:fixture:61:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_camera_checkpoint_23',
    },
    {
      id: '61-camera-thermal-warning-step-24',
      action: 'Exercise thermal warning recovery checkpoint 24',
      input: 'camera:fixture:61:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_camera_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario61CameraThermalWarningScenarioSummary = {
  id: Scenario61CameraThermalWarningScenario.id,
  risk: Scenario61CameraThermalWarningScenario.risk,
  stepCount: Scenario61CameraThermalWarningScenario.steps.length,
  recoveryStepCount: Scenario61CameraThermalWarningScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario61CameraThermalWarningScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario61CameraThermalWarningScenarioStep(index: number) {
  if (index < 0 || index >= Scenario61CameraThermalWarningScenario.steps.length) return undefined;
  return Scenario61CameraThermalWarningScenario.steps[index];
}

export function evaluateScenario61CameraThermalWarningScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario61CameraThermalWarningScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario61CameraThermalWarningScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario61CameraThermalWarningScenario.steps.length };
}
