import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario64MediaDeletedAssetScenario: ReleaseScenario = {
  id: '64-media-deleted-asset',
  domain: 'media',
  title: 'Release QA · Media · deleted asset',
  risk: 'high',
  steps: [
    {
      id: '64-media-deleted-asset-step-01',
      action: 'Exercise deleted asset recovery checkpoint 01',
      input: 'media:fixture:64:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_01',
    },
    {
      id: '64-media-deleted-asset-step-02',
      action: 'Exercise deleted asset recovery checkpoint 02',
      input: 'media:fixture:64:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_02',
    },
    {
      id: '64-media-deleted-asset-step-03',
      action: 'Exercise deleted asset recovery checkpoint 03',
      input: 'media:fixture:64:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_03',
    },
    {
      id: '64-media-deleted-asset-step-04',
      action: 'Exercise deleted asset recovery checkpoint 04',
      input: 'media:fixture:64:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_04',
    },
    {
      id: '64-media-deleted-asset-step-05',
      action: 'Exercise deleted asset recovery checkpoint 05',
      input: 'media:fixture:64:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_05',
    },
    {
      id: '64-media-deleted-asset-step-06',
      action: 'Exercise deleted asset recovery checkpoint 06',
      input: 'media:fixture:64:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_06',
    },
    {
      id: '64-media-deleted-asset-step-07',
      action: 'Exercise deleted asset recovery checkpoint 07',
      input: 'media:fixture:64:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_07',
    },
    {
      id: '64-media-deleted-asset-step-08',
      action: 'Exercise deleted asset recovery checkpoint 08',
      input: 'media:fixture:64:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_08',
    },
    {
      id: '64-media-deleted-asset-step-09',
      action: 'Exercise deleted asset recovery checkpoint 09',
      input: 'media:fixture:64:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_09',
    },
    {
      id: '64-media-deleted-asset-step-10',
      action: 'Exercise deleted asset recovery checkpoint 10',
      input: 'media:fixture:64:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_10',
    },
    {
      id: '64-media-deleted-asset-step-11',
      action: 'Exercise deleted asset recovery checkpoint 11',
      input: 'media:fixture:64:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_11',
    },
    {
      id: '64-media-deleted-asset-step-12',
      action: 'Exercise deleted asset recovery checkpoint 12',
      input: 'media:fixture:64:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_12',
    },
    {
      id: '64-media-deleted-asset-step-13',
      action: 'Exercise deleted asset recovery checkpoint 13',
      input: 'media:fixture:64:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_13',
    },
    {
      id: '64-media-deleted-asset-step-14',
      action: 'Exercise deleted asset recovery checkpoint 14',
      input: 'media:fixture:64:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_14',
    },
    {
      id: '64-media-deleted-asset-step-15',
      action: 'Exercise deleted asset recovery checkpoint 15',
      input: 'media:fixture:64:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_15',
    },
    {
      id: '64-media-deleted-asset-step-16',
      action: 'Exercise deleted asset recovery checkpoint 16',
      input: 'media:fixture:64:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_16',
    },
    {
      id: '64-media-deleted-asset-step-17',
      action: 'Exercise deleted asset recovery checkpoint 17',
      input: 'media:fixture:64:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_17',
    },
    {
      id: '64-media-deleted-asset-step-18',
      action: 'Exercise deleted asset recovery checkpoint 18',
      input: 'media:fixture:64:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_18',
    },
    {
      id: '64-media-deleted-asset-step-19',
      action: 'Exercise deleted asset recovery checkpoint 19',
      input: 'media:fixture:64:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_19',
    },
    {
      id: '64-media-deleted-asset-step-20',
      action: 'Exercise deleted asset recovery checkpoint 20',
      input: 'media:fixture:64:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_20',
    },
    {
      id: '64-media-deleted-asset-step-21',
      action: 'Exercise deleted asset recovery checkpoint 21',
      input: 'media:fixture:64:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_21',
    },
    {
      id: '64-media-deleted-asset-step-22',
      action: 'Exercise deleted asset recovery checkpoint 22',
      input: 'media:fixture:64:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_22',
    },
    {
      id: '64-media-deleted-asset-step-23',
      action: 'Exercise deleted asset recovery checkpoint 23',
      input: 'media:fixture:64:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_23',
    },
    {
      id: '64-media-deleted-asset-step-24',
      action: 'Exercise deleted asset recovery checkpoint 24',
      input: 'media:fixture:64:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario64MediaDeletedAssetScenarioSummary = {
  id: Scenario64MediaDeletedAssetScenario.id,
  risk: Scenario64MediaDeletedAssetScenario.risk,
  stepCount: Scenario64MediaDeletedAssetScenario.steps.length,
  recoveryStepCount: Scenario64MediaDeletedAssetScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario64MediaDeletedAssetScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario64MediaDeletedAssetScenarioStep(index: number) {
  if (index < 0 || index >= Scenario64MediaDeletedAssetScenario.steps.length) return undefined;
  return Scenario64MediaDeletedAssetScenario.steps[index];
}

export function evaluateScenario64MediaDeletedAssetScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario64MediaDeletedAssetScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario64MediaDeletedAssetScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario64MediaDeletedAssetScenario.steps.length };
}
