import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario67SharingFileMissingScenario: ReleaseScenario = {
  id: '67-sharing-file-missing',
  domain: 'sharing',
  title: 'Release QA · Sharing · file missing',
  risk: 'medium',
  steps: [
    {
      id: '67-sharing-file-missing-step-01',
      action: 'Exercise file missing recovery checkpoint 01',
      input: 'sharing:fixture:67:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_sharing_checkpoint_01',
    },
    {
      id: '67-sharing-file-missing-step-02',
      action: 'Exercise file missing recovery checkpoint 02',
      input: 'sharing:fixture:67:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_sharing_checkpoint_02',
    },
    {
      id: '67-sharing-file-missing-step-03',
      action: 'Exercise file missing recovery checkpoint 03',
      input: 'sharing:fixture:67:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_sharing_checkpoint_03',
    },
    {
      id: '67-sharing-file-missing-step-04',
      action: 'Exercise file missing recovery checkpoint 04',
      input: 'sharing:fixture:67:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_sharing_checkpoint_04',
    },
    {
      id: '67-sharing-file-missing-step-05',
      action: 'Exercise file missing recovery checkpoint 05',
      input: 'sharing:fixture:67:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_sharing_checkpoint_05',
    },
    {
      id: '67-sharing-file-missing-step-06',
      action: 'Exercise file missing recovery checkpoint 06',
      input: 'sharing:fixture:67:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_sharing_checkpoint_06',
    },
    {
      id: '67-sharing-file-missing-step-07',
      action: 'Exercise file missing recovery checkpoint 07',
      input: 'sharing:fixture:67:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_sharing_checkpoint_07',
    },
    {
      id: '67-sharing-file-missing-step-08',
      action: 'Exercise file missing recovery checkpoint 08',
      input: 'sharing:fixture:67:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_sharing_checkpoint_08',
    },
    {
      id: '67-sharing-file-missing-step-09',
      action: 'Exercise file missing recovery checkpoint 09',
      input: 'sharing:fixture:67:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_sharing_checkpoint_09',
    },
    {
      id: '67-sharing-file-missing-step-10',
      action: 'Exercise file missing recovery checkpoint 10',
      input: 'sharing:fixture:67:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_sharing_checkpoint_10',
    },
    {
      id: '67-sharing-file-missing-step-11',
      action: 'Exercise file missing recovery checkpoint 11',
      input: 'sharing:fixture:67:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_sharing_checkpoint_11',
    },
    {
      id: '67-sharing-file-missing-step-12',
      action: 'Exercise file missing recovery checkpoint 12',
      input: 'sharing:fixture:67:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_sharing_checkpoint_12',
    },
    {
      id: '67-sharing-file-missing-step-13',
      action: 'Exercise file missing recovery checkpoint 13',
      input: 'sharing:fixture:67:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_sharing_checkpoint_13',
    },
    {
      id: '67-sharing-file-missing-step-14',
      action: 'Exercise file missing recovery checkpoint 14',
      input: 'sharing:fixture:67:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_sharing_checkpoint_14',
    },
    {
      id: '67-sharing-file-missing-step-15',
      action: 'Exercise file missing recovery checkpoint 15',
      input: 'sharing:fixture:67:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_sharing_checkpoint_15',
    },
    {
      id: '67-sharing-file-missing-step-16',
      action: 'Exercise file missing recovery checkpoint 16',
      input: 'sharing:fixture:67:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_sharing_checkpoint_16',
    },
    {
      id: '67-sharing-file-missing-step-17',
      action: 'Exercise file missing recovery checkpoint 17',
      input: 'sharing:fixture:67:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_sharing_checkpoint_17',
    },
    {
      id: '67-sharing-file-missing-step-18',
      action: 'Exercise file missing recovery checkpoint 18',
      input: 'sharing:fixture:67:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_sharing_checkpoint_18',
    },
    {
      id: '67-sharing-file-missing-step-19',
      action: 'Exercise file missing recovery checkpoint 19',
      input: 'sharing:fixture:67:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_sharing_checkpoint_19',
    },
    {
      id: '67-sharing-file-missing-step-20',
      action: 'Exercise file missing recovery checkpoint 20',
      input: 'sharing:fixture:67:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_sharing_checkpoint_20',
    },
    {
      id: '67-sharing-file-missing-step-21',
      action: 'Exercise file missing recovery checkpoint 21',
      input: 'sharing:fixture:67:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_sharing_checkpoint_21',
    },
    {
      id: '67-sharing-file-missing-step-22',
      action: 'Exercise file missing recovery checkpoint 22',
      input: 'sharing:fixture:67:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_sharing_checkpoint_22',
    },
    {
      id: '67-sharing-file-missing-step-23',
      action: 'Exercise file missing recovery checkpoint 23',
      input: 'sharing:fixture:67:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_sharing_checkpoint_23',
    },
    {
      id: '67-sharing-file-missing-step-24',
      action: 'Exercise file missing recovery checkpoint 24',
      input: 'sharing:fixture:67:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_sharing_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario67SharingFileMissingScenarioSummary = {
  id: Scenario67SharingFileMissingScenario.id,
  risk: Scenario67SharingFileMissingScenario.risk,
  stepCount: Scenario67SharingFileMissingScenario.steps.length,
  recoveryStepCount: Scenario67SharingFileMissingScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario67SharingFileMissingScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario67SharingFileMissingScenarioStep(index: number) {
  if (index < 0 || index >= Scenario67SharingFileMissingScenario.steps.length) return undefined;
  return Scenario67SharingFileMissingScenario.steps[index];
}

export function evaluateScenario67SharingFileMissingScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario67SharingFileMissingScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario67SharingFileMissingScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario67SharingFileMissingScenario.steps.length };
}
