import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario68NotificationsDisabledRemindersScenario: ReleaseScenario = {
  id: '68-notifications-disabled-reminders',
  domain: 'notifications',
  title: 'Release QA · Notifications · disabled reminders',
  risk: 'medium',
  steps: [
    {
      id: '68-notifications-disabled-reminders-step-01',
      action: 'Exercise disabled reminders recovery checkpoint 01',
      input: 'notifications:fixture:68:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_01',
    },
    {
      id: '68-notifications-disabled-reminders-step-02',
      action: 'Exercise disabled reminders recovery checkpoint 02',
      input: 'notifications:fixture:68:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_02',
    },
    {
      id: '68-notifications-disabled-reminders-step-03',
      action: 'Exercise disabled reminders recovery checkpoint 03',
      input: 'notifications:fixture:68:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_03',
    },
    {
      id: '68-notifications-disabled-reminders-step-04',
      action: 'Exercise disabled reminders recovery checkpoint 04',
      input: 'notifications:fixture:68:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_04',
    },
    {
      id: '68-notifications-disabled-reminders-step-05',
      action: 'Exercise disabled reminders recovery checkpoint 05',
      input: 'notifications:fixture:68:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_05',
    },
    {
      id: '68-notifications-disabled-reminders-step-06',
      action: 'Exercise disabled reminders recovery checkpoint 06',
      input: 'notifications:fixture:68:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_06',
    },
    {
      id: '68-notifications-disabled-reminders-step-07',
      action: 'Exercise disabled reminders recovery checkpoint 07',
      input: 'notifications:fixture:68:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_07',
    },
    {
      id: '68-notifications-disabled-reminders-step-08',
      action: 'Exercise disabled reminders recovery checkpoint 08',
      input: 'notifications:fixture:68:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_08',
    },
    {
      id: '68-notifications-disabled-reminders-step-09',
      action: 'Exercise disabled reminders recovery checkpoint 09',
      input: 'notifications:fixture:68:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_09',
    },
    {
      id: '68-notifications-disabled-reminders-step-10',
      action: 'Exercise disabled reminders recovery checkpoint 10',
      input: 'notifications:fixture:68:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_10',
    },
    {
      id: '68-notifications-disabled-reminders-step-11',
      action: 'Exercise disabled reminders recovery checkpoint 11',
      input: 'notifications:fixture:68:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_11',
    },
    {
      id: '68-notifications-disabled-reminders-step-12',
      action: 'Exercise disabled reminders recovery checkpoint 12',
      input: 'notifications:fixture:68:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_12',
    },
    {
      id: '68-notifications-disabled-reminders-step-13',
      action: 'Exercise disabled reminders recovery checkpoint 13',
      input: 'notifications:fixture:68:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_13',
    },
    {
      id: '68-notifications-disabled-reminders-step-14',
      action: 'Exercise disabled reminders recovery checkpoint 14',
      input: 'notifications:fixture:68:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_14',
    },
    {
      id: '68-notifications-disabled-reminders-step-15',
      action: 'Exercise disabled reminders recovery checkpoint 15',
      input: 'notifications:fixture:68:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_15',
    },
    {
      id: '68-notifications-disabled-reminders-step-16',
      action: 'Exercise disabled reminders recovery checkpoint 16',
      input: 'notifications:fixture:68:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_16',
    },
    {
      id: '68-notifications-disabled-reminders-step-17',
      action: 'Exercise disabled reminders recovery checkpoint 17',
      input: 'notifications:fixture:68:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_17',
    },
    {
      id: '68-notifications-disabled-reminders-step-18',
      action: 'Exercise disabled reminders recovery checkpoint 18',
      input: 'notifications:fixture:68:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_18',
    },
    {
      id: '68-notifications-disabled-reminders-step-19',
      action: 'Exercise disabled reminders recovery checkpoint 19',
      input: 'notifications:fixture:68:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_19',
    },
    {
      id: '68-notifications-disabled-reminders-step-20',
      action: 'Exercise disabled reminders recovery checkpoint 20',
      input: 'notifications:fixture:68:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_notifications_checkpoint_20',
    },
    {
      id: '68-notifications-disabled-reminders-step-21',
      action: 'Exercise disabled reminders recovery checkpoint 21',
      input: 'notifications:fixture:68:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_notifications_checkpoint_21',
    },
    {
      id: '68-notifications-disabled-reminders-step-22',
      action: 'Exercise disabled reminders recovery checkpoint 22',
      input: 'notifications:fixture:68:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_notifications_checkpoint_22',
    },
    {
      id: '68-notifications-disabled-reminders-step-23',
      action: 'Exercise disabled reminders recovery checkpoint 23',
      input: 'notifications:fixture:68:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_notifications_checkpoint_23',
    },
    {
      id: '68-notifications-disabled-reminders-step-24',
      action: 'Exercise disabled reminders recovery checkpoint 24',
      input: 'notifications:fixture:68:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_notifications_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario68NotificationsDisabledRemindersScenarioSummary = {
  id: Scenario68NotificationsDisabledRemindersScenario.id,
  risk: Scenario68NotificationsDisabledRemindersScenario.risk,
  stepCount: Scenario68NotificationsDisabledRemindersScenario.steps.length,
  recoveryStepCount: Scenario68NotificationsDisabledRemindersScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario68NotificationsDisabledRemindersScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario68NotificationsDisabledRemindersScenarioStep(index: number) {
  if (index < 0 || index >= Scenario68NotificationsDisabledRemindersScenario.steps.length) return undefined;
  return Scenario68NotificationsDisabledRemindersScenario.steps[index];
}

export function evaluateScenario68NotificationsDisabledRemindersScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario68NotificationsDisabledRemindersScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario68NotificationsDisabledRemindersScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario68NotificationsDisabledRemindersScenario.steps.length };
}
