import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario70NavigationTabResetScenario: ReleaseScenario = {
  id: '70-navigation-tab-reset',
  domain: 'navigation',
  title: 'Release QA · Navigation · tab reset',
  risk: 'medium',
  steps: [
    {
      id: '70-navigation-tab-reset-step-01',
      action: 'Exercise tab reset recovery checkpoint 01',
      input: 'navigation:fixture:70:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_01',
    },
    {
      id: '70-navigation-tab-reset-step-02',
      action: 'Exercise tab reset recovery checkpoint 02',
      input: 'navigation:fixture:70:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_02',
    },
    {
      id: '70-navigation-tab-reset-step-03',
      action: 'Exercise tab reset recovery checkpoint 03',
      input: 'navigation:fixture:70:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_03',
    },
    {
      id: '70-navigation-tab-reset-step-04',
      action: 'Exercise tab reset recovery checkpoint 04',
      input: 'navigation:fixture:70:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_04',
    },
    {
      id: '70-navigation-tab-reset-step-05',
      action: 'Exercise tab reset recovery checkpoint 05',
      input: 'navigation:fixture:70:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_05',
    },
    {
      id: '70-navigation-tab-reset-step-06',
      action: 'Exercise tab reset recovery checkpoint 06',
      input: 'navigation:fixture:70:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_06',
    },
    {
      id: '70-navigation-tab-reset-step-07',
      action: 'Exercise tab reset recovery checkpoint 07',
      input: 'navigation:fixture:70:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_07',
    },
    {
      id: '70-navigation-tab-reset-step-08',
      action: 'Exercise tab reset recovery checkpoint 08',
      input: 'navigation:fixture:70:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_08',
    },
    {
      id: '70-navigation-tab-reset-step-09',
      action: 'Exercise tab reset recovery checkpoint 09',
      input: 'navigation:fixture:70:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_09',
    },
    {
      id: '70-navigation-tab-reset-step-10',
      action: 'Exercise tab reset recovery checkpoint 10',
      input: 'navigation:fixture:70:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_10',
    },
    {
      id: '70-navigation-tab-reset-step-11',
      action: 'Exercise tab reset recovery checkpoint 11',
      input: 'navigation:fixture:70:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_11',
    },
    {
      id: '70-navigation-tab-reset-step-12',
      action: 'Exercise tab reset recovery checkpoint 12',
      input: 'navigation:fixture:70:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_12',
    },
    {
      id: '70-navigation-tab-reset-step-13',
      action: 'Exercise tab reset recovery checkpoint 13',
      input: 'navigation:fixture:70:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_13',
    },
    {
      id: '70-navigation-tab-reset-step-14',
      action: 'Exercise tab reset recovery checkpoint 14',
      input: 'navigation:fixture:70:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_14',
    },
    {
      id: '70-navigation-tab-reset-step-15',
      action: 'Exercise tab reset recovery checkpoint 15',
      input: 'navigation:fixture:70:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_15',
    },
    {
      id: '70-navigation-tab-reset-step-16',
      action: 'Exercise tab reset recovery checkpoint 16',
      input: 'navigation:fixture:70:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_16',
    },
    {
      id: '70-navigation-tab-reset-step-17',
      action: 'Exercise tab reset recovery checkpoint 17',
      input: 'navigation:fixture:70:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_17',
    },
    {
      id: '70-navigation-tab-reset-step-18',
      action: 'Exercise tab reset recovery checkpoint 18',
      input: 'navigation:fixture:70:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_18',
    },
    {
      id: '70-navigation-tab-reset-step-19',
      action: 'Exercise tab reset recovery checkpoint 19',
      input: 'navigation:fixture:70:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_19',
    },
    {
      id: '70-navigation-tab-reset-step-20',
      action: 'Exercise tab reset recovery checkpoint 20',
      input: 'navigation:fixture:70:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_navigation_checkpoint_20',
    },
    {
      id: '70-navigation-tab-reset-step-21',
      action: 'Exercise tab reset recovery checkpoint 21',
      input: 'navigation:fixture:70:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_navigation_checkpoint_21',
    },
    {
      id: '70-navigation-tab-reset-step-22',
      action: 'Exercise tab reset recovery checkpoint 22',
      input: 'navigation:fixture:70:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_navigation_checkpoint_22',
    },
    {
      id: '70-navigation-tab-reset-step-23',
      action: 'Exercise tab reset recovery checkpoint 23',
      input: 'navigation:fixture:70:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_navigation_checkpoint_23',
    },
    {
      id: '70-navigation-tab-reset-step-24',
      action: 'Exercise tab reset recovery checkpoint 24',
      input: 'navigation:fixture:70:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_navigation_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario70NavigationTabResetScenarioSummary = {
  id: Scenario70NavigationTabResetScenario.id,
  risk: Scenario70NavigationTabResetScenario.risk,
  stepCount: Scenario70NavigationTabResetScenario.steps.length,
  recoveryStepCount: Scenario70NavigationTabResetScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario70NavigationTabResetScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario70NavigationTabResetScenarioStep(index: number) {
  if (index < 0 || index >= Scenario70NavigationTabResetScenario.steps.length) return undefined;
  return Scenario70NavigationTabResetScenario.steps[index];
}

export function evaluateScenario70NavigationTabResetScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario70NavigationTabResetScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario70NavigationTabResetScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario70NavigationTabResetScenario.steps.length };
}
