import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario73ReleaseMetadataUrlScenario: ReleaseScenario = {
  id: '73-release-metadata-url',
  domain: 'release',
  title: 'Release QA · Release · metadata URL',
  risk: 'medium',
  steps: [
    {
      id: '73-release-metadata-url-step-01',
      action: 'Exercise metadata URL recovery checkpoint 01',
      input: 'release:fixture:73:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_01',
    },
    {
      id: '73-release-metadata-url-step-02',
      action: 'Exercise metadata URL recovery checkpoint 02',
      input: 'release:fixture:73:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_02',
    },
    {
      id: '73-release-metadata-url-step-03',
      action: 'Exercise metadata URL recovery checkpoint 03',
      input: 'release:fixture:73:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_03',
    },
    {
      id: '73-release-metadata-url-step-04',
      action: 'Exercise metadata URL recovery checkpoint 04',
      input: 'release:fixture:73:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_04',
    },
    {
      id: '73-release-metadata-url-step-05',
      action: 'Exercise metadata URL recovery checkpoint 05',
      input: 'release:fixture:73:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_05',
    },
    {
      id: '73-release-metadata-url-step-06',
      action: 'Exercise metadata URL recovery checkpoint 06',
      input: 'release:fixture:73:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_06',
    },
    {
      id: '73-release-metadata-url-step-07',
      action: 'Exercise metadata URL recovery checkpoint 07',
      input: 'release:fixture:73:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_07',
    },
    {
      id: '73-release-metadata-url-step-08',
      action: 'Exercise metadata URL recovery checkpoint 08',
      input: 'release:fixture:73:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_08',
    },
    {
      id: '73-release-metadata-url-step-09',
      action: 'Exercise metadata URL recovery checkpoint 09',
      input: 'release:fixture:73:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_09',
    },
    {
      id: '73-release-metadata-url-step-10',
      action: 'Exercise metadata URL recovery checkpoint 10',
      input: 'release:fixture:73:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_10',
    },
    {
      id: '73-release-metadata-url-step-11',
      action: 'Exercise metadata URL recovery checkpoint 11',
      input: 'release:fixture:73:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_11',
    },
    {
      id: '73-release-metadata-url-step-12',
      action: 'Exercise metadata URL recovery checkpoint 12',
      input: 'release:fixture:73:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_12',
    },
    {
      id: '73-release-metadata-url-step-13',
      action: 'Exercise metadata URL recovery checkpoint 13',
      input: 'release:fixture:73:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_13',
    },
    {
      id: '73-release-metadata-url-step-14',
      action: 'Exercise metadata URL recovery checkpoint 14',
      input: 'release:fixture:73:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_14',
    },
    {
      id: '73-release-metadata-url-step-15',
      action: 'Exercise metadata URL recovery checkpoint 15',
      input: 'release:fixture:73:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_15',
    },
    {
      id: '73-release-metadata-url-step-16',
      action: 'Exercise metadata URL recovery checkpoint 16',
      input: 'release:fixture:73:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_16',
    },
    {
      id: '73-release-metadata-url-step-17',
      action: 'Exercise metadata URL recovery checkpoint 17',
      input: 'release:fixture:73:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_17',
    },
    {
      id: '73-release-metadata-url-step-18',
      action: 'Exercise metadata URL recovery checkpoint 18',
      input: 'release:fixture:73:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_18',
    },
    {
      id: '73-release-metadata-url-step-19',
      action: 'Exercise metadata URL recovery checkpoint 19',
      input: 'release:fixture:73:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_19',
    },
    {
      id: '73-release-metadata-url-step-20',
      action: 'Exercise metadata URL recovery checkpoint 20',
      input: 'release:fixture:73:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_release_checkpoint_20',
    },
    {
      id: '73-release-metadata-url-step-21',
      action: 'Exercise metadata URL recovery checkpoint 21',
      input: 'release:fixture:73:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_release_checkpoint_21',
    },
    {
      id: '73-release-metadata-url-step-22',
      action: 'Exercise metadata URL recovery checkpoint 22',
      input: 'release:fixture:73:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_release_checkpoint_22',
    },
    {
      id: '73-release-metadata-url-step-23',
      action: 'Exercise metadata URL recovery checkpoint 23',
      input: 'release:fixture:73:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_release_checkpoint_23',
    },
    {
      id: '73-release-metadata-url-step-24',
      action: 'Exercise metadata URL recovery checkpoint 24',
      input: 'release:fixture:73:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_release_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario73ReleaseMetadataUrlScenarioSummary = {
  id: Scenario73ReleaseMetadataUrlScenario.id,
  risk: Scenario73ReleaseMetadataUrlScenario.risk,
  stepCount: Scenario73ReleaseMetadataUrlScenario.steps.length,
  recoveryStepCount: Scenario73ReleaseMetadataUrlScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario73ReleaseMetadataUrlScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario73ReleaseMetadataUrlScenarioStep(index: number) {
  if (index < 0 || index >= Scenario73ReleaseMetadataUrlScenario.steps.length) return undefined;
  return Scenario73ReleaseMetadataUrlScenario.steps[index];
}

export function evaluateScenario73ReleaseMetadataUrlScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario73ReleaseMetadataUrlScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario73ReleaseMetadataUrlScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario73ReleaseMetadataUrlScenario.steps.length };
}
