import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario74AccessibilityDynamicTypeClippingScenario: ReleaseScenario = {
  id: '74-accessibility-dynamic-type-clipping',
  domain: 'accessibility',
  title: 'Release QA · Accessibility · dynamic type clipping',
  risk: 'medium',
  steps: [
    {
      id: '74-accessibility-dynamic-type-clipping-step-01',
      action: 'Exercise dynamic type clipping recovery checkpoint 01',
      input: 'accessibility:fixture:74:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_01',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-02',
      action: 'Exercise dynamic type clipping recovery checkpoint 02',
      input: 'accessibility:fixture:74:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_02',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-03',
      action: 'Exercise dynamic type clipping recovery checkpoint 03',
      input: 'accessibility:fixture:74:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_03',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-04',
      action: 'Exercise dynamic type clipping recovery checkpoint 04',
      input: 'accessibility:fixture:74:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_04',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-05',
      action: 'Exercise dynamic type clipping recovery checkpoint 05',
      input: 'accessibility:fixture:74:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_05',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-06',
      action: 'Exercise dynamic type clipping recovery checkpoint 06',
      input: 'accessibility:fixture:74:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_06',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-07',
      action: 'Exercise dynamic type clipping recovery checkpoint 07',
      input: 'accessibility:fixture:74:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_07',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-08',
      action: 'Exercise dynamic type clipping recovery checkpoint 08',
      input: 'accessibility:fixture:74:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_08',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-09',
      action: 'Exercise dynamic type clipping recovery checkpoint 09',
      input: 'accessibility:fixture:74:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_09',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-10',
      action: 'Exercise dynamic type clipping recovery checkpoint 10',
      input: 'accessibility:fixture:74:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_10',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-11',
      action: 'Exercise dynamic type clipping recovery checkpoint 11',
      input: 'accessibility:fixture:74:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_11',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-12',
      action: 'Exercise dynamic type clipping recovery checkpoint 12',
      input: 'accessibility:fixture:74:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_12',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-13',
      action: 'Exercise dynamic type clipping recovery checkpoint 13',
      input: 'accessibility:fixture:74:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_13',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-14',
      action: 'Exercise dynamic type clipping recovery checkpoint 14',
      input: 'accessibility:fixture:74:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_14',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-15',
      action: 'Exercise dynamic type clipping recovery checkpoint 15',
      input: 'accessibility:fixture:74:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_15',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-16',
      action: 'Exercise dynamic type clipping recovery checkpoint 16',
      input: 'accessibility:fixture:74:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_16',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-17',
      action: 'Exercise dynamic type clipping recovery checkpoint 17',
      input: 'accessibility:fixture:74:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_17',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-18',
      action: 'Exercise dynamic type clipping recovery checkpoint 18',
      input: 'accessibility:fixture:74:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_18',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-19',
      action: 'Exercise dynamic type clipping recovery checkpoint 19',
      input: 'accessibility:fixture:74:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_19',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-20',
      action: 'Exercise dynamic type clipping recovery checkpoint 20',
      input: 'accessibility:fixture:74:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_accessibility_checkpoint_20',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-21',
      action: 'Exercise dynamic type clipping recovery checkpoint 21',
      input: 'accessibility:fixture:74:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_accessibility_checkpoint_21',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-22',
      action: 'Exercise dynamic type clipping recovery checkpoint 22',
      input: 'accessibility:fixture:74:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_accessibility_checkpoint_22',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-23',
      action: 'Exercise dynamic type clipping recovery checkpoint 23',
      input: 'accessibility:fixture:74:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_accessibility_checkpoint_23',
    },
    {
      id: '74-accessibility-dynamic-type-clipping-step-24',
      action: 'Exercise dynamic type clipping recovery checkpoint 24',
      input: 'accessibility:fixture:74:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_accessibility_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario74AccessibilityDynamicTypeClippingScenarioSummary = {
  id: Scenario74AccessibilityDynamicTypeClippingScenario.id,
  risk: Scenario74AccessibilityDynamicTypeClippingScenario.risk,
  stepCount: Scenario74AccessibilityDynamicTypeClippingScenario.steps.length,
  recoveryStepCount: Scenario74AccessibilityDynamicTypeClippingScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario74AccessibilityDynamicTypeClippingScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario74AccessibilityDynamicTypeClippingScenarioStep(index: number) {
  if (index < 0 || index >= Scenario74AccessibilityDynamicTypeClippingScenario.steps.length) return undefined;
  return Scenario74AccessibilityDynamicTypeClippingScenario.steps[index];
}

export function evaluateScenario74AccessibilityDynamicTypeClippingScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario74AccessibilityDynamicTypeClippingScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario74AccessibilityDynamicTypeClippingScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario74AccessibilityDynamicTypeClippingScenario.steps.length };
}
