import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario79MediaMissingFileScenario: ReleaseScenario = {
  id: '79-media-missing-file',
  domain: 'media',
  title: 'Release QA · Media · missing file',
  risk: 'high',
  steps: [
    {
      id: '79-media-missing-file-step-01',
      action: 'Exercise missing file recovery checkpoint 01',
      input: 'media:fixture:79:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_01',
    },
    {
      id: '79-media-missing-file-step-02',
      action: 'Exercise missing file recovery checkpoint 02',
      input: 'media:fixture:79:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_02',
    },
    {
      id: '79-media-missing-file-step-03',
      action: 'Exercise missing file recovery checkpoint 03',
      input: 'media:fixture:79:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_03',
    },
    {
      id: '79-media-missing-file-step-04',
      action: 'Exercise missing file recovery checkpoint 04',
      input: 'media:fixture:79:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_04',
    },
    {
      id: '79-media-missing-file-step-05',
      action: 'Exercise missing file recovery checkpoint 05',
      input: 'media:fixture:79:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_05',
    },
    {
      id: '79-media-missing-file-step-06',
      action: 'Exercise missing file recovery checkpoint 06',
      input: 'media:fixture:79:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_06',
    },
    {
      id: '79-media-missing-file-step-07',
      action: 'Exercise missing file recovery checkpoint 07',
      input: 'media:fixture:79:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_07',
    },
    {
      id: '79-media-missing-file-step-08',
      action: 'Exercise missing file recovery checkpoint 08',
      input: 'media:fixture:79:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_08',
    },
    {
      id: '79-media-missing-file-step-09',
      action: 'Exercise missing file recovery checkpoint 09',
      input: 'media:fixture:79:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_09',
    },
    {
      id: '79-media-missing-file-step-10',
      action: 'Exercise missing file recovery checkpoint 10',
      input: 'media:fixture:79:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_10',
    },
    {
      id: '79-media-missing-file-step-11',
      action: 'Exercise missing file recovery checkpoint 11',
      input: 'media:fixture:79:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_11',
    },
    {
      id: '79-media-missing-file-step-12',
      action: 'Exercise missing file recovery checkpoint 12',
      input: 'media:fixture:79:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_12',
    },
    {
      id: '79-media-missing-file-step-13',
      action: 'Exercise missing file recovery checkpoint 13',
      input: 'media:fixture:79:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_13',
    },
    {
      id: '79-media-missing-file-step-14',
      action: 'Exercise missing file recovery checkpoint 14',
      input: 'media:fixture:79:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_14',
    },
    {
      id: '79-media-missing-file-step-15',
      action: 'Exercise missing file recovery checkpoint 15',
      input: 'media:fixture:79:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_15',
    },
    {
      id: '79-media-missing-file-step-16',
      action: 'Exercise missing file recovery checkpoint 16',
      input: 'media:fixture:79:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_16',
    },
    {
      id: '79-media-missing-file-step-17',
      action: 'Exercise missing file recovery checkpoint 17',
      input: 'media:fixture:79:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_17',
    },
    {
      id: '79-media-missing-file-step-18',
      action: 'Exercise missing file recovery checkpoint 18',
      input: 'media:fixture:79:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_18',
    },
    {
      id: '79-media-missing-file-step-19',
      action: 'Exercise missing file recovery checkpoint 19',
      input: 'media:fixture:79:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_19',
    },
    {
      id: '79-media-missing-file-step-20',
      action: 'Exercise missing file recovery checkpoint 20',
      input: 'media:fixture:79:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_media_checkpoint_20',
    },
    {
      id: '79-media-missing-file-step-21',
      action: 'Exercise missing file recovery checkpoint 21',
      input: 'media:fixture:79:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_media_checkpoint_21',
    },
    {
      id: '79-media-missing-file-step-22',
      action: 'Exercise missing file recovery checkpoint 22',
      input: 'media:fixture:79:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_media_checkpoint_22',
    },
    {
      id: '79-media-missing-file-step-23',
      action: 'Exercise missing file recovery checkpoint 23',
      input: 'media:fixture:79:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_media_checkpoint_23',
    },
    {
      id: '79-media-missing-file-step-24',
      action: 'Exercise missing file recovery checkpoint 24',
      input: 'media:fixture:79:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_media_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario79MediaMissingFileScenarioSummary = {
  id: Scenario79MediaMissingFileScenario.id,
  risk: Scenario79MediaMissingFileScenario.risk,
  stepCount: Scenario79MediaMissingFileScenario.steps.length,
  recoveryStepCount: Scenario79MediaMissingFileScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario79MediaMissingFileScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario79MediaMissingFileScenarioStep(index: number) {
  if (index < 0 || index >= Scenario79MediaMissingFileScenario.steps.length) return undefined;
  return Scenario79MediaMissingFileScenario.steps[index];
}

export function evaluateScenario79MediaMissingFileScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario79MediaMissingFileScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario79MediaMissingFileScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario79MediaMissingFileScenario.steps.length };
}
