import type { ReleaseScenario } from '../scenarios/scenarioTypes';

export const Scenario80AuthExpiredTokenScenario: ReleaseScenario = {
  id: '80-auth-expired-token',
  domain: 'auth',
  title: 'Release QA · Auth · expired token',
  risk: 'critical',
  steps: [
    {
      id: '80-auth-expired-token-step-01',
      action: 'Exercise expired token recovery checkpoint 01',
      input: 'auth:fixture:80:1',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_auth_checkpoint_01',
    },
    {
      id: '80-auth-expired-token-step-02',
      action: 'Exercise expired token recovery checkpoint 02',
      input: 'auth:fixture:80:2',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_auth_checkpoint_02',
    },
    {
      id: '80-auth-expired-token-step-03',
      action: 'Exercise expired token recovery checkpoint 03',
      input: 'auth:fixture:80:3',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_auth_checkpoint_03',
    },
    {
      id: '80-auth-expired-token-step-04',
      action: 'Exercise expired token recovery checkpoint 04',
      input: 'auth:fixture:80:4',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_auth_checkpoint_04',
    },
    {
      id: '80-auth-expired-token-step-05',
      action: 'Exercise expired token recovery checkpoint 05',
      input: 'auth:fixture:80:5',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_auth_checkpoint_05',
    },
    {
      id: '80-auth-expired-token-step-06',
      action: 'Exercise expired token recovery checkpoint 06',
      input: 'auth:fixture:80:6',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_auth_checkpoint_06',
    },
    {
      id: '80-auth-expired-token-step-07',
      action: 'Exercise expired token recovery checkpoint 07',
      input: 'auth:fixture:80:7',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_auth_checkpoint_07',
    },
    {
      id: '80-auth-expired-token-step-08',
      action: 'Exercise expired token recovery checkpoint 08',
      input: 'auth:fixture:80:8',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_auth_checkpoint_08',
    },
    {
      id: '80-auth-expired-token-step-09',
      action: 'Exercise expired token recovery checkpoint 09',
      input: 'auth:fixture:80:9',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_auth_checkpoint_09',
    },
    {
      id: '80-auth-expired-token-step-10',
      action: 'Exercise expired token recovery checkpoint 10',
      input: 'auth:fixture:80:10',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_auth_checkpoint_10',
    },
    {
      id: '80-auth-expired-token-step-11',
      action: 'Exercise expired token recovery checkpoint 11',
      input: 'auth:fixture:80:11',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_auth_checkpoint_11',
    },
    {
      id: '80-auth-expired-token-step-12',
      action: 'Exercise expired token recovery checkpoint 12',
      input: 'auth:fixture:80:12',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_auth_checkpoint_12',
    },
    {
      id: '80-auth-expired-token-step-13',
      action: 'Exercise expired token recovery checkpoint 13',
      input: 'auth:fixture:80:13',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_auth_checkpoint_13',
    },
    {
      id: '80-auth-expired-token-step-14',
      action: 'Exercise expired token recovery checkpoint 14',
      input: 'auth:fixture:80:14',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_auth_checkpoint_14',
    },
    {
      id: '80-auth-expired-token-step-15',
      action: 'Exercise expired token recovery checkpoint 15',
      input: 'auth:fixture:80:15',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_auth_checkpoint_15',
    },
    {
      id: '80-auth-expired-token-step-16',
      action: 'Exercise expired token recovery checkpoint 16',
      input: 'auth:fixture:80:16',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_auth_checkpoint_16',
    },
    {
      id: '80-auth-expired-token-step-17',
      action: 'Exercise expired token recovery checkpoint 17',
      input: 'auth:fixture:80:17',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_auth_checkpoint_17',
    },
    {
      id: '80-auth-expired-token-step-18',
      action: 'Exercise expired token recovery checkpoint 18',
      input: 'auth:fixture:80:18',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_auth_checkpoint_18',
    },
    {
      id: '80-auth-expired-token-step-19',
      action: 'Exercise expired token recovery checkpoint 19',
      input: 'auth:fixture:80:19',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_auth_checkpoint_19',
    },
    {
      id: '80-auth-expired-token-step-20',
      action: 'Exercise expired token recovery checkpoint 20',
      input: 'auth:fixture:80:20',
      expectation: 'recover',
      userVisibleMessage: 'Try again after reconnecting.',
      telemetryEvent: 'release_auth_checkpoint_20',
    },
    {
      id: '80-auth-expired-token-step-21',
      action: 'Exercise expired token recovery checkpoint 21',
      input: 'auth:fixture:80:21',
      expectation: 'block',
      userVisibleMessage: 'Show a blocking explanation.',
      telemetryEvent: 'release_auth_checkpoint_21',
    },
    {
      id: '80-auth-expired-token-step-22',
      action: 'Exercise expired token recovery checkpoint 22',
      input: 'auth:fixture:80:22',
      expectation: 'degrade',
      userVisibleMessage: 'Keep existing data visible.',
      telemetryEvent: 'release_auth_checkpoint_22',
    },
    {
      id: '80-auth-expired-token-step-23',
      action: 'Exercise expired token recovery checkpoint 23',
      input: 'auth:fixture:80:23',
      expectation: 'retry',
      userVisibleMessage: 'Retry without duplicate side effects.',
      telemetryEvent: 'release_auth_checkpoint_23',
    },
    {
      id: '80-auth-expired-token-step-24',
      action: 'Exercise expired token recovery checkpoint 24',
      input: 'auth:fixture:80:24',
      expectation: 'redirect',
      userVisibleMessage: 'Navigate to a safe destination.',
      telemetryEvent: 'release_auth_checkpoint_24',
    },
  ],
  invariants: [
    'No uncaught promise rejection is allowed.',
    'No duplicate user-visible action may be committed by a retry.',
    'Sensitive values never enter logs or route parameters.',
    'The user always receives a recoverable state or a clear blocking explanation.',
    'Navigation must remain valid after the scenario completes.',
    'A cancelled operation must not mutate stale UI after unmount.',
    'The app remains usable after the failure path is resolved.',
    'The scenario must not require network connectivity unless explicitly stated.',
    'Mock fixtures remain deterministic so TestFlight repro steps are repeatable.',
    'Error copy must never reveal tokens, URLs with secrets, or internal stack traces.',
    'Permission denial must provide an actionable settings path when applicable.',
    'The release logger records a redacted diagnostic breadcrumb.',
  ],
};

export const Scenario80AuthExpiredTokenScenarioSummary = {
  id: Scenario80AuthExpiredTokenScenario.id,
  risk: Scenario80AuthExpiredTokenScenario.risk,
  stepCount: Scenario80AuthExpiredTokenScenario.steps.length,
  recoveryStepCount: Scenario80AuthExpiredTokenScenario.steps.filter((step) => step.expectation === 'recover' || step.expectation === 'retry').length,
  blockingStepCount: Scenario80AuthExpiredTokenScenario.steps.filter((step) => step.expectation === 'block' || step.expectation === 'redirect').length,
};

export function getScenario80AuthExpiredTokenScenarioStep(index: number) {
  if (index < 0 || index >= Scenario80AuthExpiredTokenScenario.steps.length) return undefined;
  return Scenario80AuthExpiredTokenScenario.steps[index];
}

export function evaluateScenario80AuthExpiredTokenScenario(completedStepIds: string[]) {
  const completed = new Set(completedStepIds);
  const missing = Scenario80AuthExpiredTokenScenario.steps.filter((step) => !completed.has(step.id));
  const status = missing.length === 0 ? 'pass' : completed.size > Scenario80AuthExpiredTokenScenario.steps.length / 2 ? 'warn' : 'fail';
  return { status, missing, completedCount: completed.size, totalCount: Scenario80AuthExpiredTokenScenario.steps.length };
}
